import { defineCatalog } from "./define";

export const CATALOG_AMENAGEMENT_EXTERIEUR = defineCatalog("amenagement-exterieur", {
  "Installation et généralités": [
    ["AE-GEN-101", "Installation et repli de chantier extérieur", "Balisage, protections des végétaux conservés et des accès, repli et nettoyage final.", "forfait", 228, 10, 135, 40, 3],
    ["AE-GEN-102", "Frais de déplacement zone ≤ 30 km", "Aller-retour véhicule et remorque, temps de trajet de l'équipe, par jour d'intervention.", "forfait", 81, 20, 42, 20, 1],
    ["AE-GEN-103", "Main d'œuvre en régie, jardinier", "Heure de travail effectif pour travaux d'entretien non prévus au devis. Fournitures et évacuation en sus.", "h", 51, 20, 38, 0, 1, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
    ["AE-GEN-104", "Main d'œuvre en régie, ouvrier paysagiste ou maçon", "Heure de travail effectif pour travaux d'aménagement non prévus au devis. Fournitures en sus.", "h", 61, 10, 45, 0, 1, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "cloturiste", "installateur-arrosage", "poseur-gazon-synthetique"]],
    ["AE-GEN-105", "Évacuation des déchets verts en déchetterie, au m³ foisonné", "Chargement, transport et redevance de dépôt des tontes, tailles et feuilles.", "m³", 39, 20, 12, 18, 0.3, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
    ["AE-GEN-106", "Benne 8 m³ gravats inertes (terre, béton, pierres)", "Location, rotation et mise en décharge agréée de déchets inertes triés. Chargement non compris.", "U", 503, 10, 22.5, 380, 0.5, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "cloturiste", "poseur-gazon-synthetique"]],
    ["AE-GEN-107", "Location mini-pelle 2,5 t avec chauffeur", "Journée de 8 h, carburant et transport compris dans un rayon de 20 km.", "jour", 700, 10, 400, 160, 8, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "cloturiste", "installateur-arrosage", "poseur-gazon-synthetique"]],
    ["AE-GEN-108", "Forfait petite intervention jardin (≤ 2 h sur place)", "Déplacement, 2 h de main d'œuvre et petites fournitures. Évacuation des déchets verts en sus.", "forfait", 122, 20, 80, 10, 2, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
  ],
  "Entretien des espaces verts": [
    ["AE-ENT-101", "Tonte de pelouse avec ramassage et finitions, au m²", "Tonte, débroussailleuse en bordure, soufflage des allées. Évacuation des tontes en sus.", "m²", 0.5, 20, 0.3, 0.05, 0.008, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-102", "Tonte de pelouse, forfait jardin ≤ 400 m²", "Tonte avec ramassage, bordures et soufflage. Tontes laissées en compost sur place.", "forfait", 71, 20, 47.5, 5, 1.25, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-103", "Scarification et regarnissage de pelouse", "Scarification mécanique, ramassage du feutre, semis de regarnissage et terreautage léger.", "m²", 1.5, 20, 0.76, 0.4, 0.02, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-104", "Débroussaillage de terrain, végétation moyenne", "Débroussailleuse ou broyeur, hauteur ≤ 1 m. Ramassage et évacuation en sus.", "m²", 1.5, 20, 1, 0.1, 0.025, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
    ["AE-ENT-105", "Débroussaillage de terrain envahi (ronces, rejets ligneux)", "Coupe et broyage de végétation dense, rejets ≤ 5 cm. Ramassage et évacuation en sus.", "m²", 3, 20, 2, 0.15, 0.05, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
    ["AE-ENT-106", "Fauchage de prairie ou grande parcelle au gyrobroyeur", "Tracteur ou porte-outil, broyat laissé sur place. Parcelle accessible et sans obstacle.", "m²", 0.5, 20, 0.28, 0.1, 0.005, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-107", "Taille de haie ≤ 2 m, deux faces et dessus", "Taille au taille-haie, ramassage compris. Évacuation des déchets verts en sus.", "ml", 6.5, 20, 4.56, 0.3, 0.12, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-108", "Taille de haie 2 à 4 m (échafaudage ou nacelle)", "Taille deux faces et dessus avec moyens d'accès, ramassage compris. Évacuation en sus.", "ml", 18, 20, 12, 1.5, 0.3, ["paysagiste", "jardinier-espaces-verts", "elagueur"]],
    ["AE-ENT-109", "Taille d'arbuste isolé ≤ 2 m", "Taille de mise en forme ou de floraison, ramassage compris.", "U", 16, 20, 11.4, 0.5, 0.3, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-110", "Taille de fruitier ou de rosiers (par sujet ≤ 5 m)", "Taille de fructification ou de formation, nettoyage du bois mort, ramassage compris.", "U", 28, 20, 20, 1, 0.5, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-111", "Ramassage des feuilles, jardin ≤ 500 m²", "Soufflage, ramassage et évacuation en déchetterie comprise.", "forfait", 131, 20, 76, 25, 2, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-112", "Désherbage manuel de massifs", "Arrachage manuel et binage, ramassage compris. Sans produit phytosanitaire.", "m²", 2.5, 20, 1.9, 0.05, 0.05, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-113", "Désherbage thermique ou mécanique d'allées gravillonnées", "Désherbeur thermique ou brosse rotative, ratissage. Sans produit phytosanitaire.", "m²", 1.5, 20, 0.95, 0.2, 0.025, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-ENT-114", "Contrat d'entretien annuel jardin ≤ 1 000 m² (18 passages)", "Tontes, tailles de haies 2 fois par an, désherbage, feuilles. Évacuation des déchets verts comprise.", "forfait", 2993, 20, 2052, 250, 54, ["paysagiste", "jardinier-espaces-verts"]],
  ],
  "Engazonnement, massifs et plantations": [
    ["AE-PLA-101", "Préparation de sol : décompactage, désherbage et motoculture", "Travail du sol sur 15 à 20 cm, épierrage grossier et ratissage.", "m²", 1.5, 20, 1.2, 0.1, 0.03, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-102", "Apport et régalage de terre végétale criblée", "Fourniture, livraison et régalage à la mini-chargeuse ou à la main, au m³ foisonné.", "m³", 91, 20, 32, 38, 0.8, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-103", "Engazonnement par semis", "Affinage, semis de mélange adapté, roulage et premier arrosage. Garantie de levée sous arrosage client.", "m²", 3, 20, 1.6, 0.6, 0.04, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-104", "Gazon en plaques fourni posé", "Plaques livrées en rouleaux, pose jointive, roulage et arrosage de reprise. Préparation du sol non comprise.", "m²", 13, 20, 4, 5.5, 0.1, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-105", "Création de massif planté (vivaces et arbustes, 5 u/m²)", "Préparation, amendement, plantation et paillage. Végétaux en godets et conteneurs compris.", "m²", 51, 20, 16, 22, 0.4, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-106", "Plantation d'arbuste en conteneur 3 à 5 L", "Trou de plantation, amendement, plantation et arrosage. Végétal compris.", "U", 27, 20, 10, 9, 0.25, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-107", "Plantation de haie, 3 plants/ml (60 à 80 cm)", "Ouverture de tranchée, amendement, plantation, paillage et arrosage. Végétaux compris.", "ml", 36, 20, 12, 15, 0.3, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-108", "Plantation d'arbre tige 10/12 avec tuteurage", "Fosse 80 × 80 cm, terre amendée, tuteur bipode et collier, arrosage. Arbre compris.", "U", 196, 20, 60, 85, 1.5, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-109", "Plantation d'arbre 16/18 en motte grillagée", "Fosse mécanique, haubanage ou tuteurage tripode, cuvette d'arrosage. Arbre compris.", "U", 513, 20, 120, 260, 3, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-110", "Paillage écorces de pin ou minéral ép. 7 cm", "Fourniture et épandage sur sol désherbé. Toile de paillage en sus.", "m²", 9, 20, 2, 4.5, 0.05, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-111", "Toile de paillage tissée agrafée", "Toile perméable fixée aux agrafes, découpes en croix pour les plants.", "m²", 4, 20, 1.6, 1.2, 0.04, ["paysagiste", "jardinier-espaces-verts"]],
    ["AE-PLA-112", "Bordure de massif acier ou aluminium flexible", "Bordure 10 à 15 cm enfoncée avec piquets d'ancrage, découpes et angles.", "ml", 20, 20, 6, 9, 0.15, ["paysagiste", "jardinier-espaces-verts"]],
  ],
  "Élagage, abattage et dessouchage": [
    ["AE-ARB-101", "Élagage d'arbre < 10 m (éclaircie, bois mort)", "Taille raisonnée depuis le sol ou à l'échelle, broyage ou mise en tas. Évacuation en sus.", "U", 189, 20, 125, 15, 2.5, ["elagueur", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARB-102", "Élagage d'arbre 10 à 15 m en grimpe", "Taille raisonnée par grimpeur encordé, rétention des branches. Évacuation en sus.", "U", 425, 20, 275, 40, 5, ["elagueur"]],
    ["AE-ARB-103", "Élagage d'arbre > 15 m (grimpe ou nacelle)", "Taille raisonnée avec équipe de deux et rétention. Location nacelle en sus si nécessaire.", "U", 867, 20, 522, 120, 9, ["elagueur"]],
    ["AE-ARB-104", "Abattage d'arbuste ou conifère ≤ 6 m", "Abattage direct, débitage et mise en tas. Souche laissée à 10 cm du sol.", "U", 74, 20, 45, 10, 1, ["elagueur", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARB-105", "Abattage d'arbre < 10 m, abattage direct", "Abattage directionnel, ébranchage et débitage. Évacuation et dessouchage en sus.", "U", 162, 20, 100, 20, 2, ["elagueur", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARB-106", "Abattage d'arbre 10 à 15 m par démontage", "Démontage par tronçons en grimpe avec rétention, débitage au sol. Évacuation en sus.", "U", 526, 20, 330, 60, 6, ["elagueur"]],
    ["AE-ARB-107", "Abattage d'arbre > 15 m en démontage avec rétention", "Démontage en zone contrainte, équipe de deux, rétention et débitage. Évacuation en sus.", "U", 1183, 20, 696, 180, 12, ["elagueur"]],
    ["AE-ARB-108", "Dessouchage mécanique à la pelle (souche ≤ 50 cm)", "Extraction de la souche et des racines principales, rebouchage. Évacuation de la souche en sus.", "U", 152, 20, 82.5, 30, 1.5, ["elagueur", "paysagiste"]],
    ["AE-ARB-109", "Rognage de souche Ø ≤ 40 cm", "Rognage à la rogneuse jusqu'à 20 cm sous le sol, copeaux laissés en place.", "U", 89, 20, 41.25, 25, 0.75, ["elagueur", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARB-110", "Rognage de souche Ø 40 à 80 cm", "Rognage jusqu'à 20 cm sous le sol, copeaux régalés sur place.", "U", 172, 20, 82.5, 45, 1.5, ["elagueur", "paysagiste"]],
    ["AE-ARB-111", "Broyage de branchages sur site", "Broyeur thermique avec opérateur, copeaux laissés en paillage ou chargés.", "h", 94, 20, 45, 25, 1, ["elagueur", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARB-112", "Évacuation des bois et grumes", "Chargement et transport en plateforme de valorisation, au m³ de bois.", "m³", 45, 20, 13.5, 20, 0.3, ["elagueur", "paysagiste"]],
    ["AE-ARB-113", "Nacelle 16 m avec opérateur, journée", "Location nacelle sur porteur, conduite par opérateur qualifié, carburant compris.", "jour", 900, 20, 440, 280, 8, ["elagueur"]],
    ["AE-ARB-114", "Diagnostic visuel d'arbre avec compte rendu", "Examen du houppier, du tronc et du collet, préconisations écrites et photos.", "forfait", 126, 20, 90, 0, 1.5, ["elagueur"]],
  ],
  "Terrassement et préparation": [
    ["AE-TER-101", "Décapage de terre végétale ép. 20 cm, mise en dépôt", "Décapage à la mini-pelle et stockage sur site pour réemploi. Évacuation non comprise.", "m²", 3.5, 10, 2, 0.5, 0.04, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "poseur-gazon-synthetique"]],
    ["AE-TER-102", "Terrassement pour terrasse ou allée, ép. 20 à 30 cm", "Décaissement mécanique et réglage du fond de forme. Évacuation non comprise.", "m³", 30, 10, 20, 3, 0.4, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "poseur-gazon-synthetique", "cloturiste"]],
    ["AE-TER-103", "Évacuation des terres en décharge (≤ 20 km)", "Chargement, transport et redevance de mise en décharge de terres non polluées, au m³ en place.", "m³", 45, 10, 12.5, 22, 0.25, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "poseur-gazon-synthetique"]],
    ["AE-TER-104", "Fond de forme en grave 0/31,5 compactée ép. 15 cm", "Fourniture, réglage et compactage à la plaque vibrante.", "m²", 13.5, 10, 4.5, 6, 0.1, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "poseur-gazon-synthetique"]],
    ["AE-TER-105", "Géotextile anti-contaminant sous fond de forme", "Géotextile non tissé, recouvrements de 30 cm.", "m²", 2.5, 10, 0.9, 0.9, 0.02, ["paysagiste", "macon-paysagiste", "poseur-terrasse", "poseur-gazon-synthetique"]],
    ["AE-TER-106", "Drain agricole Ø 100 sous gravier et géotextile", "Tranchée, drain, enrobage gravier 20/40 et géotextile. Exutoire existant.", "ml", 39, 10, 18, 12, 0.4, ["paysagiste", "macon-paysagiste", "installateur-arrosage"]],
  ],
  "Terrasses bois et dalles sur plots": [
    ["AE-TRS-101", "Terrasse pin classe 4 sur lambourdes, lames 27 mm", "Lambourdes sur plots ou dalle, lames rainurées vissées inox, film anti-racines.", "m²", 136, 10, 52.8, 48, 1.1, ["poseur-terrasse", "paysagiste", "macon-paysagiste"]],
    ["AE-TRS-102", "Terrasse pin classe 4 sur plots réglables", "Plots PVC réglables, lambourdes et lames 27 mm. Pour sol stabilisé non porteur de dalle.", "m²", 135, 10, 48, 52, 1, ["poseur-terrasse", "paysagiste", "macon-paysagiste"]],
    ["AE-TRS-103", "Terrasse douglas ou mélèze sur lambourdes", "Bois résineux durable sans traitement, vis inox, espacement de ventilation.", "m²", 146, 10, 52.8, 55, 1.1, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-104", "Terrasse bois exotique (ipé, cumaru) sur lambourdes", "Lames 21 mm prépercées, lambourdes exotiques et vis inox.", "m²", 236, 10, 70, 105, 1.4, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-105", "Terrasse composite lames pleines sur lambourdes aluminium", "Lames pleines coextrudées, clips invisibles, lambourdes alu sur plots.", "m²", 209, 10, 60, 95, 1.2, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-106", "Terrasse sur structure surélevée > 60 cm", "Poteaux sur plots béton, solives et contreventement, platelage pin. Garde-corps non compris.", "m²", 236, 10, 100, 75, 2, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-107", "Dalles grès cérame 2 cm sur plots réglables", "Plots et dalles R11, calepinage et coupes. Sur support stabilisé ou étanchéité.", "m²", 136, 10, 38.4, 62, 0.8, ["poseur-terrasse", "paysagiste", "macon-paysagiste"]],
    ["AE-TRS-108", "Dalles béton ou pierre reconstituée sur plots", "Dalles 40 × 60 sur plots réglables, coupes et ajustement des niveaux.", "m²", 102, 10, 33.6, 42, 0.7, ["poseur-terrasse", "paysagiste", "macon-paysagiste"]],
    ["AE-TRS-109", "Garde-corps de terrasse bois ou aluminium", "Poteaux fixés en structure, main courante et remplissage barreaudage ou câbles.", "ml", 290, 10, 75, 140, 1.5, ["poseur-terrasse", "paysagiste", "cloturiste"]],
    ["AE-TRS-110", "Dépose de terrasse bois et évacuation", "Dévissage ou découpe des lames et lambourdes, tri et déchetterie.", "m²", 26, 10, 15.75, 4, 0.35, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-111", "Rénovation de terrasse bois : nettoyage, ponçage et saturateur", "Dégriseur, rinçage, ponçage léger et deux couches de saturateur.", "m²", 22, 10, 13.5, 3, 0.3, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-112", "Remplacement de lames de terrasse abîmées", "Dépose, lame neuve de même essence, vissage inox. Au ml de lame.", "ml", 25, 10, 9.6, 9, 0.2, ["poseur-terrasse", "paysagiste"]],
    ["AE-TRS-113", "Spot LED encastré dans terrasse ou marche", "Spot basse tension étanche, câblage et transformateur partagé. Ligne d'alimentation non comprise.", "U", 103, 10, 41.25, 35, 0.75, ["poseur-terrasse", "paysagiste", "macon-paysagiste"]],
  ],
  "Allées, pavage et dallage": [
    ["AE-ALL-101", "Pavés béton 6 cm sur lit de sable", "Lit de sable réglé, pavés, coupes, compactage et sablage. Fond de forme non compris.", "m²", 97, 10, 48, 24, 1, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-102", "Pavés béton 8 cm carrossables sur lit de gravillons", "Pose sur lit 2/6 réglé, coupes, compactage et sablage. Fond de forme non compris.", "m²", 121, 10, 57.6, 32, 1.2, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-103", "Pavés pierre naturelle (granit, grès) scellés", "Pose au mortier sur dalle, joints au mortier. Dalle support non comprise.", "m²", 223, 10, 100, 65, 2, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-104", "Dallage pierre naturelle scellé sur dalle", "Calcaire ou travertin, pose au mortier, joints et hydrofuge. Dalle support non comprise.", "m²", 182, 10, 75, 60, 1.5, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-105", "Allée gravillons ép. 5 cm sur géotextile", "Géotextile et gravillons concassés ou roulés réglés. Fond de forme non compris.", "m²", 17, 10, 6.75, 6, 0.15, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-106", "Allée gravier stabilisé en plaques alvéolaires", "Plaques nid d'abeille sur lit de sable, remplissage gravier. Carrossable léger.", "m²", 48, 10, 13.5, 22, 0.3, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-107", "Allée en sable stabilisé au liant ép. 8 cm", "Mélange sable et liant hydraulique, réglage, compactage et humidification.", "m²", 40, 10, 15.75, 14, 0.35, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-108", "Béton désactivé ép. 12 cm", "Coffrage, béton désactivé, lavage et joints de fractionnement. Fond de forme non compris.", "m²", 98, 10, 38.4, 34, 0.8, ["macon-paysagiste", "paysagiste"]],
    ["AE-ALL-109", "Bordure béton P1 sur fondation béton", "Bordure 6 × 20 posée au cordeau sur béton maigre, joints au mortier.", "ml", 29, 10, 15.75, 6, 0.35, ["macon-paysagiste", "paysagiste", "poseur-terrasse"]],
    ["AE-ALL-110", "Caniveau à grille en limite d'allée ou de terrasse", "Caniveau béton polymère sur béton, grille acier, raccordement à l'exutoire existant.", "ml", 103, 10, 38.4, 38, 0.8, ["macon-paysagiste", "paysagiste", "poseur-terrasse"]],
    ["AE-ALL-111", "Dépose de dallage ou pavage existant et évacuation", "Dépose mécanique, tri et mise en décharge. Démolition de dalle béton en sus.", "m²", 34, 10, 18, 8, 0.4, ["macon-paysagiste", "paysagiste"]],
  ],
  "Maçonnerie paysagère": [
    ["AE-MAC-101", "Muret blocs béton h 0,60 m sur semelle, enduit deux faces", "Semelle filante, blocs 20 cm chaînés et enduit. Terrassement non compris.", "ml", 315, 10, 168, 65, 3.5, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-102", "Muret en pierre sèche", "Construction traditionnelle sans mortier, pierres locales fournies, au m² de face vue.", "m²", 483, 10, 288, 70, 6, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-103", "Parement pierre naturelle sur muret existant", "Moellons ou plaquettes scellés, joints brossés, au m² de face.", "m²", 296, 10, 144, 75, 3, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-104", "Gabions remplis de pierre", "Cages galvanisées montées, remplissage manuel en face vue, au m³ de gabion.", "m³", 331, 10, 135, 110, 3, ["macon-paysagiste", "paysagiste", "cloturiste"]],
    ["AE-MAC-105", "Chaperon ou couvertine pierre reconstituée", "Pose au mortier sur muret, joints et pente d'écoulement.", "ml", 54, 10, 18, 22, 0.4, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-106", "Escalier extérieur béton coffré, par marche", "Coffrage, armatures et béton, finition balayée. Revêtement non compris.", "U", 255, 10, 144, 45, 3, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-107", "Marche en bloc pierre ou traverse bois, par marche", "Bloc ou traverse posé sur lit de béton, remblai et calage.", "U", 147, 10, 54, 55, 1.2, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-108", "Enrochement en blocs calcaires posés à la pelle", "Blocs 0,5 à 1 t posés et calés, terre végétale en joints, au m³ d'ouvrage.", "m³", 251, 10, 66, 120, 1.2, ["macon-paysagiste", "paysagiste"]],
    ["AE-MAC-109", "Pilier maçonné 30 × 30 pour portail avec chapeau", "Fondation, blocs à bancher armés, enduit et chapeau pierre reconstituée.", "U", 408, 10, 192, 110, 4, ["macon-paysagiste", "cloturiste"]],
  ],
  "Clôtures et portillons": [
    ["AE-CLO-101", "Clôture grillage simple torsion h 1,50 m, poteaux scellés", "Poteaux tous les 2,50 m avec jambes de force, fils de tension et grillage plastifié.", "ml", 37, 10, 15.75, 12, 0.35, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-102", "Clôture grillage simple torsion h 2,00 m, poteaux scellés", "Poteaux tous les 2,50 m, jambes de force, 4 fils de tension et grillage plastifié.", "ml", 45, 10, 18, 15, 0.4, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-103", "Clôture panneaux rigides h 1,23 m, fil 4 mm", "Panneaux plastifiés, poteaux à clips scellés au béton.", "ml", 71, 10, 20.25, 32, 0.45, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-104", "Clôture panneaux rigides h 2,03 m, fil 5 mm", "Panneaux renforcés, poteaux scellés, platines si muret. Soubassement non compris.", "ml", 112, 10, 24.75, 58, 0.55, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-105", "Lames d'occultation PVC pour panneaux rigides", "Lames rigides glissées dans les mailles avec profils de finition.", "ml", 62, 10, 18, 28, 0.4, ["cloturiste", "paysagiste"]],
    ["AE-CLO-106", "Soubassement béton 25 cm sous clôture", "Plaques béton entre poteaux spéciaux, calage et alignement.", "ml", 34, 10, 13.5, 12, 0.3, ["cloturiste", "macon-paysagiste"]],
    ["AE-CLO-107", "Clôture bois lames horizontales h 1,80 m", "Poteaux bois ou alu scellés, lames pin classe 4 ou douglas vissées.", "ml", 180, 10, 48, 85, 1, ["cloturiste", "paysagiste"]],
    ["AE-CLO-108", "Clôture ganivelle châtaignier h 1,20 m", "Piquets châtaignier enfoncés et ganivelle tendue sur fils.", "ml", 43, 10, 13.5, 18, 0.3, ["cloturiste", "paysagiste"]],
    ["AE-CLO-109", "Clôture aluminium lames pleines h 1,80 m", "Poteaux scellés ou sur platines, lames emboîtées et capots.", "ml", 364, 10, 50, 220, 1, ["cloturiste", "paysagiste"]],
    ["AE-CLO-110", "Clôture composite occultante h 1,80 m", "Poteaux aluminium, lames composites emboîtées et lisses de finition.", "ml", 267, 10, 48, 150, 1, ["cloturiste", "paysagiste"]],
    ["AE-CLO-111", "Portillon acier galvanisé 1 m, h 1,20 m", "Portillon assorti aux panneaux, poteaux scellés, serrure et gâche.", "U", 432, 10, 90, 230, 2, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-112", "Portillon bois ou aluminium 1 m, h 1,80 m", "Poteaux scellés, gonds et serrure. Motorisation et contrôle d'accès exclus.", "U", 896, 10, 144, 520, 3, ["cloturiste", "paysagiste"]],
    ["AE-CLO-113", "Portail battant grillagé 3 m, deux vantaux", "Portail acier assorti à la clôture, poteaux scellés, butée et verrou.", "U", 945, 10, 180, 520, 4, ["cloturiste", "paysagiste"]],
    ["AE-CLO-114", "Dépose de clôture existante et évacuation", "Arrachage des poteaux, enroulement du grillage, tri et déchetterie.", "ml", 15, 10, 9, 2, 0.2, ["cloturiste", "paysagiste", "macon-paysagiste"]],
    ["AE-CLO-115", "Remplacement d'un panneau rigide endommagé", "Dépose du panneau, fourniture et pose d'un panneau assorti avec clips.", "U", 122, 10, 45, 45, 1, ["cloturiste"]],
  ],
  "Arrosage automatique": [
    ["AE-ARR-101", "Étude et plan d'arrosage (débit, pression, zonage)", "Relevé, mesure débit et pression, plan des zones et liste du matériel.", "forfait", 154, 10, 110, 0, 2, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-102", "Zone d'arrosage enterré par tuyères (≤ 80 m²)", "Tranchées, PE, tuyères, électrovanne en regard et raccordements. Programmateur non compris.", "U", 443, 10, 208, 120, 4, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-103", "Zone d'arrosage enterré par turbines (≤ 300 m²)", "Tranchées, PE, turbines, électrovanne en regard et raccordements. Programmateur non compris.", "U", 594, 10, 260, 180, 5, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-104", "Zone goutte-à-goutte enterré pour haie ou massif (≤ 50 ml)", "Gaine goutteuse enterrée, électrovanne, filtre et réducteur de pression.", "U", 339, 10, 156, 95, 3, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-105", "Goutte-à-goutte de surface en massif", "Tuyau goutteur posé sous paillage, raccords et piquets.", "ml", 4.5, 20, 2.25, 1.2, 0.05, ["installateur-arrosage", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARR-106", "Tranchée à la trancheuse et tube PE Ø 25", "Ouverture, pose du tube et remblaiement, au ml.", "ml", 11, 10, 6, 2.2, 0.12, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-107", "Programmateur 6 stations raccordé", "Pose murale, câblage des électrovannes et programmation.", "U", 354, 10, 82.5, 180, 1.5, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-108", "Programmateur connecté avec pilotage à distance", "Pose, câblage des électrovannes, appairage et programmation avec le client.", "U", 462, 10, 82.5, 260, 1.5, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-109", "Programmateur sur robinet à piles", "Programmateur autonome monté sur robinet extérieur et réglage.", "U", 79, 20, 13.5, 45, 0.3, ["installateur-arrosage", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARR-110", "Électrovanne supplémentaire en regard", "Regard, électrovanne, raccords et câblage jusqu'au programmateur.", "U", 171, 10, 52, 75, 1, ["installateur-arrosage"]],
    ["AE-ARR-111", "Sonde de pluie raccordée", "Pose en hauteur dégagée et raccordement au programmateur.", "U", 107, 10, 39, 40, 0.75, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-112", "Raccordement au réseau avec clapet anti-retour et filtre", "Piquage après compteur, disconnecteur ou clapet, filtre et vanne d'arrêt.", "forfait", 329, 10, 104, 140, 2, ["installateur-arrosage", "paysagiste"]],
    ["AE-ARR-113", "Pompe immergée pour puits ou forage avec surpresseur", "Pompe, ballon, pressostat et raccordements. Ligne électrique non comprise.", "U", 913, 10, 156, 520, 3, ["installateur-arrosage"]],
    ["AE-ARR-114", "Récupérateur d'eau de pluie enterré 3 m³ raccordé", "Fouille, cuve, filtre, trop-plein et raccordement aux descentes. Évacuation des terres en sus.", "U", 2704, 10, 480, 1600, 10, ["installateur-arrosage", "paysagiste", "macon-paysagiste"]],
    ["AE-ARR-115", "Mise en route de l'arrosage au printemps", "Remise en eau, contrôle des zones, réglage des arroseurs et du programmateur.", "forfait", 115, 10, 75, 10, 1.5, ["installateur-arrosage", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARR-116", "Hivernage du réseau d'arrosage", "Vidange ou purge à l'air comprimé, dépose des piles, protection des organes.", "forfait", 108, 10, 75, 5, 1.5, ["installateur-arrosage", "paysagiste", "jardinier-espaces-verts"]],
    ["AE-ARR-117", "Réparation de fuite ou remplacement d'arroseur", "Recherche localisée, réparation par raccord ou arroseur neuf, réglage.", "U", 80, 10, 37.5, 22, 0.75, ["installateur-arrosage", "paysagiste", "jardinier-espaces-verts"]],
  ],
  "Gazon synthétique": [
    ["AE-GAZ-101", "Dégazonnage et décaissement 10 cm pour gazon synthétique", "Enlèvement du gazon et de la terre, chargement. Évacuation en décharge en sus.", "m²", 11.5, 20, 5.4, 3, 0.12, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-102", "Fond de forme concassé 0/20 et sable de réglage", "Concassé compacté et lit de sable réglé à 1 % de pente.", "m²", 13, 20, 4.5, 5, 0.1, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-103", "Gazon synthétique 25 mm fourni posé", "Déroulage, jonctions collées, découpes et brossage. Fond de forme non compris.", "m²", 34, 20, 9, 16, 0.2, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-104", "Gazon synthétique 50 mm haut de gamme fourni posé", "Fibres denses, jonctions collées, découpes, lestage et brossage. Fond de forme non compris.", "m²", 57, 20, 9.9, 32, 0.22, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-105", "Gazon synthétique sur dalle ou terrasse béton, sous-couche drainante", "Sous-couche drainante, gazon collé en périphérie et découpes.", "m²", 45, 20, 9, 24, 0.2, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-106", "Lestage au sable siliceux", "Épandage du sable et brossage à contre-poil.", "m²", 4, 20, 1.35, 1.5, 0.03, ["poseur-gazon-synthetique"]],
    ["AE-GAZ-107", "Bande de jonction et colle bicomposant", "Jonction supplémentaire entre lés, au ml.", "ml", 10.5, 20, 3.6, 4, 0.08, ["poseur-gazon-synthetique"]],
    ["AE-GAZ-108", "Bordure de finition pour gazon synthétique", "Bordure bois ou PVC fixée par piquets, au ml.", "ml", 17, 20, 6.75, 6, 0.15, ["poseur-gazon-synthetique", "paysagiste"]],
    ["AE-GAZ-109", "Gazon synthétique de balcon ou terrasse ≤ 15 m²", "Forfait gazon 30 mm sur support dur, découpes et fixation périphérique.", "forfait", 560, 20, 135, 280, 3, ["poseur-gazon-synthetique"]],
    ["AE-GAZ-110", "Entretien de gazon synthétique (brossage, décompactage)", "Ramassage des feuilles, brossage mécanique et regarnissage de sable.", "m²", 1.5, 20, 0.9, 0.2, 0.02, ["poseur-gazon-synthetique", "paysagiste", "jardinier-espaces-verts"]],
  ],
});
