import { defineCatalog } from "./define";

export const CATALOG_CONCEPTION_ENCADREMENT = defineCatalog("conception-encadrement", {
  "Honoraires et frais": [
    ["CE-HON-101", "Honoraires au temps passé, architecte", "Heure de conception, conseil ou réunion hors mission forfaitaire. Frais de reprographie et déplacements hors zone en sus.", "h", 119.5, 20, 90, 2, 1, ["architecte", "architecte-interieur"]],
    ["CE-HON-102", "Honoraires au temps passé, ingénieur ou économiste", "Heure d'étude, de calcul ou d'expertise hors mission forfaitaire.", "h", 113, 20, 85, 2, 1, ["bureau-etudes", "economiste-construction", "coordinateur-sps", "maitre-oeuvre"]],
    ["CE-HON-103", "Honoraires au temps passé, technicien ou dessinateur", "Heure de dessin, de saisie ou de mise au net de plans et pièces écrites.", "h", 83.5, 20, 60, 2, 1, ["architecte", "architecte-interieur", "maitre-oeuvre", "bureau-etudes", "geometre-topographe", "economiste-construction"]],
    ["CE-HON-104", "Honoraires au temps passé, décorateur", "Heure de conseil, de recherche de produits ou de coordination fournisseurs.", "h", 89, 20, 65, 1, 1, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-HON-105", "Honoraires au temps passé, géomètre", "Heure de terrain ou de bureau hors prestation forfaitaire, matériel compris.", "h", 108, 20, 80, 3, 1, ["geometre-topographe"]],
    ["CE-HON-106", "Vacation à la journée sur site ou en bureau", "Journée de 8 h d'un intervenant qualifié, pour mission non forfaitisée.", "jour", 806, 20, 600, 20, 8],
    ["CE-HON-107", "Frais de déplacement hors zone, par intervention", "Temps de trajet et frais de véhicule au-delà de 30 km du siège.", "forfait", 123.5, 20, 65, 30, 1],
    ["CE-HON-108", "Reprographie et dossiers papier", "Tirages grand format, reliures et envois de dossiers papier (permis, DCE, DOE).", "forfait", 112.5, 20, 30, 60, 0.5],
  ],
  "Relevés et état des lieux": [
    ["CE-REL-101", "Relevé de l'existant intérieur avec plans 2D", "Relevé au télémètre, plans de niveaux cotés au format DAO, au m² de surface relevée.", "m²", 8, 20, 5.6, 0.2, 0.08, ["architecte", "architecte-interieur", "maitre-oeuvre", "decorateur-interieur", "geometre-topographe"]],
    ["CE-REL-102", "Relevé par scanner 3D et nuage de points, bâtiment ≤ 200 m²", "Acquisition laser, assemblage, nuage de points et plans 2D extraits. Maquette BIM en sus.", "forfait", 1391, 20, 1020, 50, 12, ["geometre-topographe", "architecte", "bureau-etudes"]],
    ["CE-REL-103", "Plan topographique de parcelle ≤ 1 000 m², courbes de niveau", "Levé au GNSS ou station, altimétrie, arbres, réseaux visibles et limites apparentes.", "forfait", 871, 20, 640, 30, 8, ["geometre-topographe"]],
    ["CE-REL-104", "Plan topographique de terrain de 1 000 à 5 000 m²", "Levé complet avec altimétrie, ouvrages, réseaux visibles et rattachement au système légal.", "forfait", 1521, 20, 1120, 50, 14, ["geometre-topographe"]],
    ["CE-REL-105", "État des lieux et constat avant travaux", "Visite contradictoire, constat photographique des avoisinants et rapport daté.", "forfait", 403, 20, 300, 10, 4, ["architecte", "maitre-oeuvre", "conducteur-travaux", "economiste-construction"]],
    ["CE-REL-106", "Diagnostic technique de l'existant et étude de faisabilité", "Visite, analyse des structures, réseaux et contraintes réglementaires, rapport de faisabilité.", "forfait", 903.5, 20, 680, 15, 8, ["architecte", "maitre-oeuvre", "bureau-etudes", "economiste-construction"]],
  ],
  "Conception architecturale et autorisations": [
    ["CE-ARC-101", "Visite conseil d'architecte à domicile (2 h)", "Analyse du besoin, premières pistes d'aménagement et contraintes réglementaires. Compte rendu succinct.", "forfait", 293.5, 20, 212.5, 5, 2.5, ["architecte", "architecte-interieur"]],
    ["CE-ARC-102", "Étude de faisabilité et de capacité de terrain", "Analyse du PLU, gabarits constructibles et scénarios d'implantation.", "forfait", 1352, 20, 1020, 20, 12, ["architecte", "maitre-oeuvre", "economiste-construction"]],
    ["CE-ARC-103", "Esquisse (ESQ), maison ou extension", "Programme, deux à trois partis d'implantation et volumétrie, estimation au ratio.", "forfait", 1807, 20, 1360, 30, 16, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-104", "Avant-projet sommaire (APS), extension ≤ 50 m²", "Plans, coupes et façades au 1/100, notice et estimation par grands postes.", "forfait", 2262, 20, 1700, 40, 20, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-105", "Avant-projet définitif (APD)", "Plans au 1/50, choix des matériaux et systèmes, estimation détaillée par lot.", "forfait", 2717, 20, 2040, 50, 24, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-106", "Dossier de permis de construire, maison individuelle", "Pièces graphiques et écrites, notice, insertion, formulaires et dépôt. Attestation RE2020 non comprise.", "forfait", 3224, 20, 2400, 80, 30, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-107", "Dossier de déclaration préalable de travaux", "Plans, insertion, photos et formulaire CERFA pour extension, façade ou abri.", "forfait", 1014, 20, 750, 30, 10, ["architecte", "maitre-oeuvre", "architecte-interieur"]],
    ["CE-ARC-108", "Permis de construire modificatif", "Mise à jour des pièces impactées et dépôt du dossier modificatif.", "forfait", 1072.5, 20, 800, 25, 10, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-109", "Dossier d'autorisation de travaux ERP", "Pièces graphiques, notices et formulaire pour aménagement ou modification d'ERP.", "forfait", 1586, 20, 1190, 30, 14, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-110", "Projet (PRO) : plans et descriptif de conception, au m² SHAB", "Plans au 1/50, détails principaux et descriptif technique pour consultation.", "m²", 37, 20, 28, 0.5, 0.35, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-111", "Plans d'exécution détaillés (EXE), au m² SHAB", "Plans d'exécution et détails au 1/20 pour les lots architecturaux.", "m²", 30, 20, 22.5, 0.5, 0.3, ["architecte", "maitre-oeuvre", "bureau-etudes"]],
    ["CE-ARC-112", "Mission complète d'architecte, maison neuve ≤ 150 m²", "De l'esquisse à la réception : ESQ, APS, APD, PC, PRO, DCE, ACT, DET et AOR.", "forfait", 31320, 20, 25500, 600, 300, ["architecte"]],
    ["CE-ARC-113", "Mission complète, rénovation ou extension", "Conception, autorisation, consultation, suivi et réception d'une opération de rénovation.", "forfait", 12540, 20, 10200, 250, 120, ["architecte", "maitre-oeuvre"]],
    ["CE-ARC-114", "Mission de base maître d'œuvre : permis et suivi léger", "Plans, dépôt du permis, consultation des entreprises et visites ponctuelles de chantier.", "forfait", 5375, 20, 4200, 100, 60, ["maitre-oeuvre"]],
  ],
  "Consultation, suivi et réception": [
    ["CE-MOE-101", "CCTP ou descriptif technique, par lot", "Rédaction des prescriptions techniques et limites de prestations d'un lot.", "U", 422.5, 20, 320, 5, 4, ["architecte", "maitre-oeuvre", "economiste-construction"]],
    ["CE-MOE-102", "Dossier de consultation des entreprises (DCE), ≤ 8 lots", "CCTP, DPGF, plans, planning et règlement de consultation, diffusion aux entreprises.", "forfait", 3185, 20, 2400, 50, 30, ["architecte", "maitre-oeuvre", "economiste-construction"]],
    ["CE-MOE-103", "Consultation simplifiée : trois devis comparés", "Recherche d'entreprises, envoi du descriptif et tableau comparatif des offres.", "forfait", 370.5, 20, 280, 5, 4, ["maitre-oeuvre", "conducteur-travaux", "economiste-construction", "architecte-interieur"]],
    ["CE-MOE-104", "Assistance aux contrats de travaux (ACT)", "Analyse des offres, négociation et mise au point des marchés.", "forfait", 1690, 20, 1280, 20, 16, ["architecte", "maitre-oeuvre", "economiste-construction"]],
    ["CE-MOE-105", "Visite de chantier avec compte rendu (DET)", "Visite, constat d'avancement, réserves et diffusion du compte rendu.", "U", 266.5, 20, 200, 5, 2.5, ["architecte", "maitre-oeuvre", "conducteur-travaux"]],
    ["CE-MOE-106", "Direction de l'exécution, forfait mensuel", "Quatre visites, comptes rendus, suivi financier et vérification des situations du mois.", "forfait", 1703, 20, 1280, 30, 16, ["architecte", "maitre-oeuvre"]],
    ["CE-MOE-107", "Vérification d'une situation de travaux", "Contrôle des quantités et de l'avancement, proposition de paiement.", "U", 154.5, 20, 112.5, 2, 1.5, ["economiste-construction", "maitre-oeuvre", "architecte", "conducteur-travaux"]],
    ["CE-MOE-108", "Décompte général définitif", "Récapitulatif des marchés, avenants, pénalités et retenues de garantie par entreprise.", "forfait", 630.5, 20, 480, 5, 6, ["economiste-construction", "maitre-oeuvre", "architecte"]],
    ["CE-MOE-109", "Ordonnancement, pilotage et coordination (OPC), forfait mensuel", "Planning détaillé tenu à jour, coordination des interventions et réunions dédiées.", "forfait", 1586, 20, 1200, 20, 16, ["maitre-oeuvre", "conducteur-travaux", "architecte"]],
    ["CE-MOE-110", "Planning prévisionnel tous corps d'état", "Planning à barres par lot avec enchaînements et jalons, mis à jour une fois.", "forfait", 598, 20, 450, 10, 6, ["conducteur-travaux", "maitre-oeuvre", "architecte", "economiste-construction"]],
    ["CE-MOE-111", "Assistance aux opérations de réception (AOR)", "Opérations préalables, procès-verbal, liste et levée des réserves.", "forfait", 858, 20, 640, 20, 8, ["architecte", "maitre-oeuvre", "conducteur-travaux"]],
    ["CE-MOE-112", "Visite de levée de réserves ou de parfait achèvement", "Visite contradictoire et constat de levée, par visite.", "U", 209, 20, 150, 5, 2, ["conducteur-travaux", "maitre-oeuvre", "architecte"]],
    ["CE-MOE-113", "Dossier des ouvrages exécutés (DOE)", "Collecte, vérification et assemblage des plans, notices et garanties des entreprises.", "forfait", 767, 20, 560, 30, 8, ["architecte", "maitre-oeuvre", "conducteur-travaux", "bureau-etudes"]],
  ],
  "Conduite de travaux": [
    ["CE-CDT-101", "Conduite de travaux, journée sur chantier", "Présence, organisation des équipes, contrôle de la qualité et de l'avancement.", "jour", 702, 20, 520, 20, 8, ["conducteur-travaux"]],
    ["CE-CDT-102", "Conduite de travaux, demi-journée", "Intervention de 4 h sur chantier pour coordination ou contrôle.", "U", 351, 20, 260, 10, 4, ["conducteur-travaux"]],
    ["CE-CDT-103", "Réunion de chantier hebdomadaire avec compte rendu", "Animation de la réunion, suivi des actions et diffusion du compte rendu.", "U", 223.5, 20, 162.5, 3, 2.5, ["conducteur-travaux", "maitre-oeuvre"]],
    ["CE-CDT-104", "Gestion des commandes et approvisionnements, forfait mensuel", "Quantitatifs, demandes de prix, commandes et suivi des livraisons.", "forfait", 637, 20, 480, 10, 8, ["conducteur-travaux"]],
    ["CE-CDT-105", "Préparation de chantier : installation, accès et phasage", "Plan d'installation, accès, phasage et liste des autorisations à obtenir.", "forfait", 520, 20, 390, 10, 6, ["conducteur-travaux", "maitre-oeuvre"]],
  ],
  "Économie de la construction": [
    ["CE-ECO-101", "Estimation sommaire au ratio", "Estimation par ratios au m² et par grands postes à partir d'un programme ou d'une esquisse.", "forfait", 385, 20, 280, 5, 3.5, ["economiste-construction", "architecte", "maitre-oeuvre"]],
    ["CE-ECO-102", "Estimation détaillée par lots", "Métrés sur plans et chiffrage par ouvrage élémentaire, synthèse par lot.", "forfait", 1690, 20, 1280, 20, 16, ["economiste-construction", "maitre-oeuvre"]],
    ["CE-ECO-103", "Métré tous corps d'état, au m² SHAB", "Quantitatifs de tous les lots à partir des plans, édition par ouvrage.", "m²", 10.5, 20, 7.5, 0.1, 0.1, ["economiste-construction"]],
    ["CE-ECO-104", "Cadre de décomposition DPGF, par lot", "Rédaction du cadre de prix aligné sur le CCTP, quantités indicatives.", "U", 308, 20, 225, 3, 3, ["economiste-construction", "maitre-oeuvre", "architecte"]],
    ["CE-ECO-105", "Expertise de devis et contre-chiffrage", "Vérification des quantités et prix d'un devis d'entreprise, avis écrit.", "U", 316, 20, 240, 3, 3, ["economiste-construction", "maitre-oeuvre"]],
    ["CE-ECO-106", "Chiffrage de désordres ou de travaux de reprise", "Constat, métrés et estimation des reprises pour assurance ou litige.", "forfait", 955.5, 20, 720, 15, 8, ["economiste-construction", "bureau-etudes"]],
    ["CE-ECO-107", "Plan pluriannuel de travaux de copropriété", "Analyse du bâti, travaux à 10 ans hiérarchisés et chiffrés. DPE collectif non compris.", "forfait", 3380, 20, 2550, 50, 30, ["economiste-construction", "architecte", "bureau-etudes"]],
    ["CE-ECO-108", "Montage de dossier d'aides à la rénovation", "Constitution du dossier, devis éligibles et suivi des demandes de paiement.", "forfait", 468, 20, 350, 10, 5, ["economiste-construction", "maitre-oeuvre", "bureau-etudes"]],
  ],
  "Architecture intérieure et décoration": [
    ["CE-DEC-101", "Visite conseil déco à domicile (2 h)", "Échanges sur le style, l'agencement et les couleurs, conseils oraux et notes remises.", "forfait", 179.5, 20, 130, 3, 2, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-DEC-102", "Planche tendance par pièce", "Ambiance, matières, couleurs et références de mobilier sur une planche illustrée.", "U", 250, 20, 180, 5, 3, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-DEC-103", "Conseil couleurs et matériaux, par pièce", "Nuancier, références peintures et revêtements, harmonie avec l'existant.", "U", 130, 20, 90, 3, 1.5, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-DEC-104", "Plan d'aménagement 2D, par pièce", "Implantation du mobilier coté, circulations et variantes.", "U", 353.5, 20, 260, 2, 4, ["architecte-interieur", "decorateur-interieur"]],
    ["CE-DEC-105", "Perspective 3D photoréaliste, par vue", "Modélisation et rendu d'une vue intérieure avec mobilier et éclairage.", "U", 362, 20, 260, 8, 4, ["architecte-interieur", "decorateur-interieur", "architecte"]],
    ["CE-DEC-106", "Liste d'achats mobilier et déco chiffrée, par pièce", "Sélection de produits avec liens, quantités et budget. Commandes non comprises.", "U", 205, 20, 150, 2, 2.5, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-DEC-107", "Projet de décoration complet, au m²", "Planche, plan, 3D, couleurs et liste d'achats pour les pièces concernées.", "m²", 41, 20, 30, 0.5, 0.5, ["decorateur-interieur", "architecte-interieur"]],
    ["CE-DEC-108", "Conception d'architecture intérieure, au m²", "Redistribution, plans techniques, choix des matériaux et 3D. Suivi de chantier non compris.", "m²", 86.5, 20, 63, 1, 0.9, ["architecte-interieur"]],
    ["CE-DEC-109", "Plans techniques intérieurs, par pièce", "Plans électricité, plomberie, calepinage et faux plafonds pour les entreprises.", "U", 479.5, 20, 350, 5, 5, ["architecte-interieur"]],
    ["CE-DEC-110", "Conception de cuisine sur mesure", "Plans, élévations, implantation des équipements et choix des finitions.", "forfait", 741, 20, 560, 10, 8, ["architecte-interieur", "decorateur-interieur"]],
    ["CE-DEC-111", "Conception de salle de bains", "Plan, élévations, calepinage faïence et choix des équipements.", "forfait", 650, 20, 490, 10, 7, ["architecte-interieur", "decorateur-interieur"]],
    ["CE-DEC-112", "Dessin de mobilier sur mesure, par meuble", "Plans et élévations cotés, matériaux et quincaillerie pour l'agenceur.", "U", 461.5, 20, 350, 5, 5, ["architecte-interieur", "decorateur-interieur"]],
    ["CE-DEC-113", "Étude d'éclairage intérieur, par pièce", "Scénarios d'éclairage, implantation des points lumineux et sélection des luminaires.", "U", 290, 20, 210, 5, 3, ["architecte-interieur", "decorateur-interieur"]],
    ["CE-DEC-114", "Aménagement de bureaux ou de commerce, au m²", "Space planning, image de marque, plans et 3D. Dossier ERP compté à part.", "m²", 62, 20, 45, 1, 0.6, ["architecte-interieur", "architecte"]],
    ["CE-DEC-115", "Home staging, logement ≤ 80 m²", "Désencombrement, mise en scène et accessoires prêtés pour photos de vente.", "forfait", 656.5, 20, 480, 25, 8, ["decorateur-interieur"]],
    ["CE-DEC-116", "Coaching déco à distance", "Échange en visio, analyse des photos et recommandations écrites.", "forfait", 245.5, 20, 180, 2, 3, ["decorateur-interieur"]],
    ["CE-DEC-117", "Visite de suivi de chantier décoration", "Vérification des mises en œuvre et des finitions, points avec les artisans.", "U", 196, 20, 140, 5, 2, ["architecte-interieur", "decorateur-interieur"]],
  ],
  "Géomètre-topographe": [
    ["CE-GEO-101", "Bornage amiable contradictoire", "Recherche des titres, convocation des riverains, levé, pose de bornes et procès-verbal.", "forfait", 1118, 20, 800, 60, 10, ["geometre-topographe"]],
    ["CE-GEO-102", "Pose de borne supplémentaire", "Implantation et pose d'une borne en limite de propriété.", "U", 70, 20, 35, 15, 0.5, ["geometre-topographe"]],
    ["CE-GEO-103", "Division parcellaire en deux lots", "Levé, projet de division, document d'arpentage et bornage des nouvelles limites.", "forfait", 1820, 20, 1360, 40, 16, ["geometre-topographe"]],
    ["CE-GEO-104", "Document modificatif du parcellaire cadastral", "Établissement et dépôt du document d'arpentage au service du cadastre.", "forfait", 637, 20, 480, 10, 6, ["geometre-topographe"]],
    ["CE-GEO-105", "Implantation de bâtiment", "Implantation des axes et angles, repères altimétriques et procès-verbal.", "forfait", 559, 20, 400, 30, 5, ["geometre-topographe", "conducteur-travaux"]],
    ["CE-GEO-106", "Plan de masse coté pour permis de construire", "Plan de masse avec cotes, altitudes et raccordements, à partir d'un levé existant.", "forfait", 396.5, 20, 300, 5, 4, ["geometre-topographe", "architecte", "maitre-oeuvre"]],
    ["CE-GEO-107", "Certificat de mesurage de surface de plancher", "Mesurage et attestation de la surface de plancher et d'emprise au sol.", "forfait", 296.5, 20, 225, 3, 3, ["geometre-topographe", "architecte"]],
    ["CE-GEO-108", "État descriptif de division de copropriété", "Plans des lots, calcul des tantièmes et état descriptif.", "forfait", 2704, 20, 2040, 40, 24, ["geometre-topographe"]],
    ["CE-GEO-109", "Contrôle altimétrique et récolement de fondations", "Vérification de l'implantation et des niveaux, rapport d'écarts.", "forfait", 310.5, 20, 225, 5, 3, ["geometre-topographe", "conducteur-travaux"]],
    ["CE-GEO-110", "Détection et géoréférencement de réseaux enterrés", "Détection électromagnétique et radar, marquage au sol et plan géoréférencé.", "forfait", 494, 20, 320, 60, 4, ["geometre-topographe", "bureau-etudes"]],
    ["CE-GEO-111", "Calcul de cubatures de terrassement", "Calcul des déblais et remblais à partir du levé et du projet.", "forfait", 422.5, 20, 320, 5, 4, ["geometre-topographe", "economiste-construction", "bureau-etudes"]],
  ],
  "Études techniques": [
    ["CE-BET-101", "Étude de sol G1 (sous-traitée)", "Mission géotechnique préalable par bureau spécialisé, coordination et transmission du rapport.", "forfait", 1092, 20, 160, 750, 2, ["bureau-etudes", "architecte", "maitre-oeuvre"]],
    ["CE-BET-102", "Étude de sol G2 AVP (sous-traitée)", "Sondages, essais et avant-projet géotechnique de fondations par bureau spécialisé.", "forfait", 1752, 20, 160, 1300, 2, ["bureau-etudes", "architecte", "maitre-oeuvre"]],
    ["CE-BET-103", "Note de calcul pour ouverture de mur porteur", "Descente de charges, dimensionnement de la poutre et des appuis, plan de principe.", "U", 466, 20, 340, 5, 4, ["bureau-etudes"]],
    ["CE-BET-104", "Note de calcul de poutre ou de plancher", "Vérification ou dimensionnement d'un élément porteur avec plan de principe.", "U", 351, 20, 255, 5, 3, ["bureau-etudes"]],
    ["CE-BET-105", "Plans de coffrage et ferraillage, par niveau", "Plans d'exécution béton armé et nomenclatures d'aciers.", "U", 1261, 20, 960, 10, 12, ["bureau-etudes"]],
    ["CE-BET-106", "Diagnostic structurel de fissures", "Visite, relevé et classement des fissures, causes probables et préconisations.", "forfait", 721.5, 20, 540, 15, 6, ["bureau-etudes", "economiste-construction"]],
    ["CE-BET-107", "Étude thermique RE2020, maison individuelle", "Modélisation, indicateurs énergie et carbone, attestation de dépôt du permis.", "forfait", 1092, 20, 800, 40, 10, ["bureau-etudes"]],
    ["CE-BET-108", "Attestation RE2020 à l'achèvement des travaux", "Vérification des pièces et de la perméabilité à l'air, attestation finale.", "forfait", 337.5, 20, 240, 10, 3, ["bureau-etudes"]],
    ["CE-BET-109", "Étude thermique de bâtiment existant", "Calcul réglementaire global ou par élément, scénarios d'amélioration.", "forfait", 819, 20, 600, 30, 7.5, ["bureau-etudes"]],
    ["CE-BET-110", "Calcul des déperditions et dimensionnement du chauffage", "Bilan pièce par pièce et puissance des émetteurs et du générateur.", "forfait", 429, 20, 320, 10, 4, ["bureau-etudes"]],
    ["CE-BET-111", "Étude fluides chauffage, ventilation et plomberie, au m² SHAB", "Dimensionnement, schémas de principe et plans de réseaux.", "m²", 17, 20, 12.75, 0.3, 0.15, ["bureau-etudes"]],
    ["CE-BET-112", "Test d'étanchéité à l'air du bâtiment", "Mesure par porte soufflante, recherche de fuites et rapport.", "forfait", 331.5, 20, 240, 15, 3, ["bureau-etudes"]],
    ["CE-BET-113", "Étude de filière d'assainissement non collectif", "Sondages à la tarière, test de perméabilité et choix de la filière.", "forfait", 598, 20, 400, 60, 5, ["bureau-etudes", "geometre-topographe"]],
    ["CE-BET-114", "Étude de gestion des eaux pluviales à la parcelle", "Calcul des volumes, dimensionnement de l'infiltration ou de la rétention.", "forfait", 559, 20, 400, 30, 5, ["bureau-etudes", "geometre-topographe"]],
  ],
  "Coordination SPS": [
    ["CE-SPS-101", "Coordination SPS niveau 3, petite opération", "Mission complète conception et réalisation, registre, visites et DIUO simplifié.", "forfait", 1001, 20, 750, 20, 10, ["coordinateur-sps"]],
    ["CE-SPS-102", "Plan général de coordination (PGC)", "Rédaction du PGC, mesures de coordination et installations communes.", "forfait", 1059.5, 20, 800, 15, 10, ["coordinateur-sps"]],
    ["CE-SPS-103", "PGC simplifié en phase conception", "Analyse des risques du projet et PGC simplifié pour la consultation.", "forfait", 637, 20, 480, 10, 6, ["coordinateur-sps"]],
    ["CE-SPS-104", "Ouverture et tenue du registre-journal de coordination", "Ouverture du registre et enregistrement des observations sur la durée du chantier.", "forfait", 229.5, 20, 150, 20, 2, ["coordinateur-sps"]],
    ["CE-SPS-105", "Déclaration préalable de chantier", "Établissement et envoi aux organismes compétents, affichage sur chantier.", "forfait", 97, 20, 70, 2, 1, ["coordinateur-sps"]],
    ["CE-SPS-106", "Inspection commune préalable, par entreprise", "Visite des lieux avec l'entreprise avant intervention, consignes et risques.", "U", 154.5, 20, 112.5, 2, 1.5, ["coordinateur-sps"]],
    ["CE-SPS-107", "Analyse d'un PPSPS d'entreprise", "Contrôle de cohérence avec le PGC et observations écrites.", "U", 102.5, 20, 75, 1, 1, ["coordinateur-sps"]],
    ["CE-SPS-108", "Visite de coordination avec compte rendu", "Visite de chantier, observations au registre et diffusion.", "U", 257, 20, 187.5, 3, 2.5, ["coordinateur-sps"]],
    ["CE-SPS-109", "Coordination SPS en phase réalisation, forfait mensuel", "Visites hebdomadaires, registre, analyse des PPSPS et réunions.", "forfait", 1196, 20, 900, 20, 12, ["coordinateur-sps"]],
    ["CE-SPS-110", "Dossier d'interventions ultérieures sur l'ouvrage (DIUO)", "Constitution du DIUO et remise au maître d'ouvrage à la réception.", "forfait", 799.5, 20, 600, 15, 8, ["coordinateur-sps"]],
    ["CE-SPS-111", "Mise à jour d'un DIUO existant", "Intégration des nouveaux ouvrages et modes d'intervention.", "forfait", 308, 20, 225, 3, 3, ["coordinateur-sps"]],
    ["CE-SPS-112", "Plan de prévention pour intervention en site occupé", "Analyse des risques d'interférence et mesures de prévention.", "forfait", 396.5, 20, 300, 5, 4, ["coordinateur-sps", "conducteur-travaux"]],
    ["CE-SPS-113", "Audit sécurité inopiné de chantier", "Visite non programmée, check-list et rapport d'écarts.", "U", 206.5, 20, 150, 3, 2, ["coordinateur-sps", "conducteur-travaux"]],
    ["CE-SPS-114", "Plan d'installation de chantier et des moyens communs", "Implantation des cantonnements, accès, levage et stockages.", "forfait", 299, 20, 225, 5, 3, ["coordinateur-sps", "conducteur-travaux", "maitre-oeuvre"]],
  ],
});
