import { defineCatalog } from "./define";

export const CATALOG_COUVERTURE = defineCatalog("couverture", {
  "Installation et sécurité": [
    ["CV-INS-101", "Frais de déplacement chantier zone ≤ 30 km", "Aller-retour du véhicule équipé et temps de trajet de l'équipe, par jour d'intervention.", "forfait", 82, 10, 45, 18, 1],
    ["CV-INS-102", "Échafaudage de façade, montage, démontage et location 2 semaines", "Échafaudage de pied avec planchers, garde-corps et filet. Au m² de façade desservie. Prolongation facturée à part.", "m²", 22.5, 10, 11.25, 6, 0.25],
    ["CV-INS-103", "Nacelle élévatrice 14 m, location journée avec transport", "Nacelle articulée ou ciseaux livrée sur site, carburant compris. Autorisation de voirie non comprise.", "jour", 419, 10, 45, 290, 1],
    ["CV-INS-104", "Garde-corps provisoire de rive de toit (protection collective)", "Fourniture, pose et dépose de garde-corps fixés en égout ou en rive pendant la durée du chantier.", "ml", 18, 10, 9, 5, 0.2],
    ["CV-INS-105", "Monte-matériaux électrique, installation et location 1 semaine", "Monte-tuiles posé sur la façade, mise en service et repli. Alimentation électrique fournie par le client.", "forfait", 410, 10, 135, 180, 3],
    ["CV-INS-106", "Benne 8 m³ déchets de couverture (tuiles, liteaux, écran)", "Location, rotation et traitement en centre agréé. Déchets amiantés exclus. Chargement non compris.", "U", 516, 10, 22.5, 390, 0.5],
    ["CV-INS-107", "Main d'œuvre en régie, couvreur qualifié", "Heure de travail effectif sur toiture pour travaux non prévus au devis. Fournitures facturées en sus.", "h", 62.5, 10, 48, 0, 1],
    ["CV-INS-108", "Forfait petite intervention en toiture (≤ 2 h sur place)", "Déplacement, 2 h de main d'œuvre et petites fournitures courantes. Au-delà, régie horaire.", "forfait", 158, 10, 96, 25, 2],
    ["CV-INS-109", "Majoration intervention urgente soir, week-end ou jour férié", "Supplément appliqué à l'intervention réalisée hors heures ouvrées, en sus du déplacement et du travail.", "forfait", 84, 10, 60, 0, 1],
    ["CV-INS-110", "Bâchage d'urgence de toiture jusqu'à 20 m²", "Pose d'une bâche armée lestée et fixée pour mise hors d'eau provisoire. Réparation définitive non comprise.", "forfait", 284, 10, 150, 60, 3],
    ["CV-INS-111", "Diagnostic de toiture avec rapport photo", "Visite, inspection de la couverture et de la zinguerie, rapport photo et préconisations chiffrées.", "forfait", 107, 20, 82.5, 0, 1.5],
  ],
  "Dépose et préparation": [
    ["CV-DEP-101", "Dépose de couverture en tuiles avec liteaux, descente et tri", "Dépose soignée, descente des matériaux et tri pour évacuation. Benne non comprise. Charpente conservée.", "m²", 22, 10, 15.75, 1, 0.35, ["couvreur", "couvreur-zingueur"]],
    ["CV-DEP-102", "Dépose de couverture en ardoises avec crochets ou clous", "Dépose des ardoises et des fixations, tri des ardoises réemployables. Voliges conservées, benne non comprise.", "m²", 27.5, 10, 20.25, 1, 0.45, ["couvreur", "couvreur-zingueur"]],
    ["CV-DEP-103", "Dépose de plaques ondulées fibres-ciment sans amiante", "Dépose et descente de plaques sans amiante (repérage avant travaux fourni par le client). Évacuation non comprise.", "m²", 16, 10, 11.25, 1, 0.25, ["couvreur", "couvreur-zingueur"]],
    ["CV-DEP-104", "Dépose de gouttière et descente existantes", "Dépose des crochets, gouttières et descentes, descente au sol et tri. Évacuation en déchetterie comprise.", "ml", 10, 10, 6.75, 1, 0.15, ["couvreur", "couvreur-zingueur", "zingueur", "poseur-gouttieres"]],
    ["CV-DEP-105", "Dépose d'ouvrage de zinguerie (chéneau, habillage, noue)", "Dépose soignée et descente des éléments de zinguerie, tri du métal pour recyclage.", "ml", 15.5, 10, 11.25, 0.5, 0.25, ["couvreur", "couvreur-zingueur", "zingueur"]],
  ],
  "Support et isolation": [
    ["CV-SUP-101", "Écran sous-toiture HPV fourni posé, avec contre-liteaux", "Écran hautement perméable à la vapeur, recouvrements adhésifs et contre-lattage 27 mm. Liteaux non compris.", "m²", 18.5, 10, 8.1, 6, 0.18, ["couvreur", "couvreur-zingueur"]],
    ["CV-SUP-102", "Liteaux sapin traité classe 2, 27 × 38, fournis posés", "Liteaunage au pureau de la tuile ou de l'ardoise, fixation inox ou galva. Écran et contre-liteaux non compris.", "m²", 13.5, 10, 6.75, 3.5, 0.15, ["couvreur", "couvreur-zingueur"]],
    ["CV-SUP-103", "Voligeage jointif sapin 18 mm pour ardoise ou zinc", "Volige rabotée traitée clouée sur chevrons, réglage du plan. Écran ou natte de ventilation non compris.", "m²", 39, 10, 18, 12, 0.4, ["couvreur", "couvreur-zingueur", "zingueur"]],
    ["CV-SUP-104", "Remplacement ponctuel de chevron 63 × 75 mm", "Dépose locale de la couverture, chevron neuf traité doublé ou remplacé. Repose couverture non comprise.", "ml", 48, 10, 28.8, 8, 0.6, ["couvreur", "couvreur-zingueur"]],
    ["CV-SUP-105", "Isolation sarking panneaux PIR 140 mm, R ≥ 6", "Pare-vapeur, panneaux rigides à joints scotchés, contre-liteaux. Résistance thermique conforme au taux réduit.", "m²", 82, 5.5, 25, 38, 0.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-SUP-106", "Isolation sarking fibre de bois en deux couches, R ≥ 6", "Pare-vapeur, panneaux fibre de bois rigides croisés, pare-pluie intégré et contre-liteaux. Couverture non comprise.", "m²", 130, 5.5, 37.5, 62, 0.75, ["couvreur", "couvreur-zingueur"]],
  ],
  "Couverture tuiles": [
    ["CV-TUI-101", "Couverture tuiles terre cuite petit moule (20-22/m²) fournies posées", "Pose sur liteaux existants, tuiles de rive et faîtage non comprises. Coupe et façon au droit des pénétrations.", "m²", 83, 10, 36, 28, 0.8, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-102", "Couverture tuiles béton à emboîtement fournies posées", "Tuiles béton teintées 10/m², pose sur liteaux existants, fixation selon zone de vent. Accessoires non compris.", "m²", 50.5, 10, 24.75, 14, 0.55, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-103", "Couverture tuiles canal sur plaques supports ondulées", "Plaques sous-tuile fixées, tuiles de courant collées ou crochetées et tuiles de couvert. Faîtage et rives en sus.", "m²", 114, 10, 49.5, 38, 1.1, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-104", "Couverture tuiles canal avec réemploi des tuiles de couvert", "Tuiles neuves en courant, tuiles anciennes triées réemployées en couvert. Plaques supports non comprises.", "m²", 71, 10, 40.5, 14, 0.9, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-105", "Couverture tuiles plates terre cuite 17 × 27 (60-70/m²)", "Pose au clou ou au crochet sur liteaux, double recouvrement. Accessoires et liteaux non compris.", "m²", 184, 10, 76.8, 65, 1.6, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-106", "Remaniement de couverture tuiles (dépose, tri, repose)", "Dépose, tri et repose des tuiles saines, remplacement jusqu'à 15 % par des tuiles neuves fournies.", "m²", 43, 10, 27, 6, 0.6, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-107", "Remplacement de tuiles cassées, jusqu'à 10 tuiles", "Fourniture de tuiles équivalentes, dépose des tuiles cassées et recalage. Accès nacelle non compris.", "forfait", 133, 10, 67.5, 35, 1.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-108", "Remplacement de tuile à l'unité (au-delà du forfait)", "Tuile mécanique ou canal équivalente fournie, remplacement et recalage des tuiles voisines.", "U", 19, 10, 11.25, 3.5, 0.25, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-109", "Tuile chatière de ventilation fournie posée", "Chatière assortie au modèle de tuile, avec grille anti-insectes, pour ventilation de la sous-face.", "U", 52.5, 10, 22.5, 18, 0.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-TUI-110", "Révision générale de toiture tuiles (recalage, contrôle)", "Recalage des tuiles glissées, contrôle des faîtages et rives, remplacement de 5 tuiles maximum.", "m²", 8, 10, 5.4, 0.8, 0.12, ["couvreur", "couvreur-zingueur"]],
  ],
  "Couverture ardoise et plaques": [
    ["CV-ARD-101", "Couverture ardoise naturelle 32 × 22 au crochet inox", "Ardoise naturelle 1er choix posée au crochet sur liteaux, double recouvrement. Accessoires et liteaux en sus.", "m²", 169, 10, 75, 55, 1.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-102", "Couverture ardoise naturelle 40 × 24 au clou cuivre", "Pose clouée sur voligeage existant, recouvrement selon pente. Faîtage, rives et noues non compris.", "m²", 191, 10, 85, 62, 1.7, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-103", "Couverture ardoise fibres-ciment 40 × 24 au crochet", "Ardoise synthétique sans amiante sur liteaux, crochets inox. Accessoires et liteaux non compris.", "m²", 89.5, 10, 45, 24, 1, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-104", "Remplacement d'ardoises cassées, jusqu'à 10 ardoises", "Ardoises équivalentes fournies, pose au crochet inox ou au tasseau cuivre. Accès nacelle non compris.", "forfait", 136, 10, 75, 30, 1.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-105", "Couverture plaques fibres-ciment ondulées sans amiante", "Plaques fixées par crochets ou tire-fonds avec rondelles d'étanchéité, sur pannes existantes. Faîtières en sus.", "m²", 44, 10, 18, 16, 0.4, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-106", "Remplacement de plaque fibres-ciment ondulée à l'unité", "Dépose de la plaque abîmée (non amiantée), fourniture et fixation d'une plaque neuve équivalente.", "U", 85.5, 10, 33.75, 32, 0.75, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-107", "Plaque translucide ondulée polycarbonate en remplacement", "Plaque éclairante au profil de la couverture existante, fixations et closoirs compris.", "U", 65.5, 10, 22.5, 28, 0.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-ARD-108", "Couverture bac acier simple peau 63/100 prélaqué", "Bacs nervurés fixés sur pannes avec vis à rondelles, closoirs. Faîtage et rives en sus. Abri, garage ou annexe.", "m²", 40, 10, 15.75, 15, 0.35, ["couvreur", "couvreur-zingueur"]],
  ],
  "Faîtages, rives et raccords": [
    ["CV-FAI-101", "Faîtage tuiles scellé au mortier bâtard", "Faîtières posées à bain de mortier avec embarrures, about et fronton. Dépose de l'ancien faîtage non comprise.", "ml", 48, 10, 27, 10, 0.6, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-102", "Faîtage à sec sur closoir ventilé et support de faîtage", "Closoir souple ventilé, rail support et faîtières vissées. Solution sans mortier, ventilation de la sous-face.", "ml", 47, 10, 20.25, 16, 0.45, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-103", "Réfection de faîtage scellé existant (dépiquetage, rescellement)", "Dépose des faîtières, piquage des anciens solins, repose au mortier neuf. 10 % de faîtières neuves incluses.", "ml", 49, 10, 31.5, 6, 0.7, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-104", "Arêtier en tuiles faîtières scellées ou à sec", "Coupe des tuiles en arêtier, pose des arêtières sur closoir ou mortier, abouts compris.", "ml", 59, 10, 31.5, 14, 0.7, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-105", "Rives à rabat terre cuite fournies posées", "Tuiles de rive assorties fixées mécaniquement, about de rive compris.", "ml", 38.5, 10, 15.75, 14, 0.35, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-106", "Rive scellée au mortier avec tuiles de couvert", "Rive traditionnelle maçonnée pour tuile canal, mortier teinté. Planche de rive non comprise.", "ml", 33, 10, 20.25, 5, 0.45, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-107", "Bande de rive aluminium laqué façonnée", "Habillage de rive en alu laqué teinte au choix, fixation sur chevron de rive. Planche de rive non comprise.", "ml", 33, 10, 13.5, 12, 0.3, ["couvreur", "couvreur-zingueur", "zingueur"]],
    ["CV-FAI-108", "Noue zinc ou alu façonnée sur volige", "Fond de noue en tôle façonnée avec relevés, coupe des tuiles ou ardoises en biais comprise.", "ml", 80.5, 10, 40, 22, 0.8, ["couvreur", "couvreur-zingueur", "zingueur"]],
    ["CV-FAI-109", "Closoir d'égout anti-oiseaux (peigne ou grille)", "Peigne ou grille PVC fixé en égout pour ventilation et protection contre nuisibles.", "ml", 10, 10, 4.5, 3, 0.1, ["couvreur", "couvreur-zingueur", "nettoyage-toiture"]],
    ["CV-FAI-110", "Solin au mortier contre maçonnerie", "Solin bâtard en relevé de couverture contre mur ou souche, dégarnissage de l'ancien solin compris.", "ml", 30, 10, 20.25, 3, 0.45, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-111", "Solin bande zinc engravée avec mastic", "Bande de solin engravée dans la maçonnerie, joint mastic polyuréthane. Abergement non compris.", "ml", 57, 10, 30, 14, 0.6, ["couvreur", "couvreur-zingueur", "zingueur"]],
    ["CV-FAI-112", "Abergement complet de souche de cheminée en zinc", "Bavette, côtés à gradins, back et solins engravés pour souche jusqu'à 60 × 60 cm.", "U", 442, 10, 250, 90, 5, ["couvreur", "couvreur-zingueur", "zingueur"]],
    ["CV-FAI-113", "Chapeau de cheminée terre cuite ou inox fourni posé", "Dépose de l'ancien chapeau, pose et scellement d'un chapeau ou d'une mitre adapté au conduit.", "U", 185, 10, 67.5, 75, 1.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-114", "Sortie de toit ventilation avec tuile à douille", "Tuile ou ardoise à douille, manchon isolé et raccord à la gaine existante. Gaine non comprise.", "U", 169, 10, 75, 55, 1.5, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-115", "Barre pare-neige sur crochets galvanisés", "Barre arrêt de neige fixée sur crochets vissés dans la charpente, tous les 60 cm environ.", "ml", 52, 10, 18, 22, 0.4, ["couvreur", "couvreur-zingueur"]],
    ["CV-FAI-116", "Crochet de sécurité permanent pour entretien de toiture", "Point d'ancrage fixé à la charpente pour l'intervention en sécurité, vérification à la pose.", "U", 94, 10, 37.5, 35, 0.75, ["couvreur", "couvreur-zingueur", "poseur-fenetres-toit"]],
  ],
  "Zinguerie": [
    ["CV-ZIN-101", "Couverture zinc à joint debout prépatiné", "Bandes de zinc 0,65 mm à joint debout, pattes fixes et coulissantes. Voligeage et natte non compris.", "m²", 177, 10, 88, 48, 1.6, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-102", "Couverture zinc à tasseaux sur voligeage", "Bandes de zinc naturel entre tasseaux bois avec couvre-joints. Voligeage non compris.", "m²", 186, 10, 99, 44, 1.8, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-103", "Chéneau zinc encaissé façonné, développé 50 cm", "Chéneau sur fond bois, dilatations, talons et moignons soudés. Fond de chéneau bois non compris.", "ml", 135, 10, 66, 38, 1.2, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-104", "Habillage de bandeau ou planche de rive en zinc", "Façonnage et pose sur tasseaux ou pattes, recouvrements et angles soudés.", "ml", 63.5, 10, 33, 16, 0.6, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-105", "Bavette d'appui ou habillage de tableau en zinc", "Tôle façonnée avec goutte d'eau, fixation et étanchéité au mastic.", "ml", 51.5, 10, 27.5, 12, 0.5, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-106", "Couvertine zinc ou alu laqué sur acrotère ou mur", "Couvertine façonnée sur pattes, éclisses de jonction et pente vers l'intérieur.", "ml", 56, 10, 25, 18, 0.5, ["zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-ZIN-107", "Bande d'égout avec larmier, zinc ou alu", "Bande d'égout fixée sous l'écran, rejet de l'eau dans la gouttière.", "ml", 21, 10, 9, 7, 0.2, ["zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-ZIN-108", "Brisis ou membron zinc façonné", "Façonnage et pose du membron de brisis avec agrafures et recouvrements soudés.", "ml", 86, 10, 44, 22, 0.8, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-109", "Habillage de jouées de lucarne en zinc", "Jouées et fronton de lucarne en zinc à joint debout ou à tasseaux. Voligeage non compris.", "m²", 216, 10, 121, 45, 2.2, ["zingueur", "couvreur-zingueur"]],
    ["CV-ZIN-110", "Réparation ponctuelle de zinguerie (soudure, pièce rapportée)", "Décapage, soudure à l'étain ou pièce de zinc rapportée sur fuite localisée, jusqu'à 2 h.", "forfait", 176, 10, 110, 25, 2, ["zingueur", "couvreur-zingueur", "poseur-gouttieres"]],
  ],
  "Gouttières et descentes": [
    ["CV-GOU-101", "Gouttière PVC demi-ronde développé 25, fournie posée", "Gouttière, crochets, talons, naissance et joints. Pente réglée vers la descente. Descente en sus.", "ml", 32, 10, 15.75, 9, 0.35, ["poseur-gouttieres", "couvreur", "couvreur-zingueur"]],
    ["CV-GOU-102", "Gouttière PVC demi-ronde développé 33, fournie posée", "Gouttière grande section pour versant important, crochets renforcés, accessoires compris.", "ml", 39, 10, 18, 12, 0.4, ["poseur-gouttieres", "couvreur", "couvreur-zingueur"]],
    ["CV-GOU-103", "Gouttière zinc demi-ronde développé 25, fournie posée", "Zinc naturel 0,65 mm, crochets galvanisés, raccords soudés, naissance comprise. Descente en sus.", "ml", 67.5, 10, 30, 22, 0.6, ["poseur-gouttieres", "zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-GOU-104", "Gouttière zinc demi-ronde développé 33, fournie posée", "Zinc naturel, grande section, crochets à bande, dilatations et soudures comprises.", "ml", 78.5, 10, 32.5, 28, 0.65, ["poseur-gouttieres", "zingueur", "couvreur-zingueur"]],
    ["CV-GOU-105", "Gouttière aluminium laqué sans joint, profilée sur place", "Profilage en continu sur chantier, teinte au choix, crochets ou pattes alu, naissance comprise.", "ml", 49.5, 10, 20, 18, 0.4, ["poseur-gouttieres"]],
    ["CV-GOU-106", "Gouttière zinc moulurée type corniche (havraise, nantaise)", "Gouttière pendante ou corniche à moulure, fixations adaptées, soudures et naissance comprises.", "ml", 121, 10, 55, 38, 1, ["poseur-gouttieres", "zingueur", "couvreur-zingueur"]],
    ["CV-GOU-107", "Descente eaux pluviales PVC Ø 80, fournie posée", "Tube, colliers, coudes et raccord au regard ou dauphin existant.", "ml", 26.5, 10, 13.5, 7, 0.3, ["poseur-gouttieres", "couvreur", "couvreur-zingueur"]],
    ["CV-GOU-108", "Descente eaux pluviales zinc Ø 80, fournie posée", "Tuyau zinc, colliers à bracelets, coudes soudés, raccord au dauphin.", "ml", 49.5, 10, 20, 18, 0.4, ["poseur-gouttieres", "zingueur", "couvreur-zingueur"]],
    ["CV-GOU-109", "Descente eaux pluviales aluminium laqué Ø 80", "Descente teintée assortie à la gouttière alu, colliers et coudes compris.", "ml", 41, 10, 17.5, 14, 0.35, ["poseur-gouttieres"]],
    ["CV-GOU-110", "Dauphin fonte 1 m avec raccord au réseau", "Dauphin fonte scellé ou fixé par colliers, raccord sur regard existant. Terrassement non compris.", "U", 106, 10, 27, 55, 0.6, ["poseur-gouttieres", "zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-GOU-111", "Remplacement des crochets de gouttière et reprise de pente", "Dépose de la gouttière, crochets neufs posés à 50 cm, repose avec pente régulière.", "ml", 18.5, 10, 11.25, 3, 0.25, ["poseur-gouttieres", "zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-GOU-112", "Réparation de fuite sur gouttière (joint, manchon, soudure)", "Recherche du point de fuite, remplacement de joint ou manchon, ou soudure sur zinc.", "forfait", 82, 10, 48, 15, 1, ["poseur-gouttieres", "zingueur", "couvreur-zingueur", "couvreur"]],
    ["CV-GOU-113", "Grille pare-feuilles pour gouttière, fournie posée", "Grille clipsée sur la gouttière limitant l'encrassement par les feuilles et mousses.", "ml", 13.5, 10, 4.5, 6, 0.1, ["poseur-gouttieres", "nettoyage-toiture"]],
    ["CV-GOU-114", "Nettoyage et curage de gouttières", "Enlèvement des dépôts, rinçage, contrôle de l'écoulement et évacuation des déchets.", "ml", 5.5, 10, 3.6, 0.3, 0.08, ["poseur-gouttieres", "nettoyage-toiture", "couvreur", "couvreur-zingueur"]],
    ["CV-GOU-115", "Débouchage de descente eaux pluviales", "Débouchage mécanique ou au jet, contrôle de l'écoulement jusqu'au regard.", "U", 50.5, 10, 33.75, 5, 0.75, ["poseur-gouttieres", "nettoyage-toiture"]],
    ["CV-GOU-116", "Récupérateur d'eau de pluie 300 L raccordé sur descente", "Cuve hors sol avec collecteur filtrant posé sur la descente, robinet et socle compris.", "U", 182, 10, 45, 95, 1, ["poseur-gouttieres"]],
  ],
  "Fenêtres de toit": [
    ["CV-FDT-101", "Fenêtre de toit 55 × 78 en pose neuve avec raccord", "Création de la trémie, chevêtre, pose, raccord d'étanchéité et reprise de couverture. Habillage intérieur en sus.", "U", 819, 10, 330, 300, 6, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-102", "Fenêtre de toit 114 × 118 en pose neuve avec raccord", "Création de trémie et chevêtrage, fenêtre à rotation, raccord et reprise de couverture. Habillage en sus.", "U", 1228, 10, 385, 560, 7, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-103", "Fenêtre de toit électrique solaire 78 × 98, pose neuve", "Fenêtre à commande radio et capteur de pluie, trémie, raccord et reprise de couverture.", "U", 1606, 10, 385, 850, 7, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-104", "Remplacement de fenêtre de toit 78 × 98, même dimension", "Dépose de l'ancienne fenêtre, pose d'une fenêtre isolante Uw ≤ 1,5 et raccord neuf. Habillage conservé.", "U", 806, 5.5, 220, 400, 4, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-105", "Remplacement de fenêtre de toit 114 × 118, même dimension", "Dépose, fenêtre isolante Uw ≤ 1,5 et raccord neuf, reprise ponctuelle de couverture.", "U", 1076, 5.5, 247.5, 580, 4.5, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-106", "Châssis tabatière d'accès au toit 45 × 55", "Châssis métallique d'accès ou d'éclairement de comble non habité, raccord compris.", "U", 312, 10, 150, 90, 3, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-107", "Store occultant intérieur pour fenêtre de toit", "Store à coulisses latérales adapté à la référence de la fenêtre, pose sans perçage du vitrage.", "U", 146, 10, 27.5, 85, 0.5, ["poseur-fenetres-toit"]],
    ["CV-FDT-108", "Store pare-soleil extérieur pour fenêtre de toit", "Store toile extérieur à crochets limitant l'apport solaire, pose sur fenêtre existante.", "U", 159, 10, 27.5, 95, 0.5, ["poseur-fenetres-toit"]],
    ["CV-FDT-109", "Volet roulant extérieur solaire pour fenêtre de toit", "Volet à panneau photovoltaïque intégré et télécommande radio, pose sans raccordement électrique.", "U", 653, 10, 82.5, 420, 1.5, ["poseur-fenetres-toit"]],
    ["CV-FDT-110", "Kit de motorisation solaire pour fenêtre de toit existante", "Moteur à chaîne, panneau solaire et télécommande, programmation et essais.", "U", 448, 10, 55, 290, 1, ["poseur-fenetres-toit"]],
    ["CV-FDT-111", "Remplacement du raccord d'étanchéité de fenêtre de toit", "Dépose locale de la couverture, raccord neuf adapté au matériau et repose. Fenêtre conservée.", "U", 299, 10, 110, 120, 2, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-112", "Dépose de fenêtre de toit et rebouchage en couverture", "Dépose de la fenêtre, fermeture de la trémie par chevrons, écran, liteaux et tuiles assorties.", "U", 254, 10, 150, 45, 3, ["poseur-fenetres-toit", "couvreur", "couvreur-zingueur"]],
    ["CV-FDT-113", "Habillage intérieur de fenêtre de toit en plaque de plâtre", "Ébrasements en plaque de plâtre sur ossature, bandes et enduit prêts à peindre.", "U", 221, 10, 125, 45, 2.5, ["poseur-fenetres-toit"]],
    ["CV-FDT-114", "Entretien de fenêtre de toit (joints, charnières, réglage)", "Nettoyage, graissage, remplacement des joints et réglage de la fermeture.", "forfait", 91, 10, 55, 15, 1, ["poseur-fenetres-toit"]],
    ["CV-FDT-115", "Conduit de lumière tubulaire Ø 250 mm", "Dôme, raccord en couverture, conduit réfléchissant et diffuseur au plafond, jusqu'à 2 m.", "U", 624, 10, 220, 260, 4, ["poseur-fenetres-toit", "couvreur"]],
  ],
  "Entretien et nettoyage": [
    ["CV-NET-101", "Nettoyage de toiture à basse pression avec traitement anti-mousse", "Grattage des mousses, rinçage basse pression, application d'un anti-mousse. Protection des abords comprise.", "m²", 9.5, 10, 5.4, 1.5, 0.12, ["nettoyage-toiture", "couvreur", "couvreur-zingueur"]],
    ["CV-NET-102", "Traitement anti-mousse curatif par pulvérisation seule", "Pulvérisation sans rinçage, action progressive par la pluie. Pour mousses peu épaisses.", "m²", 4, 10, 1.8, 1.2, 0.04, ["nettoyage-toiture", "couvreur", "couvreur-zingueur"]],
    ["CV-NET-103", "Hydrofuge incolore de toiture en deux passes", "Application d'un hydrofuge en phase aqueuse sur support propre et sec, au pulvérisateur.", "m²", 7.5, 10, 2.7, 3, 0.06, ["nettoyage-toiture", "couvreur", "couvreur-zingueur"]],
    ["CV-NET-104", "Hydrofuge coloré de toiture (teinte tuile ou ardoise)", "Revêtement hydrofuge pigmenté redonnant la teinte, deux couches sur support nettoyé.", "m²", 12, 10, 3.6, 5.5, 0.08, ["nettoyage-toiture", "couvreur"]],
    ["CV-NET-105", "Nettoyage de couverture bac acier ou fibres-ciment sans amiante", "Nettoyage basse pression et anti-mousse. Plaques amiantées exclues (autre famille).", "m²", 6, 10, 3.6, 1, 0.08, ["nettoyage-toiture", "couvreur"]],
    ["CV-NET-106", "Peinture de couverture métallique ou fibres-ciment (résine)", "Primaire d'accrochage et résine de finition deux couches sur support nettoyé.", "m²", 16.5, 10, 6.75, 6, 0.15, ["nettoyage-toiture", "couvreur"]],
    ["CV-NET-107", "Nettoyage de chéneau encaissé et contrôle des évacuations", "Enlèvement des dépôts, rinçage et vérification des moignons et trop-pleins.", "ml", 9.5, 10, 6.75, 0.3, 0.15, ["nettoyage-toiture", "zingueur", "couvreur-zingueur"]],
    ["CV-NET-108", "Nettoyage de toiture-terrasse (désherbage, évacuations)", "Enlèvement des végétaux et dépôts, dégagement des évacuations. Étanchéité non reprise.", "m²", 5.5, 10, 3.6, 0.5, 0.08, ["nettoyage-toiture"]],
    ["CV-NET-109", "Dispositif anti-pigeons à pics inox sur rebord ou faîtage", "Bandes de pics collées ou vissées, nettoyage préalable des fientes compris.", "ml", 23.5, 10, 9, 9, 0.2, ["nettoyage-toiture", "couvreur"]],
    ["CV-NET-110", "Visite d'entretien annuelle de toiture et gouttières", "Contrôle couverture, curage gouttières, recalage de tuiles et compte rendu. Réparations en sus.", "forfait", 172, 10, 112.5, 20, 2.5, ["nettoyage-toiture", "couvreur", "couvreur-zingueur", "poseur-gouttieres"]],
  ],
  "Réparations et dépannage": [
    ["CV-REP-101", "Recherche de fuite en toiture avec compte rendu", "Inspection de la couverture, de la zinguerie et des raccords, localisation de l'infiltration.", "forfait", 143, 10, 100, 10, 2, ["couvreur", "couvreur-zingueur", "zingueur", "poseur-fenetres-toit"]],
    ["CV-REP-102", "Réparation de fuite localisée en couverture (≤ 2 m²)", "Dépose locale, remplacement des éléments défectueux, reprise d'écran ou de solin. Hors charpente.", "forfait", 246, 10, 144, 45, 3, ["couvreur", "couvreur-zingueur"]],
    ["CV-REP-103", "Mise en sécurité de toiture après tempête", "Dépose des éléments instables, recalage des tuiles déplacées et mise hors d'eau provisoire.", "forfait", 226, 10, 144, 30, 3, ["couvreur", "couvreur-zingueur", "zingueur"]],
  ],
});
