import { defineCatalog } from "./define";

export const CATALOG_ELECTRICITE = defineCatalog("electricite", {
  "Interventions et régie": [
    ["EL-INT-101", "Frais de déplacement zone ≤ 30 km", "Aller-retour véhicule équipé et temps de trajet du technicien, par intervention.", "forfait", 64.5, 10, 37.5, 12, 0.75],
    ["EL-INT-102", "Main d'œuvre en régie, électricien qualifié", "Heure de travail effectif pour travaux non prévus au devis. Fournitures facturées en sus.", "h", 67.5, 10, 50, 0, 1],
    ["EL-INT-103", "Main d'œuvre en régie, technicien spécialisé", "Heure de technicien (automatisme, réseau, sûreté, IRVE). Fournitures et logiciels facturés en sus.", "h", 83.5, 10, 62, 0, 1],
    ["EL-INT-104", "Forfait dépannage ≤ 1 h sur place, déplacement compris", "Diagnostic et remise en service simple, petites fournitures courantes incluses. Pièces spécifiques en sus.", "forfait", 138.5, 10, 87.5, 15, 1.75],
    ["EL-INT-105", "Majoration intervention urgente (soir, week-end, jour férié)", "Supplément d'astreinte appliqué au forfait dépannage ou à la régie, hors heures ouvrées.", "forfait", 126, 10, 90, 0, 1.5],
    ["EL-INT-106", "Mise en service, paramétrage et prise en main client", "Essais de fonctionnement, réglages finaux et explication d'usage à l'occupant. Remise des notices.", "forfait", 71.5, 10, 55, 0, 1],
    ["EL-INT-107", "Diagnostic de l'installation électrique existante avec rapport", "Contrôle visuel, mesures d'isolement et de terre, liste chiffrée des non-conformités. Hors travaux.", "forfait", 192, 20, 137.5, 10, 2.5, ["electricien", "electricien-industriel"]],
    ["EL-INT-108", "Recherche de panne électrique ou de défaut d'isolement", "Localisation du défaut circuit par circuit au mégohmmètre. Réparation chiffrée en sus si importante.", "forfait", 156, 10, 110, 10, 2, ["electricien", "electricien-industriel", "domoticien"]],
    ["EL-INT-109", "Constitution du dossier et visa de l'attestation Consuel", "Schémas, attestation de conformité et frais de visa. Visite de contrôle et levée de réserves non comprises.", "forfait", 299, 20, 75, 155, 1.5, ["electricien", "electricien-industriel", "installateur-irve"]],
    ["EL-INT-110", "Saignée et rebouchage en maçonnerie pour encastrement", "Saignée à la rainureuse, pose de gaine et rebouchage au plâtre. Peinture et enduit de finition exclus.", "ml", 28, 10, 20, 1.5, 0.4, ["electricien"]],
    ["EL-INT-111", "Goulotte PVC apparente avec câblage", "Goulotte 2 compartiments fixée, couvercle et accessoires d'angle. Appareillage compté à part.", "ml", 27.5, 10, 15, 6, 0.3, ["electricien", "electricien-courants-faibles", "electricien-industriel"]],
  ],
  "Rénovation et mise aux normes": [
    ["EL-REN-101", "Rénovation électrique complète studio ou T1 (≤ 35 m²)", "Tableau, circuits et appareillage neufs NF C 15-100 encastrés. Consuel, rebouchage peint et luminaires exclus.", "m²", 152, 10, 65, 52, 1.3, ["electricien"]],
    ["EL-REN-102", "Rénovation électrique complète appartement T3 (55-75 m²)", "Installation neuve complète NF C 15-100 encastrée, tableau 2 rangées. Consuel et finitions peinture exclus.", "m²", 123, 10, 52.5, 42, 1.05, ["electricien"]],
    ["EL-REN-103", "Rénovation électrique complète maison (90-130 m²)", "Installation neuve complète, tableau 3 rangées et terre. Combles et vide sanitaire accessibles. Finitions exclues.", "m²", 114, 10, 47.5, 40, 0.95, ["electricien"]],
    ["EL-REN-104", "Mise aux normes NF C 15-100 maison T4/T5 existante", "Tableau, DDR 30 mA, terre, liaisons, circuits spécialisés et points manquants. Saignées comprises, peinture exclue.", "forfait", 4940, 10, 2000, 1800, 40, ["electricien"]],
    ["EL-REN-105", "Mise en sécurité de l'installation (protections et terre)", "Tableau de protection en tête avec DDR 30 mA, prise de terre et suppression des parties nues sous tension.", "forfait", 702, 10, 300, 240, 6, ["electricien"]],
    ["EL-REN-106", "Dépose d'installation électrique ancienne", "Dépose des câbles, boîtes et appareillages hors service, tri et évacuation en déchetterie.", "m²", 9.5, 10, 6.75, 0.5, 0.15, ["electricien"]],
    ["EL-REN-107", "Câble R2V 3G2,5 tiré sous conduit ICTA encastré", "Fourniture et pose de conduit et câble pour création ou reprise de circuit. Saignées comptées à part.", "ml", 13, 10, 7.5, 2.4, 0.15, ["electricien"]],
  ],
  "Tableaux et protections": [
    ["EL-TAB-101", "Tableau électrique 1 rangée équipé (13 modules)", "Coffret, interrupteur différentiel 30 mA, disjoncteurs et peignes, repérage. Pour dépendance ou studio.", "U", 429, 10, 150, 180, 3, ["electricien", "electricien-industriel"]],
    ["EL-TAB-102", "Tableau électrique 3 rangées équipé, logement", "Coffret 39 modules, 3 interrupteurs différentiels, disjoncteurs, parafoudre en attente, repérage et schéma.", "U", 1131, 10, 350, 520, 7, ["electricien", "electricien-industriel"]],
    ["EL-TAB-103", "Remplacement tableau à fusibles par tableau 2 rangées équipé", "Dépose de l'ancien tableau, pose du neuf, reprise des départs existants et essais. Mise à la terre non comprise.", "U", 1079, 10, 400, 430, 8, ["electricien"]],
    ["EL-TAB-104", "Disjoncteur divisionnaire phase-neutre ajouté au tableau", "Disjoncteur 2 à 32 A raccordé sur peigne et repéré. Câblage du circuit en aval non compris.", "U", 41.5, 10, 20, 12, 0.4, ["electricien", "electricien-industriel", "installateur-irve"]],
    ["EL-TAB-105", "Interrupteur différentiel 40 A 30 mA type AC", "Fourniture et pose en tête de rangée, répartition des circuits et essai du bouton test.", "U", 97.5, 10, 30, 45, 0.6, ["electricien", "electricien-industriel"]],
    ["EL-TAB-106", "Interrupteur différentiel 40 A 30 mA type A", "Pour circuits plaque, lave-linge ou borne de recharge. Fourniture, pose, répartition et essais.", "U", 132.5, 10, 30, 72, 0.6, ["electricien", "electricien-industriel", "installateur-irve"]],
    ["EL-TAB-107", "Parafoudre type 2 avec protection associée", "Parafoudre modulaire et disjoncteur de déconnexion en tête de tableau, liaison à la barrette de terre.", "U", 208, 10, 50, 110, 1, ["electricien", "electricien-industriel", "electricien-courants-faibles"]],
    ["EL-TAB-108", "Contacteur heures creuses pour chauffe-eau", "Contacteur modulaire 20 A avec commande forcée, câblage du signal tarifaire.", "U", 78, 10, 30, 30, 0.6, ["electricien"]],
    ["EL-TAB-109", "Télérupteur ou minuterie modulaire", "Appareil modulaire raccordé, câblage des boutons-poussoirs existants non compris.", "U", 74, 10, 25, 32, 0.5, ["electricien", "electricien-industriel"]],
  ],
  "Terre et liaisons équipotentielles": [
    ["EL-TER-101", "Prise de terre par piquet cuivre 1,50 m avec regard", "Piquet, câble cuivre 25 mm², barrette de mesure et regard de visite. Mesure de la résistance incluse.", "U", 266.5, 10, 125, 80, 2.5, ["electricien", "electricien-industriel", "installateur-irve"]],
    ["EL-TER-102", "Boucle à fond de fouille cuivre nu 25 mm²", "Câble posé en fond de fouille avant coulage, remontée vers barrette de terre. Construction neuve.", "ml", 13.5, 20, 5, 5.5, 0.1, ["electricien"]],
    ["EL-TER-103", "Liaison équipotentielle principale (eau, gaz, chauffage)", "Conducteur 6 à 10 mm² et colliers sur canalisations métalliques au point d'entrée.", "U", 130, 10, 75, 25, 1.5, ["electricien", "electricien-industriel"]],
    ["EL-TER-104", "Liaison équipotentielle supplémentaire salle d'eau", "Raccordement des masses et éléments conducteurs de la salle d'eau, conducteur 2,5 mm².", "U", 117, 10, 75, 15, 1.5, ["electricien"]],
    ["EL-TER-105", "Mise à la terre de mât d'antenne ou de parabole", "Conducteur cuivre, collier sur mât et raccordement à la terre existante. Création de piquet exclue.", "U", 106.5, 10, 52, 30, 1, ["antenniste", "electricien"]],
  ],
  "Appareillage et éclairage intérieur": [
    ["EL-APP-101", "Prise 16 A en saillie ou sur goulotte, câble ≤ 8 m", "Prise avec terre en apparent, câble et protections. Pour pièces sans saignée possible.", "U", 63.5, 10, 35, 14, 0.7, ["electricien"]],
    ["EL-APP-102", "Double prise 16 A encastrée, câble ≤ 10 m", "Boîte d'encastrement, double prise et câblage sur circuit existant. Saignée comptée à part.", "U", 96, 10, 50, 24, 1, ["electricien"]],
    ["EL-APP-103", "Prise étanche extérieure IP55 avec protection", "Prise saillie à clapet, câble et protection différentielle existante. Terrasse ou façade.", "U", 106.5, 10, 60, 22, 1.2, ["electricien"]],
    ["EL-APP-104", "Interrupteur simple allumage encastré", "Interrupteur, boîte et câblage vers point lumineux existant. Saignée comptée à part.", "U", 65, 10, 40, 10, 0.8, ["electricien"]],
    ["EL-APP-105", "Commande va-et-vient (deux points de commande)", "Deux interrupteurs va-et-vient câblés vers le point lumineux. Saignées comptées à part.", "U", 130, 10, 80, 20, 1.6, ["electricien"]],
    ["EL-APP-106", "Point lumineux applique murale avec commande", "Boîte DCL murale, câblage et interrupteur. Luminaire non fourni.", "U", 101.5, 10, 60, 18, 1.2, ["electricien"]],
    ["EL-APP-107", "Spot LED encastré basse consommation (IP65 salle d'eau)", "Découpe du plafond, spot fixe 5-7 W et câblage en dérivation. Prix par spot.", "U", 70, 10, 30, 24, 0.6, ["electricien"]],
    ["EL-APP-108", "Ruban LED en profilé aluminium avec alimentation", "Profilé, diffuseur, ruban 24 V et alimentation raccordés, au mètre. Variateur non compris.", "ml", 57, 10, 20, 24, 0.4, ["electricien", "domoticien"]],
    ["EL-APP-109", "Détecteur de présence plafonnier", "Détecteur 360° encastré ou saillie, réglage temporisation et luminosité. Couloir, WC, garage.", "U", 110.5, 10, 40, 45, 0.8, ["electricien", "electricien-industriel"]],
    ["EL-APP-110", "Remplacement d'appareillage à l'identique", "Dépose et remplacement d'une prise, d'un interrupteur ou d'un DCL sur boîte existante.", "U", 28.5, 10, 15, 7, 0.3, ["electricien"]],
    ["EL-APP-111", "Détecteur autonome avertisseur de fumée (DAAF)", "Détecteur pile 10 ans fixé au plafond, test de fonctionnement.", "U", 43, 10, 15, 18, 0.3, ["electricien", "installateur-alarme-videosurveillance"]],
  ],
  "Circuits spécialisés": [
    ["EL-CIR-101", "Circuit plaque de cuisson 32 A en 6 mm², ≤ 15 m", "Disjoncteur 32 A, câble 3G6 sous conduit et sortie de câble. Différentiel type A compté à part.", "U", 260, 10, 125, 75, 2.5, ["electricien"]],
    ["EL-CIR-102", "Circuit spécialisé 20 A (four, lave-linge, lave-vaisselle), ≤ 15 m", "Disjoncteur 20 A, câble 3G2,5 sous conduit et prise 16 A dédiée. Différentiel type A compté à part.", "U", 184.5, 10, 100, 42, 2, ["electricien"]],
    ["EL-CIR-103", "Circuit chauffe-eau 20 A avec commande heures creuses", "Disjoncteur, câble 3G2,5 et sortie de câble. Contacteur HC compté à part.", "U", 195, 10, 110, 40, 2.2, ["electricien"]],
    ["EL-CIR-104", "Circuit climatisation ou pompe à chaleur 20 à 32 A", "Protection dédiée, câble jusqu'à l'unité extérieure ≤ 15 m et interrupteur de proximité.", "U", 273, 10, 125, 85, 2.5, ["electricien"]],
    ["EL-CIR-105", "Liaison enterrée U1000 R2V sous gaine TPC", "Câble 3G2,5 à 3G6 tiré en fourreau rouge. Tranchée non comprise.", "ml", 14.5, 10, 6, 5, 0.12, ["electricien", "electricien-industriel"]],
    ["EL-CIR-106", "Sous-tableau de dépendance avec liaison ≤ 25 m", "Coffret 1 rangée équipé dans garage ou atelier, liaison depuis le tableau principal. Tranchée exclue.", "forfait", 858, 10, 300, 360, 6, ["electricien"]],
  ],
  "Chauffage électrique et ventilation": [
    ["EL-CHA-101", "Dépose de radiateur électrique existant", "Déconnexion, dépose, isolation de la sortie de câble et évacuation en déchetterie.", "U", 24.5, 10, 18, 0, 0.4, ["electricien"]],
    ["EL-CHA-102", "Pose de radiateur fourni par le client", "Fixation murale, raccordement sur sortie de câble avec fil pilote et essai.", "U", 75.5, 10, 50, 8, 1, ["electricien"]],
    ["EL-CHA-103", "Radiateur à inertie 1000-1500 W fourni et posé", "Radiateur à inertie avec programmation intégrée, raccordement fil pilote sur sortie existante.", "U", 606, 10, 65, 420, 1.3, ["electricien"]],
    ["EL-CHA-104", "Panneau rayonnant 1000 W fourni et posé", "Radiateur rayonnant thermostat électronique, fixation et raccordement sur sortie existante.", "U", 260, 10, 50, 150, 1, ["electricien"]],
    ["EL-CHA-105", "Sèche-serviettes électrique 500-750 W fourni et posé", "Sèche-serviettes avec soufflerie, raccordement en volume 2 de la salle d'eau et fil pilote.", "U", 537.5, 10, 100, 330, 2, ["electricien"]],
    ["EL-CHA-106", "Circuit radiateur 20 A avec fil pilote", "Disjoncteur, câble 3G2,5 + fil pilote et sortie de câble murale.", "U", 139, 10, 75, 32, 1.5, ["electricien"]],
    ["EL-CHA-107", "Gestionnaire d'énergie fil pilote multizone", "Programmateur centralisé et délestage, raccordement des zones de chauffage. Éligible TVA réduite.", "U", 429, 5.5, 110, 220, 2, ["electricien", "domoticien"]],
    ["EL-CHA-108", "Thermostat d'ambiance programmable filaire", "Thermostat sur chaudière ou PAC, câblage et paramétrage des plages horaires.", "U", 224, 5.5, 82.5, 90, 1.5, ["electricien", "domoticien"]],
    ["EL-CHA-109", "Raccordement électrique de VMC (circuit et commande)", "Circuit dédié 2 A, sortie de câble en combles et commande grande vitesse cuisine.", "U", 175.5, 10, 100, 35, 2, ["electricien"]],
  ],
  "Éclairage extérieur": [
    ["EL-EXT-101", "Applique extérieure LED avec détecteur", "Applique IP44 fixée en façade, câblage et commande. Saignée en façade exclue.", "U", 149.5, 10, 60, 55, 1.2, ["electricien"]],
    ["EL-EXT-102", "Projecteur LED 30-50 W avec détecteur, en hauteur", "Fixation ≤ 4 m sur façade ou mât, raccordement et réglage. Nacelle non comprise.", "U", 169, 10, 70, 60, 1.4, ["electricien", "electricien-industriel"]],
    ["EL-EXT-103", "Borne LED de jardin sur platine, raccordée", "Borne IP65 hauteur 50-80 cm, plot béton et raccordement. Tranchée et câble enterré non compris.", "U", 221, 10, 75, 95, 1.5, ["electricien"]],
    ["EL-EXT-104", "Interrupteur crépusculaire ou horloge astronomique", "Appareil modulaire ou cellule en façade, câblage et programmation de la commande d'éclairage.", "U", 143, 10, 50, 60, 1, ["electricien", "electricien-industriel"]],
  ],
  "Électricité industrielle et tertiaire": [
    ["EL-IND-101", "Armoire de distribution tertiaire 4 rangées IP55 équipée", "Armoire métallique, interrupteur général, protections différentielles et disjoncteurs, repérage et schéma.", "U", 2431, 20, 720, 1150, 12, ["electricien-industriel"]],
    ["EL-IND-102", "Armoire de commande machine câblée et testée", "Étude de schéma, câblage contacteurs, relais et automate simple, essais en atelier. Programmation en sus.", "forfait", 4758, 20, 1860, 1800, 30, ["electricien-industriel"]],
    ["EL-IND-103", "Raccordement moteur triphasé ≤ 7,5 kW, câble ≤ 15 m", "Disjoncteur moteur, câble et presse-étoupes, contrôle du sens de rotation et de l'intensité.", "U", 535.5, 20, 232, 180, 4, ["electricien-industriel"]],
    ["EL-IND-104", "Variateur de fréquence ≤ 7,5 kW fourni posé", "Variateur en armoire ou coffret IP54, câblage blindé, paramétrage de base et essais.", "U", 1112.5, 20, 240, 650, 4, ["electricien-industriel"]],
    ["EL-IND-105", "Chemin de câbles dalle perforée 200 mm", "Chemin de câbles galvanisé, consoles et accessoires, fixé ≤ 4 m. Nacelle non comprise.", "ml", 52, 20, 22, 18, 0.4, ["electricien-industriel", "electricien-courants-faibles"]],
    ["EL-IND-106", "Câble U1000 R2V 5G6 posé sur chemin de câbles", "Déroulage, fixation et repérage aux extrémités. Raccordements comptés avec les équipements.", "ml", 19, 20, 6.6, 8, 0.12, ["electricien-industriel"]],
    ["EL-IND-107", "Prise industrielle 32 A mono ou triphasée", "Socle IP44 avec protection dédiée, câble ≤ 15 m sur chemin de câbles existant.", "U", 191, 20, 87, 60, 1.5, ["electricien-industriel"]],
    ["EL-IND-108", "Dalle LED 600 × 600 encastrée en faux plafond", "Dalle 36-40 W raccordée en dérivation, fixation dans ossature existante.", "U", 115.5, 20, 44, 45, 0.8, ["electricien-industriel", "electricien"]],
    ["EL-IND-109", "Réglette LED étanche IP65 1,50 m pour atelier", "Luminaire étanche suspendu ou fixé, raccordement sur circuit éclairage existant.", "U", 109, 20, 44, 40, 0.8, ["electricien-industriel", "electricien"]],
    ["EL-IND-110", "Bloc autonome d'éclairage de sécurité (BAES)", "Bloc LED évacuation ou ambiance, raccordement et essai d'autonomie.", "U", 119.5, 20, 44, 48, 0.8, ["electricien-industriel", "electricien"]],
    ["EL-IND-111", "Thermographie infrarouge d'armoires avec rapport", "Contrôle en charge des connexions et protections, rapport avec clichés. Hors travaux correctifs.", "forfait", 292.5, 20, 195, 30, 3, ["electricien-industriel"]],
    ["EL-IND-112", "Levée d'observations du rapport de vérification périodique", "Heure de reprise des non-conformités relevées par l'organisme de contrôle. Fournitures en sus.", "h", 78.5, 20, 58, 0, 1, ["electricien-industriel", "electricien"]],
  ],
  "Réseau et courants faibles": [
    ["EL-COM-101", "Prise RJ45 cat. 6 avec câble ≤ 20 m", "Câble cat. 6 tiré sous gaine, prise encastrée et brassage au coffret. Saignée comptée à part.", "U", 110.5, 10, 55, 30, 1, ["electricien-courants-faibles", "electricien", "domoticien"]],
    ["EL-COM-102", "Câble cat. 6A F/FTP tiré sous gaine", "Fourniture et tirage de câble blindé pour liaison longue ou réseau tertiaire. Raccordements en sus.", "ml", 8, 20, 4.4, 1.8, 0.08, ["electricien-courants-faibles", "electricien"]],
    ["EL-COM-103", "Coffret de communication grade 2 TV équipé", "Tableau de communication avec DTIo, répartiteur TV, panneau RJ45 et prise de courant. Logement.", "U", 552.5, 10, 165, 260, 3, ["electricien-courants-faibles", "electricien", "antenniste", "domoticien"]],
    ["EL-COM-104", "Baie de brassage murale 19\" 12U équipée", "Baie, panneau 24 RJ45 cat. 6, passe-câbles et bandeau de prises. Actifs réseau non compris.", "U", 1014, 20, 220, 560, 4, ["electricien-courants-faibles"]],
    ["EL-COM-105", "Certification de lien cuivre avec rapport (par prise)", "Test au certificateur selon catégorie, étiquetage et rapport de recette.", "U", 11.5, 20, 9, 0, 0.15, ["electricien-courants-faibles"]],
    ["EL-COM-106", "Switch PoE 16 ports fourni et configuré", "Commutateur administrable PoE en baie, configuration de base et VLAN simple.", "U", 533, 20, 90, 320, 1.5, ["electricien-courants-faibles", "installateur-alarme-videosurveillance"]],
    ["EL-COM-107", "Point d'accès Wi-Fi plafonnier PoE", "Borne Wi-Fi fixée au plafond, câble RJ45 ≤ 20 m et configuration du réseau.", "U", 262.5, 10, 72, 130, 1.2, ["electricien-courants-faibles", "domoticien"]],
    ["EL-COM-108", "Prolongation de la fibre de la PTO au coffret de communication", "Déplacement de la prise terminale optique et tirage de jarretière en gaine existante.", "U", 153, 10, 82.5, 35, 1.5, ["electricien-courants-faibles", "antenniste"]],
    ["EL-COM-109", "Interphone audio 1 logement, platine de rue", "Platine 1 bouton, combiné intérieur, câblage ≤ 25 m et alimentation. Gâche comptée à part.", "U", 448.5, 10, 165, 180, 3, ["electricien-courants-faibles", "electricien"]],
    ["EL-COM-110", "Visiophone connecté Wi-Fi avec application", "Platine caméra, moniteur et renvoi d'appel sur smartphone, câblage ≤ 25 m et paramétrage.", "U", 744, 10, 192.5, 380, 3.5, ["electricien-courants-faibles", "electricien", "domoticien", "installateur-alarme-videosurveillance"]],
    ["EL-COM-111", "Platine de rue collective pour immeuble ≤ 10 logements", "Platine audio-vidéo, alimentation, câblage colonne et raccordement des postes existants.", "forfait", 2535, 10, 550, 1400, 10, ["electricien-courants-faibles"]],
    ["EL-COM-112", "Gâche électrique ou ventouse raccordée", "Gâche ou ventouse 300 kg avec alimentation, raccordement à l'interphone ou au contrôle d'accès.", "U", 266.5, 10, 110, 95, 2, ["electricien-courants-faibles", "installateur-alarme-videosurveillance"]],
  ],
  "Domotique et automatismes": [
    ["EL-DOM-101", "Box domotique centrale installée et paramétrée", "Contrôleur multi-protocole, mise en réseau, appairage des équipements et accès distant.", "U", 598, 10, 180, 280, 3, ["domoticien", "electricien-courants-faibles"]],
    ["EL-DOM-102", "Micromodule d'éclairage radio derrière interrupteur", "Module encastré rendant le circuit pilotable, appairage à la box. Interrupteur existant conservé.", "U", 118.5, 10, 36, 55, 0.6, ["domoticien", "electricien"]],
    ["EL-DOM-103", "Raccordement électrique de volet roulant motorisé", "Alimentation depuis circuit dédié, inverseur filaire encastré. Fourniture du volet exclue.", "U", 126, 10, 75, 22, 1.5, ["electricien", "domoticien"]],
    ["EL-DOM-104", "Motorisation radio de volet roulant existant", "Remplacement de la manœuvre manuelle par moteur radio tubulaire et point de commande.", "U", 390, 10, 110, 190, 2, ["domoticien", "electricien"]],
    ["EL-DOM-105", "Centralisation des volets roulants (par volet)", "Module récepteur, commande générale et programmation horaire ou crépusculaire.", "U", 169, 10, 60, 70, 1, ["domoticien", "electricien"]],
    ["EL-DOM-106", "Thermostat connecté avec programmation pièce par pièce", "Thermostat raccordé au générateur, sondes de zone et paramétrage. Éligible TVA réduite.", "U", 364, 5.5, 90, 190, 1.5, ["domoticien", "electricien"]],
    ["EL-DOM-107", "Tête thermostatique connectée sur radiateur à eau", "Remplacement de tête existante, appairage et programmation. Corps de vanne compatible requis.", "U", 109, 5.5, 24, 60, 0.4, ["domoticien"]],
    ["EL-DOM-108", "Module fil pilote connecté par radiateur électrique", "Module derrière radiateur ou au tableau, appairage et plannings de chauffage.", "U", 110.5, 5.5, 30, 55, 0.5, ["domoticien", "electricien"]],
    ["EL-DOM-109", "Point domotique filaire sur bus (par sortie commandée)", "Actionneur sur bus, câble bus et adressage. Hors programmation des scénarios.", "U", 343, 10, 124, 140, 2, ["domoticien"]],
    ["EL-DOM-110", "Programmation de scénarios domotiques", "Heure de création de scénarios, plannings et notifications. Sur box ou bus existant.", "h", 81, 10, 60, 0, 1, ["domoticien"]],
  ],
  "Alarme intrusion": [
    ["EL-ALA-101", "Centrale d'alarme filaire 8 zones avec clavier", "Centrale, batterie, clavier et câblage des zones ≤ 50 m. Détecteurs comptés à part.", "U", 780, 10, 220, 380, 4, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-102", "Centrale d'alarme radio avec transmetteur GSM/IP", "Centrale, clavier, transmetteur et appairage. Abonnement de télésurveillance exclu.", "U", 812.5, 10, 165, 460, 3, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-103", "Détecteur de mouvement infrarouge filaire", "Détecteur IRP fixé en angle, câblage à la centrale ≤ 15 m et réglage de la zone.", "U", 102.5, 10, 44, 35, 0.8, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-104", "Détecteur de mouvement radio immunité animaux", "Détecteur radio fixé, appairage et test de portée.", "U", 126, 10, 22, 75, 0.4, ["installateur-alarme-videosurveillance", "domoticien"]],
    ["EL-ALA-105", "Détecteur d'ouverture radio porte ou fenêtre", "Contact magnétique radio, fixation et appairage.", "U", 80, 10, 16.5, 45, 0.3, ["installateur-alarme-videosurveillance", "domoticien"]],
    ["EL-ALA-106", "Sirène extérieure autoalimentée avec flash", "Sirène en façade ≤ 4 m, batterie et liaison à la centrale.", "U", 328, 10, 82.5, 170, 1.5, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-107", "Clavier ou lecteur de badge supplémentaire", "Organe de commande additionnel fixé, appairé et programmé.", "U", 206, 10, 38.5, 120, 0.7, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-108", "Détecteur de fumée raccordé à la centrale", "Détecteur de fumée radio intégré au système d'alarme, appairage et test.", "U", 119.5, 10, 22, 70, 0.4, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-109", "Maintenance annuelle système d'alarme", "Contrôle des détecteurs, batteries, transmissions et sirènes, rapport. Remplacement de piles en sus.", "forfait", 127, 10, 82.5, 15, 1.5, ["installateur-alarme-videosurveillance"]],
    ["EL-ALA-110", "Dépose d'un système d'alarme existant", "Mise hors service, dépose de la centrale, des détecteurs et sirènes, évacuation.", "forfait", 135, 10, 100, 0, 2, ["installateur-alarme-videosurveillance"]],
  ],
  "Vidéosurveillance et contrôle d'accès": [
    ["EL-VID-101", "Caméra IP dôme 4 MP PoE avec câble ≤ 20 m", "Caméra intérieure ou sous avancée, câble RJ45, réglage du champ et intégration à l'enregistreur.", "U", 377, 10, 110, 180, 2, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-102", "Caméra IP tube 8 MP extérieure infrarouge PoE", "Caméra IP67 en façade ≤ 4 m, câble ≤ 20 m, réglage et masquage des zones privées.", "U", 495.5, 10, 121, 260, 2.2, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-103", "Caméra Wi-Fi autonome sur batterie", "Fixation, appairage à l'application et réglage des zones de détection.", "U", 239, 10, 44, 140, 0.8, ["installateur-alarme-videosurveillance", "domoticien"]],
    ["EL-VID-104", "Enregistreur NVR 8 voies avec disque 2 To", "Enregistreur PoE en baie ou coffret, paramétrage, horodatage et rétention.", "U", 650, 10, 110, 390, 2, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-105", "Configuration de l'accès distant et des notifications", "Accès sécurisé depuis smartphone, comptes utilisateurs et alertes de détection.", "forfait", 81, 10, 60, 0, 1, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-106", "Lecteur de badges autonome 1 porte", "Lecteur, électronique déportée, bouton de sortie et programmation de 20 badges. Gâche comptée à part.", "U", 578.5, 20, 165, 280, 3, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-107", "Contrôle d'accès centralisé 2 portes", "Centrale, 2 lecteurs, boutons de sortie, alimentation secourue et logiciel. Gâches comptées à part.", "forfait", 2574, 20, 580, 1400, 10, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
    ["EL-VID-108", "Clavier à code extérieur antivandale", "Clavier rétroéclairé IP65, câblage à la gâche ou à l'automatisme et programmation des codes.", "U", 263, 10, 82.5, 120, 1.5, ["installateur-alarme-videosurveillance", "electricien-courants-faibles"]],
  ],
  "Bornes de recharge IRVE": [
    ["EL-IRV-101", "Prise renforcée 3,7 kW pour véhicule électrique", "Prise dédiée en garage, protection différentielle type A et câble ≤ 15 m.", "U", 447, 10, 174, 170, 3, ["installateur-irve", "electricien"]],
    ["EL-IRV-102", "Borne 7,4 kW pilotable, liaison ≤ 15 m", "Borne murale, protections dédiées et câble 3G10. Paramétrage et attestation de conformité inclus.", "U", 1492.5, 10, 348, 800, 6, ["installateur-irve", "electricien"]],
    ["EL-IRV-103", "Borne 7,4 kW pilotable, liaison longue ≤ 40 m", "Borne murale avec liaison en goulotte, fourreau ou sous-sol. Tranchée et carottage exclus.", "U", 2288, 10, 580, 1180, 10, ["installateur-irve", "electricien"]],
    ["EL-IRV-104", "Borne 11 kW triphasée, liaison ≤ 15 m", "Borne murale tri, protections dédiées et câble 5G6. Abonnement triphasé requis.", "U", 1802, 10, 406, 980, 7, ["installateur-irve", "electricien"]],
    ["EL-IRV-105", "Borne 22 kW triphasée professionnelle, liaison ≤ 15 m", "Borne avec badge RFID, protections, câble 5G16 et paramétrage. Local professionnel.", "U", 2228, 20, 464, 1250, 8, ["installateur-irve"]],
    ["EL-IRV-106", "Borne 22 kW triphasée, liaison longue ≤ 50 m", "Borne professionnelle avec liaison sur chemin de câbles ou fourreau. Tranchée exclue.", "U", 3450, 20, 754, 1900, 13, ["installateur-irve"]],
    ["EL-IRV-107", "Borne double 2 × 22 kW sur pied pour parking", "Borne sur pied avec massif béton, supervision et badges. Liaison et tranchée comptées à part.", "U", 6390, 20, 812, 4300, 14, ["installateur-irve"]],
    ["EL-IRV-108", "Supplément de liaison de borne au-delà du forfait", "Câble 3G10 ou 5G6 avec goulotte ou fourreau, au mètre supplémentaire. Tranchée exclue.", "ml", 33.5, 10, 11.6, 14, 0.2, ["installateur-irve", "electricien"]],
    ["EL-IRV-109", "Module de gestion dynamique de puissance", "Mesure au tableau et délestage de la borne selon la consommation du logement.", "U", 347, 10, 87, 180, 1.5, ["installateur-irve", "electricien", "domoticien"]],
    ["EL-IRV-110", "Pied support de borne avec massif béton", "Pied métallique, fourreau et massif coulé. Tranchée d'alimentation non comprise.", "U", 578.5, 10, 165, 280, 3, ["installateur-irve"]],
    ["EL-IRV-111", "Pré-équipement de place en parking collectif", "Chemin de câbles, attente de câble et protection en tableau d'étage. Borne non comprise.", "U", 473, 10, 174, 190, 3, ["installateur-irve", "electricien"]],
    ["EL-IRV-112", "Dépose de borne de recharge existante", "Mise hors tension, dépose, isolation de la ligne et évacuation de l'équipement.", "U", 111.5, 10, 82.5, 0, 1.5, ["installateur-irve"]],
    ["EL-IRV-113", "Maintenance annuelle de borne de recharge", "Contrôle des protections et du serrage, test de charge et mise à jour du logiciel.", "forfait", 126, 10, 87, 10, 1.5, ["installateur-irve"]],
  ],
  "Antennes et réception TV": [
    ["EL-ANT-101", "Antenne TNT râteau sur mât existant, orientation", "Antenne extérieure, câble coaxial ≤ 15 m et réglage au mesureur de champ.", "U", 252, 10, 104, 90, 2, ["antenniste"]],
    ["EL-ANT-102", "Antenne TNT avec mât 2 m et cerclage de cheminée", "Mât, cerclage, antenne et descente coaxiale ≤ 20 m. Mise à la terre comptée à part.", "U", 483.5, 10, 182, 190, 3.5, ["antenniste"]],
    ["EL-ANT-103", "Parabole 80 cm avec tête LNB et pointage", "Support mural, parabole, LNB et câble ≤ 15 m. Pointage au mesureur.", "U", 325, 10, 130, 120, 2.5, ["antenniste"]],
    ["EL-ANT-104", "Remplacement de tête LNB et repointage", "Dépose de la LNB défectueuse, pose d'une tête neuve et repointage du satellite.", "U", 117.5, 10, 52, 35, 1, ["antenniste"]],
    ["EL-ANT-105", "Dépannage réception TV ou satellite", "Diagnostic au mesureur, réorientation et remplacement de connectique. Pièces importantes en sus.", "forfait", 119, 10, 78, 10, 1.5, ["antenniste"]],
    ["EL-ANT-106", "Amplificateur d'antenne avec alimentation", "Amplificateur réglable en mât ou en combles, alimentation et réglage des niveaux.", "U", 158.5, 10, 52, 70, 1, ["antenniste"]],
    ["EL-ANT-107", "Répartiteur 4 sorties avec raccordements", "Répartiteur blindé, connecteurs F et contrôle des niveaux sur chaque prise.", "U", 86.5, 10, 41.6, 25, 0.8, ["antenniste", "electricien-courants-faibles"]],
    ["EL-ANT-108", "Prise TV/SAT supplémentaire avec câble ≤ 20 m", "Câble coaxial sous gaine ou goulotte, prise et raccordement au répartiteur.", "U", 113.5, 10, 62.4, 25, 1.2, ["antenniste", "electricien", "electricien-courants-faibles"]],
    ["EL-ANT-109", "Câble coaxial blindé fourni et tiré", "Câble coaxial haute qualité pour descente ou distribution, au mètre.", "ml", 7, 10, 4.16, 1.2, 0.08, ["antenniste", "electricien-courants-faibles"]],
    ["EL-ANT-110", "Mât supplémentaire 3 m avec haubanage", "Mât acier, haubans et ancrages en toiture. Nacelle ou échafaudage non compris.", "U", 312, 10, 130, 110, 2.5, ["antenniste"]],
    ["EL-ANT-111", "Tête de réseau collective TNT/SAT (≤ 20 logements)", "Antennes, centrale programmable, multiswitch et réglages en tête. Distribution colonne en sus.", "forfait", 3546.5, 10, 928, 1800, 16, ["antenniste"]],
    ["EL-ANT-112", "Remise à niveau de la distribution collective (par prise)", "Remplacement de dérivateur et de prise, contrôle des niveaux en logement.", "U", 123.5, 10, 55, 40, 1, ["antenniste"]],
    ["EL-ANT-113", "Dépose d'ancienne antenne et évacuation", "Dépose de l'antenne, du mât et des câbles inutilisés, évacuation en déchetterie.", "U", 83.5, 10, 52, 10, 1, ["antenniste"]],
  ],
});
