import { defineCatalog } from "./define";

export const CATALOG_GROS_OEUVRE = defineCatalog("gros-oeuvre", {
  "Installation de chantier": [
    ["GO-INS-101", "Installation et repli de chantier (clôture, signalisation, accès)", "Mise en place et repli : balisage, panneau, accès, rangement et nettoyage final. WC chimique et base vie non compris.", "forfait", 507, 10, 270, 120, 6],
    ["GO-INS-102", "Frais de déplacement chantier zone ≤ 30 km", "Aller-retour véhicule utilitaire et temps de trajet de l'équipe, par jour d'intervention.", "forfait", 91, 10, 45, 25, 1],
    ["GO-INS-103", "Benne 8 m³ gravats inertes (béton, brique, terre)", "Location, livraison, enlèvement et mise en décharge agréée de déchets inertes triés. Chargement non compris.", "U", 503, 10, 22.5, 380, 0.5],
    ["GO-INS-104", "Benne 10 m³ déchets non dangereux en mélange", "Location, rotation et traitement en centre agréé (bois, plâtre, plastiques). Amiante et déchets dangereux exclus.", "U", 803, 10, 22.5, 620, 0.5],
    ["GO-INS-105", "Protection des sols et abords existants (polyane, panneaux)", "Fourniture et pose de protections sur sols, escaliers et végétaux conservés, dépose en fin de chantier.", "m²", 9, 10, 4.5, 2.5, 0.1],
    ["GO-INS-106", "Main d'œuvre en régie, ouvrier qualifié", "Heure de travail effectif d'un ouvrier qualifié pour travaux non prévus au devis. Fournitures facturées en sus.", "h", 61, 10, 45, 0, 1],
    ["GO-INS-107", "Main d'œuvre en régie, chef d'équipe / compagnon", "Heure de travail effectif d'un compagnon ou chef d'équipe. Fournitures et engins facturés en sus.", "h", 74, 10, 55, 0, 1],
    ["GO-INS-108", "Forfait petite intervention gros œuvre (≤ 2 h sur place)", "Déplacement, 2 h de main d'œuvre et petites fournitures courantes. Au-delà, régie horaire.", "forfait", 148.5, 10, 90, 20, 2],
  ],
  "Terrassement": [
    ["GO-TER-101", "Décapage de terre végétale ép. 20 à 30 cm, mise en dépôt", "Décapage à la pelle et stockage sur site pour réemploi. Évacuation non comprise.", "m²", 3, 20, 1.5, 0.8, 0.03, ["terrassier"]],
    ["GO-TER-102", "Terrassement en pleine masse à la mini-pelle, terrain ordinaire", "Fouille en pleine masse avec accès restreint, jet sur berge ou chargement. Évacuation et blindage exclus.", "m³", 26.5, 20, 17.5, 3, 0.35, ["terrassier", "macon"]],
    ["GO-TER-103", "Fouille en puits pour semelle isolée, profondeur ≤ 1,50 m", "Fouille mécanique localisée, dressement des parois et fond de fouille. Évacuation des terres non comprise.", "m³", 83, 20, 60, 4, 1.2, ["terrassier", "macon"]],
    ["GO-TER-104", "Fouille manuelle en accès difficile, terrain ordinaire", "Terrassement à la main (intérieur, cour, sous plancher), jet sur berge. Évacuation non comprise.", "m³", 292.5, 10, 225, 0, 5, ["terrassier", "macon", "demolisseur"]],
    ["GO-TER-105", "Terrassement en terrain rocheux au brise-roche hydraulique", "Fragmentation au BRH sur pelle et extraction des blocs. Évacuation non comprise.", "m³", 175.5, 20, 110, 25, 2, ["terrassier", "demolisseur"]],
    ["GO-TER-106", "Évacuation des terres en décharge (≤ 20 km)", "Chargement, transport et redevance de mise en décharge de terres non polluées, au m³ en place.", "m³", 45, 20, 12.5, 22, 0.25, ["terrassier", "demolisseur"]],
    ["GO-TER-107", "Remblai périphérique en matériaux du site compactés", "Remblaiement par couches de 30 cm compactées, matériaux sains issus des fouilles.", "m³", 41.5, 20, 28.8, 3, 0.6, ["terrassier", "macon"]],
    ["GO-TER-108", "Remblai en grave 0/31,5 fournie et compactée", "Fourniture, mise en œuvre par couches et compactage au rouleau ou à la plaque.", "m³", 79, 20, 28.8, 32, 0.6, ["terrassier", "macon"]],
    ["GO-TER-109", "Hérisson pierres 40/80 ép. 20 cm sous dallage", "Fourniture, réglage et compactage d'un hérisson drainant. Film polyane non compris.", "m²", 24, 20, 12, 6.5, 0.25, ["terrassier", "macon"]],
    ["GO-TER-110", "Tranchée pour réseaux 40 × 80 cm, remblai et grillage avertisseur", "Ouverture, lit de sable, remblaiement compacté et grillage. Fourniture des fourreaux non comprise.", "ml", 36.5, 10, 24, 4, 0.5, ["terrassier"]],
    ["GO-TER-111", "Drainage périphérique PVC Ø 100, géotextile et gravier 20/40", "Drain fourni posé en pied de fondation, enrobage gravier et géotextile. Fouille et regards non compris.", "ml", 61, 10, 28.8, 18, 0.6, ["terrassier", "macon"]],
    ["GO-TER-112", "Regard béton 40 × 40 avec tampon fonte, fourni posé", "Regard de visite ou de drainage, raccordements et calage béton. Terrassement non compris.", "U", 165, 10, 72, 55, 1.5, ["terrassier", "macon"]],
    ["GO-TER-113", "Puits d'infiltration buse béton Ø 1000, hauteur 2 m", "Fouille, buses, remplissage galets et géotextile, tampon. Étude de sol non comprise.", "U", 975, 10, 300, 450, 6, ["terrassier"]],
    ["GO-TER-114", "Location mini-pelle 2,5 t avec chauffeur", "Journée de 8 h, carburant et transport compris dans un rayon de 20 km.", "jour", 700, 20, 400, 160, 8, ["terrassier", "demolisseur", "macon"]],
    ["GO-TER-115", "Location pelle 8 t avec chauffeur", "Journée de 8 h, carburant compris. Transport porte-engin facturé à part.", "jour", 962.5, 20, 440, 330, 8, ["terrassier", "demolisseur"]],
  ],
  "Fondations": [
    ["GO-FON-101", "Semelle isolée béton armé 60 × 60 × 40 cm", "Béton C25/30, armatures et coulage pleine fouille. Fouille et évacuation non comprises.", "U", 152, 20, 72, 45, 1.5, ["macon", "constructeur-beton-arme"]],
    ["GO-FON-102", "Semelle isolée béton armé 100 × 100 × 50 cm", "Béton C25/30, nappe d'armatures et attentes de poteau. Fouille non comprise.", "U", 292.5, 20, 120, 105, 2.5, ["macon", "constructeur-beton-arme"]],
    ["GO-FON-103", "Gros béton de puits ou de rattrapage de fondation", "Béton dosé 250 kg coulé en pleine fouille jusqu'au bon sol. Fouille non comprise.", "m³", 243, 20, 72, 115, 1.5, ["macon", "constructeur-beton-arme", "terrassier"]],
    ["GO-FON-104", "Longrine béton armé 20 × 40 cm coffrée", "Coffrage, armatures 4 HA12 et béton C25/30, décoffrage. Fouille et plots non compris.", "ml", 132.5, 20, 70, 32, 1.4, ["macon", "constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-FON-105", "Mur de soubassement en blocs pleins 20 cm (vide sanitaire)", "Blocs pleins hourdés au mortier sur semelle, h ≤ 1 m. Arase et chaînage non compris.", "m²", 120, 20, 62.4, 30, 1.3, ["macon"]],
    ["GO-FON-106", "Dallage sur terre-plein béton armé 12 cm", "Polyane, treillis ST25C et béton C25/30 talochés. Hérisson non compris.", "m²", 68.5, 20, 28.8, 24, 0.6, ["macon", "constructeur-beton-arme"]],
    ["GO-FON-107", "Reprise en sous-œuvre par plots béton alternés", "Ouverture par passes, coffrage, béton et clavage au mortier sans retrait. Étude de structure exclue.", "ml", 756, 10, 440, 120, 8, ["macon", "constructeur-beton-arme"]],
    ["GO-FON-108", "Radier béton armé 25 cm double nappe", "Béton C25/30 et armatures HA en deux nappes, coulage à la pompe. Terrassement non compris.", "m²", 161.5, 20, 62.4, 62, 1.2, ["constructeur-beton-arme", "macon", "coffreur-bancheur"]],
  ],
  "Maçonnerie": [
    ["GO-MAC-101", "Mur en parpaings creux 15 × 20 × 50", "Blocs NF hourdés au mortier, joints réglés. Chaînages et enduit non compris.", "m²", 70.5, 20, 38.25, 16, 0.85, ["macon"]],
    ["GO-MAC-102", "Cloison en parpaings creux 10 cm", "Cloison intérieure hourdée au mortier, liaisons aux murs existants. Enduit non compris.", "m²", 61, 10, 33.75, 13, 0.75, ["macon"]],
    ["GO-MAC-103", "Mur en brique monomur 30 cm à joint mince", "Briques à rectifier collées, accessoires d'angle et de tableau. Enduit non compris.", "m²", 124, 20, 43.2, 52, 0.9, ["macon"]],
    ["GO-MAC-104", "Mur en brique creuse 20 cm à joint mince", "Briques rectifiées collées sur lit de mortier de pose. Doublage et enduit non compris.", "m²", 93, 20, 38.4, 33, 0.8, ["macon"]],
    ["GO-MAC-105", "Mur en béton cellulaire 25 cm collé", "Blocs béton cellulaire collés au mortier-colle, premier rang au mortier. Enduit non compris.", "m²", 106, 20, 33.6, 48, 0.7, ["macon"]],
    ["GO-MAC-106", "Mur en blocs à bancher 20 cm remplis béton", "Blocs posés à sec, remplissage béton C25/30 vibré. Aciers verticaux comptés à part.", "m²", 113, 20, 52.8, 34, 1.1, ["macon", "constructeur-beton-arme"]],
    ["GO-MAC-107", "Chaînage horizontal béton armé 20 × 20 cm", "Coffrage ou blocs U, 4 HA10 avec cadres et béton. Inclus dans les murs neufs ou rénovés.", "ml", 53, 20, 28.8, 12, 0.6, ["macon", "constructeur-beton-arme"]],
    ["GO-MAC-108", "Linteau béton préfabriqué ≤ 1,40 m fourni posé", "Linteau précontraint posé sur mortier avec calage et appuis de 20 cm minimum.", "U", 89, 10, 38.4, 30, 0.8, ["macon"]],
    ["GO-MAC-109", "Ouverture mur porteur parpaing ≤ 1,20 m avec linteau BA", "Étaiement, sciage, linteau béton armé et reprise des tableaux bruts. Évacuation et finitions exclues.", "U", 1161, 10, 700, 160, 14, ["macon", "demolisseur"]],
    ["GO-MAC-110", "Ouverture mur porteur pierre ≤ 1,50 m avec deux IPN", "Étaiement, saignées, pose des poutrelles sur sommiers, démolition et tableaux bruts. Hors évacuation.", "U", 2252, 10, 1248, 420, 24, ["macon", "charpentier-metallique", "demolisseur"]],
    ["GO-MAC-111", "Grande ouverture mur porteur ≤ 3 m, poutre HEB et poteaux", "Étaiement, poutre et poteaux acier, sommiers et démolition. Note de calcul et finitions exclues.", "forfait", 4293, 10, 2080, 1100, 40, ["macon", "charpentier-metallique"]],
    ["GO-MAC-112", "Rebouchage d'ouverture en parpaings (≤ 2 m²)", "Fermeture de baie existante avec harpage ou ancrage, faces brutes prêtes à enduire.", "U", 292.5, 10, 180, 45, 4, ["macon"]],
    ["GO-MAC-113", "Appui de fenêtre béton préfabriqué ≤ 1,20 m", "Dépose de l'ancien appui exclue. Pose au mortier avec pente et rejingot, joints.", "U", 119.5, 10, 54, 38, 1.2, ["macon", "facadier-ravaleur"]],
    ["GO-MAC-114", "Muret de clôture parpaing h 1 m sur semelle, avec chaperon", "Semelle, élévation en blocs, chaînage et chaperon. Enduit et terrassement non compris.", "ml", 208.5, 10, 112.5, 48, 2.5, ["macon"]],
    ["GO-MAC-115", "Pilier de portail 30 × 30 cm h 1,80 m avec chapeau", "Bloc pilier armé et rempli béton sur massif, platines ou gonds scellés. Enduit non compris.", "U", 325, 10, 180, 70, 4, ["macon"]],
    ["GO-MAC-116", "Mur de soutènement béton armé h ≤ 1,50 m", "Semelle et voile BA coffrés, barbacanes et drain. Terrassement et étude exclus.", "ml", 714, 10, 364, 165, 7, ["macon", "constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-MAC-117", "Escalier béton droit coulé en place (≤ 15 marches)", "Coffrage, ferraillage, béton et décoffrage, marches brutes. Revêtement et garde-corps exclus.", "forfait", 3124, 10, 1664, 650, 32, ["macon", "constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-MAC-118", "Chape ciment traditionnelle ép. 5 cm", "Chape dosée à 350 kg tirée à la règle et talochée. Isolant sous chape non compris.", "m²", 28, 10, 13.5, 8, 0.3, ["macon"]],
    ["GO-MAC-119", "Chape fluide anhydrite ép. 5 cm pompée", "Bande périphérique, film et coulage à la pompe. Ponçage éventuel non compris.", "m²", 26.5, 10, 5.4, 15, 0.12, ["macon"]],
    ["GO-MAC-120", "Mur en pierre de pays hourdé à la chaux ép. 40 cm", "Reconstruction à l'identique avec pierres fournies ou de réemploi, joints chaux.", "m²", 507, 10, 300, 90, 6, ["macon"]],
    ["GO-MAC-121", "Scellement de gond, patte ou ferrure", "Percement, scellement au mortier ou à la résine. Fourniture de la pièce scellée exclue.", "U", 34.5, 10, 22.5, 3, 0.5, ["macon"]],
    ["GO-MAC-122", "Saignée et rebouchage en maçonnerie", "Saignée pour gaine ou tuyau et rebouchage au mortier, finition brute.", "ml", 26.5, 10, 18, 1.5, 0.4, ["macon"]],
    ["GO-MAC-123", "Raccord de maçonnerie après pose de menuiserie", "Reprise des tableaux et de l'appui au mortier, finition prête à peindre ou à enduire.", "U", 137.5, 10, 90, 12, 2, ["macon", "facadier-ravaleur"]],
  ],
  "Béton armé": [
    ["GO-BET-101", "Dalle béton armé 12 cm coulée sur coffrage", "Coffrage, étaiement, treillis et béton C25/30. Pour mezzanine ou plancher de faible portée.", "m²", 121, 20, 55, 38, 1.1, ["constructeur-beton-arme", "macon", "coffreur-bancheur"]],
    ["GO-BET-102", "Dalle béton armé 20 cm portée sur coffrage", "Coffrage et étaiement, ferraillage selon plan, béton pompé. Note de calcul non comprise.", "m²", 162.5, 20, 70, 55, 1.4, ["constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-BET-103", "Plancher poutrelles-hourdis béton 16 + 4", "Poutrelles précontraintes, entrevous béton, treillis et dalle de compression. Étaiement compris.", "m²", 106.5, 20, 40, 42, 0.8, ["constructeur-beton-arme", "macon"]],
    ["GO-BET-104", "Plancher poutrelles et entrevous isolants sur vide sanitaire", "Entrevous PSE avec rupteurs, treillis et dalle de compression 5 cm.", "m²", 123.5, 20, 40, 55, 0.8, ["constructeur-beton-arme", "macon"]],
    ["GO-BET-105", "Voile béton armé banché 18 cm", "Coffrage deux faces, armatures et béton C25/30 vibré. Parement brut ordinaire.", "m²", 170.5, 20, 83.2, 48, 1.6, ["constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-BET-106", "Poteau béton armé 20 × 20 cm coffré", "Coffrage, cage d'armatures et béton, décoffrage. Hauteur courante ≤ 3 m.", "ml", 104.5, 20, 62.4, 18, 1.2, ["constructeur-beton-arme", "coffreur-bancheur", "macon"]],
    ["GO-BET-107", "Poutre béton armé 20 × 40 cm coffrée et étayée", "Coffrage fond et joues, armatures, béton et étaiement jusqu'à 28 jours.", "ml", 160.5, 20, 93.6, 30, 1.8, ["constructeur-beton-arme", "coffreur-bancheur"]],
    ["GO-BET-108", "Linteau béton armé coulé en place 20 × 20 cm", "Coffrage, 4 HA10 avec cadres, béton. Pour portée ≤ 2 m en reprise de baie.", "ml", 83, 10, 50, 14, 1, ["constructeur-beton-arme", "macon"]],
    ["GO-BET-109", "Béton C25/30 prêt à l'emploi mis en œuvre", "Livraison toupie, mise en place et vibration. Coffrage et armatures comptés à part.", "m³", 281, 20, 60, 165, 1.2, ["constructeur-beton-arme", "macon", "coffreur-bancheur"]],
    ["GO-BET-110", "Réparation béton éclaté : passivation et mortier de réparation", "Purge, brossage des aciers, passivation et reprofilage au mortier R3/R4. Hors échafaudage.", "m²", 233, 10, 137.5, 35, 2.5, ["constructeur-beton-arme", "macon", "facadier-ravaleur"]],
    ["GO-BET-111", "Balcon béton armé en porte-à-faux", "Coffrage, armatures, béton et rupteurs. Étanchéité et garde-corps non compris.", "m²", 533, 20, 275, 120, 5, ["constructeur-beton-arme", "coffreur-bancheur"]],
  ],
  "Coffrage": [
    ["GO-COF-101", "Coffrage bois traditionnel de voile, deux faces", "Panneaux, banches bois, entretoises et décoffrage. Location d'étais incluse.", "m²", 72.5, 20, 46.8, 9, 0.9, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-102", "Coffrage de voile en banches métalliques", "Location, réglage, huilage, mannequins courants et décoffrage. Levage non compris.", "m²", 49.5, 20, 26, 12, 0.5, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-103", "Coffrage de rive de dalle h ≤ 25 cm", "Planches de rive, équerres et décoffrage. Pour dalle ou dallage.", "ml", 28, 20, 17.5, 4, 0.35, ["coffreur-bancheur", "constructeur-beton-arme", "macon"]],
    ["GO-COF-104", "Coffrage et étaiement de dalle (contreplaqué et étais)", "Fond de coffrage, poutrelles et étais réglables, décoffrage à 28 jours.", "m²", 57, 20, 35, 9, 0.7, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-105", "Coffrage de poutre (fond et joues) étayée", "Coffrage bois, étaiement et décoffrage. Mesuré en surface coffrée.", "m²", 87.5, 20, 57.2, 10, 1.1, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-106", "Coffrage d'escalier (paillasse et contremarches)", "Fond de paillasse, joues et contremarches réglées, étaiement compris.", "m²", 192.5, 20, 130, 18, 2.5, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-107", "Réservation ou trémie dans voile ou dalle", "Mannequin bois ou polystyrène jusqu'à 0,5 m², calé et retiré après coulage.", "U", 62.5, 20, 40, 8, 0.8, ["coffreur-bancheur", "constructeur-beton-arme"]],
    ["GO-COF-108", "Étaiement provisoire de plancher existant", "Étais métalliques et bastaings sous solives pendant travaux, location un mois.", "m²", 30, 10, 19.2, 4, 0.4, ["coffreur-bancheur", "macon", "constructeur-beton-arme", "demolisseur"]],
  ],
  "Ferraillage": [
    ["GO-FER-101", "Armatures HA façonnées et posées (lot de 100 kg)", "Aciers B500B coupés, façonnés et ligaturés selon plan, cales comprises.", "U", 338, 20, 125, 135, 2.5, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-102", "Treillis soudé ST25C pour dallage, posé sur cales", "Fourniture et pose avec recouvrements réglementaires et distanciers.", "m²", 10.5, 20, 3.84, 4.2, 0.08, ["ferrailleur", "macon"]],
    ["GO-FER-103", "Armatures de semelle filante prêtes à poser 35 × 15", "Filants préfabriqués avec recouvrements et équerres d'angle, posés sur cales.", "ml", 19, 20, 7.2, 7.5, 0.15, ["ferrailleur", "macon", "constructeur-beton-arme"]],
    ["GO-FER-104", "Chaînage préfabriqué 4 HA10 avec cadres, posé", "Fourniture et pose en blocs U ou coffrage, recouvrements et retours d'angle.", "ml", 13.5, 20, 4.8, 5.5, 0.1, ["ferrailleur", "macon"]],
    ["GO-FER-105", "Cage de poteau façonnée sur plan", "4 à 6 HA avec cadres, attentes et ligatures. Poteau courant ≤ 30 × 30 cm.", "ml", 38.5, 20, 20.8, 9, 0.4, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-106", "Armatures de poutre (filants et cadres) façonnées", "Filants supérieurs et inférieurs, cadres et épingles selon plan.", "ml", 68, 20, 36.4, 16, 0.7, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-107", "Ferraillage de voile double nappe et U de rive", "Treillis deux faces, U de rive, chapeaux de baie et cales.", "m²", 38, 20, 18.2, 11, 0.35, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-108", "Ferraillage de radier double nappe HA", "Deux nappes croisées, chaises de calage et recouvrements selon plan.", "m²", 62.5, 20, 26, 22, 0.5, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-109", "Ferraillage de longrine 20 × 40 (4 HA12 et cadres HA6)", "Façonnage, assemblage et pose dans coffrage, attentes de raccordement.", "ml", 31, 20, 15, 9, 0.3, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-110", "Renforts de trémie et chapeaux d'angle", "Barres de renfort et chapeaux autour d'une trémie ou d'un angle rentrant.", "U", 69.5, 20, 41.6, 12, 0.8, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-111", "Armatures d'escalier béton façonnées", "Paillasse, paliers et attentes pour un escalier droit ≤ 15 marches.", "forfait", 481, 20, 260, 110, 5, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-112", "Armatures de balcon avec rupteurs thermiques", "Rupteurs de pont thermique et aciers de porte-à-faux selon plan.", "ml", 151, 20, 31.2, 85, 0.6, ["ferrailleur", "constructeur-beton-arme"]],
    ["GO-FER-113", "Scellement chimique d'armature en attente HA12", "Forage, nettoyage, injection de résine et mise en place de la barre.", "U", 22.5, 10, 13, 3.5, 0.25, ["ferrailleur", "constructeur-beton-arme", "macon"]],
    ["GO-FER-114", "Pose d'armatures fournies par le client (lot de 100 kg)", "Main d'œuvre de pose et ligatures uniquement. Aciers non fournis.", "U", 165, 20, 125, 2, 2.5, ["ferrailleur"]],
  ],
  "Charpente bois": [
    ["GO-CHA-101", "Charpente traditionnelle résineux, pannes et chevrons", "Pannes, chevrons et fermes en sapin traité classe 2, levage compris. Couverture exclue.", "m²", 170.5, 20, 83.2, 48, 1.6, ["charpentier-bois"]],
    ["GO-CHA-102", "Charpente traditionnelle en chêne massif", "Fermes assemblées tenon-mortaise, pannes et chevrons chêne. Couverture exclue.", "m²", 281, 20, 121, 95, 2.2, ["charpentier-bois"]],
    ["GO-CHA-103", "Remplacement de chevrons résineux", "Dépose du chevron dégradé, fourniture et pose d'un chevron traité. Couverture exclue.", "ml", 40.5, 10, 25, 6, 0.5, ["charpentier-bois"]],
    ["GO-CHA-104", "Remplacement de panne résineux ou lamellé-collé ≤ 6 m", "Étaiement, dépose, pose de la nouvelle panne et fixations. Couverture exclue.", "ml", 147, 10, 78, 35, 1.5, ["charpentier-bois"]],
    ["GO-CHA-105", "Poutre lamellé-collé portée ≤ 6 m fournie posée", "Poutre GL24h traitée, sabots ou appuis maçonnés. Levage manuel ou petit engin.", "ml", 178.5, 10, 62.4, 75, 1.2, ["charpentier-bois"]],
    ["GO-CHA-106", "Traitement préventif de charpente par pulvérisation", "Brossage, dépoussiérage et pulvérisation insecticide-fongicide sur bois apparents.", "m²", 8, 10, 3.84, 2.5, 0.08, ["charpentier-bois"]],
    ["GO-CHA-107", "Murs à ossature bois 145 mm avec OSB et pare-pluie", "Montants, lisses, contreventement OSB et pare-pluie. Isolant et parement exclus.", "m²", 159.5, 20, 67.6, 55, 1.3, ["charpentier-bois"]],
    ["GO-CHA-108", "Plancher bois solives 75 × 200 et OSB 22 mm", "Solivage traité, entretoises, panneaux OSB vissés-collés. Finition non comprise.", "m²", 126.5, 10, 57.2, 40, 1.1, ["charpentier-bois"]],
    ["GO-CHA-109", "Mezzanine bois ≤ 10 m² sur structure existante", "Solivage, chevêtre d'accès et plancher OSB. Escalier et garde-corps exclus.", "m²", 247, 10, 130, 60, 2.5, ["charpentier-bois"]],
    ["GO-CHA-110", "Chevêtre pour trémie (fenêtre de toit, escalier)", "Coupe des pièces, chevêtres et renforts boulonnés. Fenêtre de toit non comprise.", "U", 329, 10, 208, 45, 4, ["charpentier-bois"]],
    ["GO-CHA-111", "Auvent ou appentis bois sur poteaux", "Poteaux, platines, chevrons et voligeage. Couverture et massifs exclus.", "m²", 226, 10, 104, 70, 2, ["charpentier-bois"]],
    ["GO-CHA-112", "Carport bois 1 voiture 3 × 5 m", "Structure résineux traitée autoclave sur platines, toiture bac acier incluse. Massifs exclus.", "forfait", 3380, 20, 1200, 1400, 24, ["charpentier-bois"]],
    ["GO-CHA-113", "Pergola bois adossée 3 × 4 m", "Poteaux, sablières et chevrons traités autoclave sur platines. Couverture exclue.", "forfait", 2210, 10, 800, 900, 16, ["charpentier-bois"]],
    ["GO-CHA-114", "Redressement et calage de charpente affaissée", "Étaiement, vérinage, moisage des pièces et reprise des appuis. Diagnostic structure exclu.", "forfait", 1460.5, 10, 832, 250, 16, ["charpentier-bois"]],
    ["GO-CHA-115", "Dépose de charpente bois existante", "Dépose soignée ou démolition des pièces, tri sur site. Évacuation non comprise.", "m²", 30.5, 10, 22.5, 0, 0.5, ["charpentier-bois", "demolisseur"]],
  ],
  "Charpente métallique": [
    ["GO-CMT-101", "Poutrelle IPN 200 fournie posée en reprise", "Poutrelle avec antirouille, posée sur sommiers. Ouverture et sommiers comptés à part.", "ml", 201.5, 10, 110, 45, 2, ["charpentier-metallique", "macon"]],
    ["GO-CMT-102", "Poutrelle HEA / HEB 200 fournie posée", "Profilé débité à longueur, antirouille, levage et calage sur appuis.", "ml", 242, 10, 121, 65, 2.2, ["charpentier-metallique", "macon"]],
    ["GO-CMT-103", "Poteau acier HEA 160 avec platine et ancrages", "Poteau ≤ 3 m, platine soudée, scellement chimique et calage mortier.", "U", 396.5, 10, 165, 140, 3, ["charpentier-metallique"]],
    ["GO-CMT-104", "Sommier béton préfabriqué sous poutrelle", "Sommier ou plaque d'appui scellé au mortier sans retrait dans la maçonnerie.", "U", 104, 10, 60, 20, 1.2, ["charpentier-metallique", "macon"]],
    ["GO-CMT-105", "Mezzanine métallique avec plancher bois", "Structure acier galvanisée ou peinte, solivage et plancher. Escalier et garde-corps exclus.", "m²", 382, 10, 174, 120, 3, ["charpentier-metallique"]],
    ["GO-CMT-106", "Portique acier pour bâtiment de stockage (m² d'emprise)", "Portiques galvanisés, pannes et contreventements, levage. Couverture et fondations exclues.", "m²", 181.5, 20, 69.6, 70, 1.2, ["charpentier-metallique"]],
    ["GO-CMT-107", "Escalier métallique droit, marches tôle larmée", "Limons acier, marches larmées, peinture antirouille. Garde-corps non compris.", "forfait", 2766.5, 10, 928, 1200, 16, ["charpentier-metallique"]],
    ["GO-CMT-108", "Garde-corps acier barreaudé thermolaqué", "Fabrication, thermolaquage et pose par platines. Conforme hauteur 1 m.", "ml", 289, 10, 82.5, 140, 1.5, ["charpentier-metallique"]],
    ["GO-CMT-109", "Carport métallique 1 voiture", "Structure acier galvanisé sur platines, couverture bac acier. Massifs exclus.", "forfait", 3484, 20, 880, 1800, 16, ["charpentier-metallique"]],
    ["GO-CMT-110", "Antirouille et peinture sur ossature acier existante", "Brossage, antirouille et deux couches de finition glycéro ou polyuréthane.", "m²", 33, 10, 19.2, 6, 0.4, ["charpentier-metallique"]],
    ["GO-CMT-111", "Modification ou soudure sur ossature existante (régie)", "Heure de soudeur avec poste, consommables et petits profilés courants.", "h", 88.5, 10, 60, 8, 1, ["charpentier-metallique"]],
    ["GO-CMT-112", "Chariot télescopique avec conducteur", "Journée de levage de charpente ou de profilés, transport aller-retour compris.", "jour", 900, 20, 440, 280, 8, ["charpentier-metallique", "charpentier-bois"]],
    ["GO-CMT-113", "Démontage d'ossature métallique par oxycoupage", "Découpe, descente des éléments et tri de la ferraille. Évacuation non comprise.", "m²", 39.5, 10, 27.5, 3, 0.5, ["charpentier-metallique", "demolisseur"]],
  ],
  "Démolition": [
    ["GO-DEM-101", "Démolition de mur porteur en parpaings", "Démolition manuelle ou mécanisée après étaiement (compté à part). Hors évacuation.", "m²", 91, 10, 67.5, 0, 1.5, ["demolisseur", "macon"]],
    ["GO-DEM-102", "Démolition de mur en pierre ép. ≤ 50 cm", "Démolition soignée avec tri des pierres réemployables. Évacuation non comprise.", "m²", 182, 10, 135, 0, 3, ["demolisseur", "macon"]],
    ["GO-DEM-103", "Démolition de cloison plâtre ou carreaux de plâtre", "Dépose avec ossature et isolant éventuels, mise en sacs. Évacuation non comprise.", "m²", 20, 10, 14.7, 0, 0.35, ["demolisseur", "macon"]],
    ["GO-DEM-104", "Démolition de dalle béton armé ép. ≤ 15 cm", "Sciage en éléments, BRH et découpe des aciers. Étaiement et évacuation exclus.", "m²", 92, 10, 60, 8, 1.2, ["demolisseur", "constructeur-beton-arme"]],
    ["GO-DEM-105", "Démolition de chape et carrelage", "Piquage jusqu'au support, mise en sacs ou en tas. Évacuation non comprise.", "m²", 31.5, 10, 22.5, 1, 0.5, ["demolisseur", "macon"]],
    ["GO-DEM-106", "Démolition de dallage ou terrasse béton extérieure", "Démolition au marteau ou BRH ≤ 12 cm, aciers coupés. Évacuation non comprise.", "m²", 44.5, 10, 28.8, 4, 0.6, ["demolisseur", "terrassier", "macon"]],
    ["GO-DEM-107", "Sciage béton au disque ép. ≤ 20 cm", "Découpe à l'eau, mesurée au mètre de trait de scie, disque compris.", "ml", 61, 10, 33, 12, 0.6, ["demolisseur", "macon", "constructeur-beton-arme"]],
    ["GO-DEM-108", "Carottage béton Ø 100 à 150 mm ép. ≤ 30 cm", "Carottage à l'eau pour passage de gaine ou réseau, protection incluse.", "U", 79.5, 10, 44, 15, 0.8, ["demolisseur", "macon", "constructeur-beton-arme"]],
    ["GO-DEM-109", "Curage intérieur complet (au m² de plancher)", "Dépose cloisons, doublages, plafonds et revêtements, tri sur site. Amiante et évacuation exclus.", "m²", 56.5, 10, 42, 0, 1, ["demolisseur", "macon"]],
    ["GO-DEM-110", "Piquage d'enduit ciment de façade jusqu'au support", "Piquage manuel ou mécanique, brossage du support. Échafaudage et évacuation exclus.", "m²", 37, 10, 27, 0.5, 0.6, ["demolisseur", "facadier-ravaleur", "macon"]],
    ["GO-DEM-111", "Démolition d'annexe légère ≤ 20 m² (abri, appentis)", "Démolition complète hors dalle, tri et évacuation en benne incluse. Amiante exclu.", "forfait", 897, 10, 540, 150, 12, ["demolisseur"]],
    ["GO-DEM-112", "Démolition mécanique de maison individuelle", "Démolition à la pelle avec tri, au m² de plancher. Désamiantage, évacuation et fondations exclus.", "m²", 46, 20, 27.5, 8, 0.5, ["demolisseur"]],
    ["GO-DEM-113", "Évacuation manuelle de gravats en sacs (étage)", "Descente par escalier sans ascenseur et chargement en benne ou camion.", "m³", 170, 10, 126, 0, 3, ["demolisseur", "macon"]],
    ["GO-DEM-114", "Dépose d'ancienne étanchéité multicouche", "Arrachage, grattage et nettoyage du support. Évacuation non comprise.", "m²", 19.5, 10, 14.4, 0, 0.3, ["demolisseur", "etancheur"]],
  ],
  "Façade": [
    ["GO-RAV-101", "Échafaudage de pied (montage, démontage, 4 semaines)", "Échafaudage conforme avec garde-corps et filets, location 4 semaines incluse. Au m² de façade.", "m²", 28.5, 10, 15.75, 6, 0.35, ["facadier-ravaleur", "macon", "etancheur", "charpentier-bois"]],
    ["GO-RAV-102", "Nacelle articulée 12 m (location jour sans opérateur)", "Location seule avec livraison. Opérateur facturé en régie.", "jour", 287.5, 20, 0, 230, 0, ["facadier-ravaleur", "etancheur", "charpentier-metallique"]],
    ["GO-RAV-103", "Nettoyage de façade haute pression eau froide", "Lavage au nettoyeur HP, rinçage et protection des abords. Échafaudage non compris.", "m²", 7.5, 10, 5.4, 0.5, 0.12, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-104", "Hydrogommage de façade pierre ou brique", "Projection basse pression d'abrasif fin et eau, rinçage, abrasif compris.", "m²", 32, 10, 20.8, 4, 0.4, ["facadier-ravaleur"]],
    ["GO-RAV-105", "Traitement de fissures ≤ 2 mm (ouverture, mastic, entoilage)", "Ouverture en V, mastic acrylique et bande d'armature avant revêtement.", "ml", 25.5, 10, 16.8, 3, 0.35, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-106", "Agrafage de fissure structurelle (agrafes acier et résine)", "Saignées transversales, agrafes inox scellées résine, rebouchage. Diagnostic exclu.", "ml", 113.5, 10, 66, 18, 1.2, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-107", "Peinture de façade pliolite, impression et 2 couches", "Brossage, fixateur et deux couches de peinture façade sur support sain.", "m²", 24, 10, 13.5, 5, 0.3, ["facadier-ravaleur"]],
    ["GO-RAV-108", "Revêtement d'imperméabilité I3 sur façade fissurée", "Système armé avec impression, couche de fond et finition. Traitement des fissures inclus.", "m²", 47, 10, 24, 12, 0.5, ["facadier-ravaleur"]],
    ["GO-RAV-109", "Enduit monocouche gratté sur brique ou béton cellulaire, armé", "Enduit projeté avec trame en points singuliers, finition grattée. Échafaudage non compris.", "m²", 51, 10, 26.4, 13, 0.55, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-110", "Enduit traditionnel trois couches à la chaux", "Gobetis, corps d'enduit et finition talochée ou lissée sur maçonnerie ancienne.", "m²", 89.5, 10, 60, 9, 1.2, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-111", "Rejointoiement de briques apparentes", "Dégarnissage des joints, rejointoiement au mortier bâtard teinté et brossage.", "m²", 91.5, 10, 67.2, 3, 1.4, ["facadier-ravaleur", "macon"]],
    ["GO-RAV-112", "Hydrofuge incolore de façade, deux passes", "Imprégnation hydrofuge et oléofuge sur pierre, brique ou enduit sain.", "m²", 8, 10, 3.6, 2.5, 0.08, ["facadier-ravaleur"]],
    ["GO-RAV-113", "Réparation ponctuelle d'enduit de façade ≤ 1 m²", "Piquage, reprise en enduit et raccord de finition au plus proche de l'existant.", "U", 106.5, 10, 72, 10, 1.5, ["facadier-ravaleur", "macon"]],
  ],
  "Étanchéité": [
    ["GO-ETA-101", "Étanchéité bicouche bitume SBS sous protection gravillons", "Pare-vapeur hors lot, EIF, deux couches soudées et gravillons 5 cm. Relevés comptés à part.", "m²", 55.5, 10, 24.75, 18, 0.45, ["etancheur"]],
    ["GO-ETA-102", "Étanchéité bicouche bitume SBS autoprotégée", "Primaire, sous-couche et chape autoprotégée ardoisée soudées. Relevés comptés à part.", "m²", 63, 10, 27.5, 21, 0.5, ["etancheur"]],
    ["GO-ETA-103", "Membrane EPDM monocouche collée (≤ 50 m²)", "Membrane d'un seul tenant collée sur support sain, angles préformés. Relevés à part.", "m²", 64.5, 10, 27.5, 22, 0.5, ["etancheur"]],
    ["GO-ETA-104", "Membrane PVC-P fixée mécaniquement", "Membrane armée soudée à l'air chaud, fixations en rive et en partie courante.", "m²", 47, 10, 19.25, 17, 0.35, ["etancheur"]],
    ["GO-ETA-105", "Isolant PIR 120 mm sous étanchéité (R ≥ 4,5) et pare-vapeur", "Pare-vapeur bitumineux et panneaux PIR fixés. Revêtement d'étanchéité non compris.", "m²", 57, 5.5, 13.75, 30, 0.25, ["etancheur"]],
    ["GO-ETA-106", "Relevé d'étanchéité bitume h ≤ 50 cm avec bande de protection", "Équerre de renfort, relevé autoprotégé et bande solin ou profil.", "ml", 47.5, 10, 27.5, 9, 0.5, ["etancheur"]],
    ["GO-ETA-107", "Relevé EPDM avec profil de rive", "Relevé collé, angles préformés et profil aluminium de fixation.", "ml", 44, 10, 22, 12, 0.4, ["etancheur"]],
    ["GO-ETA-108", "Naissance d'eaux pluviales avec crapaudine", "Moignon et platine raccordés à l'étanchéité, crapaudine. Descente EP non comprise.", "U", 166, 10, 82.5, 45, 1.5, ["etancheur"]],
    ["GO-ETA-109", "Couvertine aluminium laqué sur acrotère", "Couvertine avec éclisses et pattes de fixation, pente vers l'intérieur.", "ml", 69, 10, 25, 28, 0.5, ["etancheur", "charpentier-metallique"]],
    ["GO-ETA-110", "Recherche de fuite et réparation ponctuelle de toiture-terrasse", "Inspection, localisation et réparation par pièce soudée ou collée ≤ 2 m².", "forfait", 378, 10, 220, 60, 4, ["etancheur"]],
    ["GO-ETA-111", "Étanchéité liquide résine PU sur balcon circulable", "Préparation, primaire, résine armée et finition antidérapante.", "m²", 86.5, 10, 38.5, 28, 0.7, ["etancheur"]],
    ["GO-ETA-112", "Système d'étanchéité sous carrelage (balcon, terrasse)", "Primaire et SPEC deux couches avec bandes d'angle. Carrelage non compris.", "m²", 41, 10, 17.5, 14, 0.35, ["etancheur", "macon"]],
    ["GO-ETA-113", "Cuvelage intérieur au mortier hydraulique (sous-sol)", "Préparation du support, mortier de cuvelage en deux passes et gorges d'angle.", "m²", 113.5, 10, 66, 18, 1.2, ["etancheur", "macon"]],
    ["GO-ETA-114", "Injection de résine sur fissure infiltrante", "Injecteurs, injection de résine PU ou époxy et arasement en paroi enterrée.", "ml", 128, 10, 60, 35, 1, ["etancheur", "constructeur-beton-arme"]],
    ["GO-ETA-115", "Membrane à excroissances contre mur enterré", "Membrane PEHD avec profil de finition haut, posée avant remblai.", "m²", 19, 10, 9.6, 5, 0.2, ["etancheur", "macon", "terrassier"]],
    ["GO-ETA-116", "Entretien annuel de toiture-terrasse", "Nettoyage des EP et crapaudines, enlèvement des végétaux, contrôle des relevés.", "forfait", 143, 10, 100, 10, 2, ["etancheur"]],
  ],
});
