import { defineCatalog } from "./define";

export const CATALOG_MENUISERIES_EXTERIEURES = defineCatalog("menuiseries-exterieures", {
  "Installation et interventions": [
    ["ME-INS-101", "Frais de déplacement chantier zone ≤ 30 km", "Aller-retour du véhicule équipé et temps de trajet du poseur, par jour d'intervention.", "forfait", 78, 10, 45, 15, 1],
    ["ME-INS-102", "Prise de cotes et métré sur site", "Relevé des dimensions et contraintes de pose avant commande. Déduit si la commande est passée.", "forfait", 107, 20, 82.5, 0, 1.5],
    ["ME-INS-103", "Main d'œuvre en régie, poseur qualifié", "Heure de travail effectif pour travaux non prévus au devis. Fournitures facturées en sus.", "h", 65, 10, 50, 0, 1],
    ["ME-INS-104", "Forfait petite intervention (≤ 1 h sur place)", "Déplacement, 1 h de main d'œuvre et petites fournitures courantes. Au-delà, régie horaire.", "forfait", 117, 10, 75, 15, 1.5],
    ["ME-INS-105", "Majoration intervention urgente nuit, week-end ou jour férié", "Supplément appliqué à l'intervention réalisée hors heures ouvrées, en sus du déplacement et du travail.", "forfait", 84, 10, 60, 0, 1],
    ["ME-INS-106", "Protection des sols et du mobilier pendant la pose", "Bâches et films de protection, aspiration et nettoyage de fin d'intervention.", "forfait", 78, 10, 45, 15, 1],
    ["ME-INS-107", "Enlèvement et recyclage d'une menuiserie ou d'un ouvrage déposé", "Évacuation en filière de recyclage (verre, PVC, alu, acier, bois), par élément déposé.", "U", 33, 10, 13.5, 12, 0.3],
    ["ME-INS-108", "Échafaudage roulant, location journée avec montage", "Échafaudage roulant jusqu'à 6 m de hauteur de travail, montage et démontage compris.", "jour", 150, 10, 45, 70, 1],
  ],
  "Fenêtres": [
    ["ME-FEN-101", "Fenêtre PVC 1 vantail 60 × 75, pose en rénovation", "Double vitrage Uw ≤ 1,3, pose sur dormant existant, habillages et calfeutrement compris.", "U", 372, 5.5, 96, 190, 2, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-102", "Fenêtre PVC 2 vantaux 100 × 125, pose en rénovation", "Double vitrage Uw ≤ 1,3, oscillo-battant sur un vantail, habillages et calfeutrement compris.", "U", 585, 5.5, 120, 330, 2.5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-103", "Fenêtre PVC 2 vantaux 100 × 125, dépose totale", "Dépose du dormant ancien, pose en tunnel ou en applique, reprise des tableaux. Peinture non comprise.", "U", 767, 5.5, 240, 350, 5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-104", "Fenêtre aluminium 2 vantaux 100 × 125 à rupture de pont thermique", "Fenêtre alu laquée Uw ≤ 1,4, pose en rénovation sur dormant existant, habillages compris.", "U", 1020, 5.5, 165, 620, 3, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-105", "Fenêtre bois 2 vantaux 100 × 125, pose en rénovation", "Fenêtre pin ou bois exotique lasuré, double vitrage Uw ≤ 1,4, habillages bois compris.", "U", 1105, 5.5, 150, 700, 3, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-106", "Fenêtre PVC 2 vantaux 100 × 125, pose en construction neuve", "Pose en applique intérieure avec isolation ou en tunnel, calfeutrement et fixations. Doublage non compris.", "U", 546, 20, 120, 300, 2.5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-107", "Plus-value fenêtre PVC teinte plaxée une face", "Supplément pour coloration plaxée extérieure. Prix par fenêtre jusqu'à 2 m².", "U", 117, 5.5, 0, 90, 0, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-108", "Plus-value vitrage feuilleté retardateur d'effraction 44.2", "Supplément pour vitrage de sécurité par fenêtre jusqu'à 2 m².", "U", 97.5, 5.5, 0, 75, 0, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-109", "Remplacement de double vitrage seul, jusqu'à 1 m²", "Dépose des parcloses, vitrage isolant neuf, calage et joints. Menuiserie conservée.", "U", 263, 10, 82.5, 120, 1.5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-110", "Entrée d'air hygroréglable avec mortaisage de la menuiserie", "Mortaisage du dormant ou de l'ouvrant et pose d'une entrée d'air avec auvent acoustique.", "U", 54.5, 10, 24, 18, 0.5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-111", "Calfeutrement de menuiserie existante au mastic", "Dégarnissage des anciens joints, fond de joint et mastic acrylique ou polyuréthane.", "ml", 11.5, 10, 6.75, 2, 0.15, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-FEN-112", "Dépannage de menuiserie (réglage, remplacement de crémone)", "Réglage des paumelles et de la fermeture, remplacement d'une crémone ou d'une poignée.", "forfait", 108, 10, 48, 35, 1, ["menuisier-pvc-alu", "poseur-fenetres", "serrurier"]],
  ],
  "Portes-fenêtres et baies": [
    ["ME-BAI-101", "Porte-fenêtre PVC 2 vantaux 120 × 215, pose en rénovation", "Double vitrage Uw ≤ 1,3, seuil alu, pose sur dormant existant, habillages compris.", "U", 894, 5.5, 168, 520, 3.5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-BAI-102", "Porte-fenêtre PVC 2 vantaux 120 × 215, dépose totale", "Dépose du bâti ancien, pose neuve, reprise des tableaux et du seuil. Peinture non comprise.", "U", 1076, 5.5, 288, 540, 6, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-BAI-103", "Baie coulissante aluminium 2 vantaux 240 × 215, rénovation", "Coulissant alu Uw ≤ 1,4, pose sur dormant existant, habillages et calfeutrement compris.", "U", 2502, 5.5, 275, 1650, 5, ["menuisier-pvc-alu", "poseur-fenetres", "verandaliste"]],
    ["ME-BAI-104", "Baie coulissante aluminium 2 vantaux 300 × 215, dépose totale", "Dépose de l'ancienne baie, pose en tunnel ou applique, reprise des tableaux et du seuil.", "U", 3562, 5.5, 440, 2300, 8, ["menuisier-pvc-alu", "poseur-fenetres", "verandaliste"]],
    ["ME-BAI-105", "Baie coulissante PVC 2 vantaux 240 × 215, rénovation", "Coulissant PVC renforcé Uw ≤ 1,3, pose sur dormant existant, habillages compris.", "U", 1711, 5.5, 216, 1100, 4.5, ["menuisier-pvc-alu", "poseur-fenetres", "verandaliste"]],
  ],
  "Portes d'entrée et de service": [
    ["ME-POR-101", "Porte d'entrée PVC isolante 90 × 215, pose en rénovation", "Porte Ud ≤ 1,7, serrure 3 points, pose sur dormant existant, habillages compris.", "U", 1614, 5.5, 192, 1050, 4, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-POR-102", "Porte d'entrée acier isolante 90 × 215, dépose totale", "Bloc-porte acier Ud ≤ 1,7, serrure 5 points, dépose du bâti ancien et reprise des tableaux.", "U", 1547, 5.5, 240, 950, 5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-POR-103", "Porte d'entrée aluminium avec tierce fixe 130 × 215", "Porte alu isolante Ud ≤ 1,7 avec semi-fixe vitré, pose en rénovation, habillages compris.", "U", 3738, 5.5, 275, 2600, 5, ["menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-POR-104", "Porte de service acier 80 × 200 sur local non chauffé", "Bloc-porte acier prélaqué, serrure 1 point, pose en applique ou en tableau.", "U", 733, 10, 144, 420, 3, ["menuisier-pvc-alu", "poseur-fenetres", "serrurier-metallier"]],
  ],
  "Volets roulants": [
    ["ME-VRO-101", "Volet roulant rénovation 100 × 125, manœuvre manuelle par sangle", "Coffre extérieur alu, lames alu isolées, coulisses avec joints. Pose en applique ou sous linteau.", "U", 392, 5.5, 72, 230, 1.5, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-VRO-102", "Volet roulant rénovation 100 × 125, motorisé filaire", "Moteur tubulaire avec inverseur filaire. Alimentation électrique jusqu'au coffre non comprise.", "U", 611, 5.5, 110, 360, 2, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-VRO-103", "Volet roulant solaire autonome 100 × 125", "Panneau photovoltaïque et batterie intégrés, commande radio. Aucun raccordement électrique.", "U", 819, 5.5, 110, 520, 2, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-VRO-104", "Volet roulant porte-fenêtre 120 × 215, motorisé radio", "Coffre rénovation alu, lames alu isolées, moteur radio et émetteur mural.", "U", 855, 5.5, 137.5, 520, 2.5, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-VRO-105", "Volet roulant baie 240 × 215, motorisé radio", "Grande largeur, lame finale renforcée, moteur radio avec détection d'obstacle.", "U", 1280, 5.5, 165, 820, 3, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-VRO-106", "Motorisation d'un volet roulant manuel existant", "Moteur radio adapté à l'axe, émetteur mural, suppression du treuil ou de la sangle.", "U", 390, 10, 110, 190, 2, ["poseur-volets-stores"]],
    ["ME-VRO-107", "Remplacement de moteur de volet roulant hors service", "Démontage du tablier, moteur équivalent, réglage des fins de course. Alimentation conservée.", "U", 315, 10, 82.5, 160, 1.5, ["poseur-volets-stores"]],
    ["ME-VRO-108", "Remplacement de sangle et d'enrouleur de volet roulant", "Ouverture du coffre, sangle et enrouleur neufs, essais de fonctionnement.", "U", 79.5, 10, 36, 25, 0.75, ["poseur-volets-stores"]],
    ["ME-VRO-109", "Dépannage de volet roulant bloqué", "Diagnostic, déblocage du tablier, remise en place des lames ou réglage moteur. Pièces en sus.", "forfait", 84.5, 10, 55, 10, 1, ["poseur-volets-stores"]],
  ],
  "Volets battants et persiennes": [
    ["ME-VBA-101", "Volets battants PVC 2 vantaux 100 × 125", "Volets PVC isolants avec pentures, gonds scellés ou chimiques et arrêts. Dépose des anciens en sus.", "U", 541, 5.5, 96, 320, 2, ["poseur-volets-stores", "menuisier-pvc-alu"]],
    ["ME-VBA-102", "Volets battants aluminium isolés 2 vantaux 100 × 125", "Volets alu à âme isolante, laquage au choix, gonds, pentures et arrêts compris.", "U", 801, 5.5, 96, 520, 2, ["poseur-volets-stores", "menuisier-pvc-alu"]],
    ["ME-VBA-103", "Persiennes repliables aluminium 100 × 125", "Persiennes en tableau à lames, pose sur cadre, laquage au choix.", "U", 780, 10, 120, 480, 2.5, ["poseur-volets-stores", "menuisier-pvc-alu", "serrurier-metallier"]],
    ["ME-VBA-104", "Motorisation de volets battants existants par bras articulés", "Bras motorisés radio en façade, réglage et programmation. Alimentation électrique non comprise.", "U", 1060, 10, 165, 650, 3, ["poseur-volets-stores"]],
    ["ME-VBA-105", "Dépose de volets battants existants et des gonds", "Dépose des vantaux, des gonds et des arrêts, rebouchage des scellements.", "U", 50.5, 10, 33.75, 5, 0.75, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
  ],
  "Stores et moustiquaires": [
    ["ME-STO-101", "Brise-soleil orientable aluminium motorisé 150 × 150", "Lames orientables, coulisses, coffre ou linteau, moteur radio. Alimentation électrique non comprise.", "U", 1644, 10, 165, 1100, 3, ["poseur-volets-stores"]],
    ["ME-STO-102", "Store extérieur toile screen à coulisses zip, motorisé 200 × 200", "Toile microperforée maintenue en coulisses, moteur radio. Alimentation électrique non comprise.", "U", 1284, 10, 137.5, 850, 2.5, ["poseur-volets-stores", "poseur-store-banne"]],
    ["ME-STO-103", "Store enrouleur intérieur occultant sur mesure", "Store sur mesure en tableau ou en applique, chaînette ou ressort, fixations comprises.", "U", 128, 10, 24, 75, 0.5, ["poseur-volets-stores"]],
    ["ME-STO-104", "Moustiquaire enroulable pour fenêtre", "Moustiquaire à rappel par ressort en coulisses alu, pose en tableau.", "U", 122, 10, 24, 70, 0.5, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
    ["ME-STO-105", "Moustiquaire plissée pour porte-fenêtre", "Moustiquaire plissée à seuil bas, coulissement latéral, pose en tableau.", "U", 242, 10, 36, 150, 0.75, ["poseur-volets-stores", "menuisier-pvc-alu", "poseur-fenetres"]],
  ],
  "Stores bannes": [
    ["ME-SBA-101", "Store banne coffre intégral motorisé radio 5 × 3 m", "Coffre alu, bras renforcés, toile acrylique, moteur radio. Alimentation électrique non comprise.", "U", 2395, 10, 192.5, 1650, 3.5, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-102", "Store banne coffre intégral manuel 4 × 3 m", "Coffre alu fermé, manœuvre par manivelle, toile acrylique, fixations murales.", "U", 1450, 10, 165, 950, 3, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-103", "Store banne monobloc manuel 3 × 2,5 m", "Store sans coffre sur barre carrée, manivelle, toile acrylique. Pose murale ou plafond.", "U", 702, 10, 120, 420, 2.5, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-104", "Plus-value automatisme capteur vent et soleil", "Capteur sans fil fixé en façade, réglage des seuils de repli et de descente.", "U", 192, 10, 27.5, 120, 0.5, ["poseur-store-banne", "poseur-volets-stores", "poseur-pergolas"]],
    ["ME-SBA-105", "Remplacement de toile de store banne jusqu'à 5 × 3 m", "Toile acrylique sur mesure, dépose de l'ancienne, réglage de l'inclinaison des bras.", "U", 689, 10, 110, 420, 2, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-106", "Motorisation d'un store banne manuel existant", "Moteur radio adapté au tube d'enroulement, émetteur, suppression du treuil.", "U", 481, 10, 110, 260, 2, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-107", "Fixations renforcées par scellement chimique sur support difficile", "Supplément pour pose sur brique creuse, isolation extérieure ou chevrons, entretoises comprises.", "forfait", 185, 10, 82.5, 60, 1.5, ["poseur-store-banne", "poseur-volets-stores", "poseur-pergolas"]],
    ["ME-SBA-108", "Dépose et repose de store banne (ravalement, isolation)", "Démontage, stockage sur site et remontage avec réglages. Supports neufs en sus.", "U", 200, 10, 144, 10, 3, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-109", "Entretien de store banne (toile, bras, réglages)", "Nettoyage de la toile, graissage des articulations, réglage d'inclinaison et des fins de course.", "forfait", 113, 10, 72, 15, 1.5, ["poseur-store-banne", "poseur-volets-stores"]],
    ["ME-SBA-110", "Dépannage de moteur ou d'automatisme de store", "Diagnostic, réglage des fins de course, réappairage des émetteurs. Pièces en sus.", "forfait", 91, 10, 55, 15, 1, ["poseur-store-banne", "poseur-volets-stores", "poseur-pergolas"]],
    ["ME-SBA-111", "Voile d'ombrage tendue sur mâts acier, jusqu'à 20 m²", "Voile en toile ombrage, mâts galvanisés scellés, tendeurs inox. Massifs béton compris.", "U", 744, 10, 192, 380, 4, ["poseur-store-banne", "poseur-pergolas"]],
  ],
  "Portes de garage": [
    ["ME-PGA-101", "Porte sectionnelle plafond isolée 240 × 200 motorisée", "Panneaux isolés 40 mm, rails plafond, moteur radio avec 2 émetteurs. Alimentation non comprise.", "U", 2178, 10, 275, 1400, 5, ["poseur-porte-garage"]],
    ["ME-PGA-102", "Porte sectionnelle plafond isolée 300 × 212 motorisée", "Grande largeur, panneaux isolés 40 mm, ressorts de torsion, moteur radio et 2 émetteurs.", "U", 2834, 10, 330, 1850, 6, ["poseur-porte-garage"]],
    ["ME-PGA-103", "Porte sectionnelle latérale motorisée 250 × 200", "Ouverture latérale sur rail au sol, panneaux isolés, motorisation et accès piéton partiel.", "U", 3159, 10, 330, 2100, 6, ["poseur-porte-garage"]],
    ["ME-PGA-104", "Porte basculante débordante acier 240 × 200 manuelle", "Tablier acier nervuré prélaqué, serrure, pose en tableau ou en applique.", "U", 842, 10, 168, 480, 3.5, ["poseur-porte-garage", "serrurier-metallier"]],
    ["ME-PGA-105", "Porte basculante acier 240 × 200 motorisée", "Tablier acier, moteur à rail plafond et 2 émetteurs. Alimentation électrique non comprise.", "U", 1336, 10, 247.5, 780, 4.5, ["poseur-porte-garage", "serrurier-metallier"]],
    ["ME-PGA-106", "Porte enroulable aluminium motorisée 240 × 200", "Lames alu isolées, coffre intérieur, moteur tubulaire radio avec détection d'obstacle.", "U", 1781, 10, 220, 1150, 4, ["poseur-porte-garage"]],
    ["ME-PGA-107", "Plus-value porte de service intégrée au tablier", "Portillon piéton intégré à la porte sectionnelle, seuil réduit et serrure.", "U", 916, 10, 55, 650, 1, ["poseur-porte-garage"]],
    ["ME-PGA-108", "Motorisation d'une porte de garage existante", "Moteur à rail plafond adapté à la porte, 2 émetteurs, réglages. Alimentation non comprise.", "U", 708, 10, 165, 380, 3, ["poseur-porte-garage"]],
    ["ME-PGA-109", "Remplacement des ressorts de torsion de porte sectionnelle", "Paire de ressorts aux dimensions, mise en tension et équilibrage du tablier.", "U", 338, 10, 110, 150, 2, ["poseur-porte-garage"]],
    ["ME-PGA-110", "Dépannage de porte de garage (réglage, fins de course)", "Diagnostic mécanique et électrique, réglages, déblocage. Pièces en sus.", "forfait", 91, 10, 55, 15, 1, ["poseur-porte-garage"]],
    ["ME-PGA-111", "Dépose d'une porte de garage existante", "Démontage de la porte et de ses rails ou contrepoids, rebouchage des fixations.", "U", 101, 10, 67.5, 10, 1.5, ["poseur-porte-garage", "serrurier-metallier"]],
  ],
  "Portails, clôtures et automatismes": [
    ["ME-PTL-101", "Portail battant aluminium 2 vantaux 3 m plein", "Portail alu laqué, gonds réglables, butée et serrure, pose sur piliers existants.", "U", 2568, 10, 275, 1700, 5, ["poseur-portails-clotures"]],
    ["ME-PTL-102", "Portail battant acier thermolaqué 2 vantaux 3,5 m", "Portail acier galvanisé thermolaqué ajouré ou semi-plein, pose sur piliers existants.", "U", 2048, 10, 275, 1300, 5, ["poseur-portails-clotures", "serrurier-metallier"]],
    ["ME-PTL-103", "Portail coulissant autoportant acier 4 m", "Portail sans rail au sol sur chariots, massif de fondation béton compris.", "U", 3952, 10, 440, 2600, 8, ["poseur-portails-clotures", "serrurier-metallier"]],
    ["ME-PTL-104", "Portillon aluminium 1 m assorti au portail", "Portillon alu laqué avec serrure et gâche, pose sur pilier ou poteau existant.", "U", 855, 10, 137.5, 520, 2.5, ["poseur-portails-clotures"]],
    ["ME-PTL-105", "Motorisation de portail battant à bras articulés", "Deux moteurs, carte électronique, 2 émetteurs, photocellules et feu. Alimentation non comprise.", "U", 962, 10, 220, 520, 4, ["poseur-portails-clotures", "serrurier-metallier"]],
    ["ME-PTL-106", "Motorisation de portail coulissant avec crémaillère", "Moteur sur socle béton, crémaillère, 2 émetteurs, photocellules. Alimentation non comprise.", "U", 910, 10, 220, 480, 4, ["poseur-portails-clotures", "serrurier-metallier"]],
    ["ME-PTL-107", "Clôture panneaux rigides H 1,53 m sur poteaux scellés", "Panneaux acier plastifiés, poteaux à scellement béton tous les 2,50 m, fixations comprises.", "ml", 84.5, 10, 27, 38, 0.6, ["poseur-portails-clotures"]],
    ["ME-PTL-108", "Clôture panneaux rigides H 1,73 m avec soubassement béton", "Panneaux acier plastifiés, plaques de soubassement 25 cm, poteaux à encoches scellés.", "ml", 122, 10, 36, 58, 0.8, ["poseur-portails-clotures"]],
    ["ME-PTL-109", "Clôture grillage simple torsion H 1,50 m", "Grillage plastifié, poteaux et jambes de force scellés, fils de tension.", "ml", 33, 10, 13.5, 12, 0.3, ["poseur-portails-clotures"]],
    ["ME-PTL-110", "Occultation par lamelles PVC sur panneaux rigides", "Lamelles PVC glissées dans les mailles, finition par profilé de fin.", "ml", 46, 10, 13.5, 22, 0.3, ["poseur-portails-clotures"]],
    ["ME-PTL-111", "Clôture aluminium à lames pleines H 1,80 m", "Lames alu emboîtées entre poteaux alu scellés, laquage au choix.", "ml", 333, 10, 66, 190, 1.2, ["poseur-portails-clotures"]],
    ["ME-PTL-112", "Dépose de clôture existante avec poteaux", "Dépose du grillage ou des panneaux, arrachage des poteaux, évacuation comprise.", "ml", 18.5, 10, 11.25, 3, 0.25, ["poseur-portails-clotures"]],
    ["ME-PTL-113", "Réparation et réglage de portail (gonds, alignement)", "Redressage, gonds ou roulettes neufs, réglage des butées et de la serrure.", "forfait", 182, 10, 110, 30, 2, ["poseur-portails-clotures", "serrurier-metallier", "ferronnier"]],
    ["ME-PTL-114", "Dépannage de motorisation de portail ou de porte", "Diagnostic, réglage des forces et fins de course, reprogrammation. Pièces en sus.", "forfait", 91, 10, 55, 15, 1, ["poseur-portails-clotures", "poseur-porte-garage"]],
    ["ME-PTL-115", "Photocellules et feu clignotant de sécurité", "Paire de photocellules et feu orange raccordés à l'automatisme existant.", "U", 169, 10, 55, 75, 1, ["poseur-portails-clotures", "poseur-porte-garage"]],
    ["ME-PTL-116", "Clavier à code radio pour automatisme", "Clavier extérieur sans fil appairé au récepteur existant, programmation des codes.", "U", 164, 10, 41.25, 85, 0.75, ["poseur-portails-clotures", "poseur-porte-garage", "serrurier"]],
    ["ME-PTL-117", "Télécommande supplémentaire programmée", "Émetteur compatible avec l'automatisme existant, appairage et essais.", "U", 63.5, 10, 13.75, 35, 0.25, ["poseur-portails-clotures", "poseur-porte-garage"]],
    ["ME-PTL-118", "Visiophone filaire avec commande d'ouverture", "Platine de rue et moniteur intérieur, câblage jusqu'à 25 m, liaison gâche ou automatisme.", "U", 552, 10, 165, 260, 3, ["poseur-portails-clotures", "serrurier"]],
    ["ME-PTL-119", "Contrat d'entretien annuel d'automatisme (portail ou garage)", "Visite de contrôle, réglages de sécurité, graissage et compte rendu. Pièces en sus.", "forfait", 120, 10, 82.5, 10, 1.5, ["poseur-portails-clotures", "poseur-porte-garage"]],
  ],
  "Vérandas": [
    ["ME-VER-101", "Véranda aluminium, toiture polycarbonate 32 mm", "Structure alu à rupture de pont thermique, coulissants vitrés, chéneau. Dalle support non comprise.", "m²", 1599, 20, 330, 900, 6, ["verandaliste"]],
    ["ME-VER-102", "Véranda aluminium, toiture panneaux sandwich isolés", "Structure alu RPT, toiture isolée avec plafond fini, coulissants vitrés. Dalle non comprise.", "m²", 1830, 20, 357.5, 1050, 6.5, ["verandaliste"]],
    ["ME-VER-103", "Véranda aluminium, toiture vitrée à contrôle solaire", "Toiture verre feuilleté isolant à contrôle solaire, structure alu RPT. Dalle non comprise.", "m²", 2126, 20, 385, 1250, 7, ["verandaliste"]],
    ["ME-VER-104", "Fermeture de loggia ou balcon en coulissants aluminium", "Coulissants alu vitrés entre murs et dalles existants, habillages et calfeutrement.", "m²", 800, 20, 165, 450, 3, ["verandaliste", "menuisier-pvc-alu"]],
    ["ME-VER-105", "Remplacement de toiture polycarbonate de véranda existante", "Dépose des anciennes plaques, polycarbonate 32 mm neuf, profils et joints.", "m²", 184, 10, 66, 75, 1.2, ["verandaliste"]],
    ["ME-VER-106", "Remplacement de toiture de véranda par panneaux isolés", "Dépose de la toiture existante, panneaux sandwich isolés, profils de jonction et finitions.", "m²", 224, 10, 77, 95, 1.4, ["verandaliste"]],
    ["ME-VER-107", "Store intérieur de toiture de véranda", "Store plissé ou enrouleur sous toiture, guidage par câbles ou coulisses.", "m²", 166, 10, 33, 95, 0.6, ["verandaliste", "poseur-volets-stores"]],
    ["ME-VER-108", "Store extérieur de toiture de véranda motorisé", "Store toile tendue sur coulisses au-dessus de la toiture, moteur radio.", "m²", 265, 10, 44, 160, 0.8, ["verandaliste", "poseur-volets-stores", "poseur-store-banne"]],
    ["ME-VER-109", "Remplacement de vitrage ou de joints de véranda", "Vitrage isolant aux dimensions ou réfection des joints d'étanchéité d'un module.", "U", 315, 10, 82.5, 160, 1.5, ["verandaliste", "menuisier-pvc-alu"]],
    ["ME-VER-110", "Nettoyage et révision de véranda", "Nettoyage toiture et chéneau, contrôle des joints et des coulissants, réglages.", "forfait", 220, 10, 144, 25, 3, ["verandaliste", "poseur-pergolas"]],
    ["ME-VER-111", "Carport aluminium 1 voiture, toiture polycarbonate", "Abri adossé ou autoportant 3 × 5 m, poteaux sur platines ou plots, gouttière intégrée.", "U", 4485, 20, 550, 2900, 10, ["verandaliste", "poseur-pergolas"]],
  ],
  "Pergolas": [
    ["ME-PER-101", "Pergola bioclimatique aluminium 4 × 3 m, lames motorisées", "Lames orientables, poteaux alu, évacuation des eaux intégrée, moteur radio. Alimentation non comprise.", "U", 10504, 10, 880, 7200, 16, ["poseur-pergolas", "verandaliste"]],
    ["ME-PER-102", "Pergola bioclimatique aluminium 6 × 4 m, lames motorisées", "Grande dimension avec poutre renforcée, lames orientables motorisées, gestion des eaux pluviales.", "U", 16523, 10, 1210, 11500, 22, ["poseur-pergolas", "verandaliste"]],
    ["ME-PER-103", "Pergola aluminium à toile rétractable motorisée 4 × 3 m", "Toile PVC sur chariots, poteaux alu, moteur radio. Alimentation électrique non comprise.", "U", 5655, 10, 550, 3800, 10, ["poseur-pergolas", "poseur-store-banne"]],
    ["ME-PER-104", "Pergola aluminium toiture polycarbonate fixe 4 × 3 m", "Structure alu adossée, plaques polycarbonate, gouttière et descente intégrées.", "U", 3705, 10, 550, 2300, 10, ["poseur-pergolas", "verandaliste"]],
    ["ME-PER-105", "Ancrage de poteau de pergola sur plot béton", "Fouille, plot béton armé avec platine ou tige filetée, par poteau.", "U", 176, 10, 90, 45, 2, ["poseur-pergolas", "verandaliste"]],
    ["ME-PER-106", "Store vertical zip latéral pour pergola, largeur 3 m", "Toile screen en coulisses, moteur radio. Alimentation électrique non comprise.", "U", 1378, 10, 110, 950, 2, ["poseur-pergolas", "poseur-store-banne", "poseur-volets-stores"]],
    ["ME-PER-107", "Panneaux coulissants vitrés latéraux pour pergola", "Vantaux en verre trempé sur rails haut et bas, sans montants verticaux.", "ml", 819, 10, 110, 520, 2, ["poseur-pergolas", "verandaliste"]],
    ["ME-PER-108", "Remplacement de toile de pergola rétractable", "Toile PVC sur mesure, remontage sur chariots et réglage de tension.", "m²", 94, 10, 27.5, 45, 0.5, ["poseur-pergolas", "poseur-store-banne"]],
    ["ME-PER-109", "Entretien de pergola bioclimatique", "Nettoyage des lames et gouttières, contrôle des joints, réglage du moteur.", "forfait", 205, 10, 137.5, 20, 2.5, ["poseur-pergolas"]],
    ["ME-PER-110", "Claustra aluminium brise-vue à lames", "Lames alu fixes horizontales entre poteaux scellés, hauteur 1,80 m.", "ml", 318, 10, 55, 190, 1, ["poseur-pergolas", "poseur-portails-clotures"]],
  ],
  "Serrurerie": [
    ["ME-SER-101", "Ouverture de porte claquée sans dégradation", "Ouverture fine sans destruction, contrôle du bon fonctionnement. Déplacement en sus.", "forfait", 61, 10, 45, 0, 0.75, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-102", "Ouverture de porte fermée à clé avec destruction du cylindre", "Perçage ou extraction du cylindre. Remplacement du cylindre facturé en sus.", "forfait", 94.5, 10, 60, 10, 1, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-103", "Remplacement de cylindre européen standard 30 × 30", "Cylindre laiton avec 3 clés, dépose de l'ancien et essais.", "U", 84.5, 10, 30, 35, 0.5, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-104", "Cylindre haute sécurité certifié A2P une étoile avec carte", "Cylindre anti-crochetage et anti-perçage, clés reproductibles sur carte de propriété.", "U", 195, 10, 30, 120, 0.5, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-105", "Cylindre haute sécurité certifié A2P trois étoiles", "Cylindre très haute résistance avec carte de propriété, protège-cylindre recommandé.", "U", 325, 10, 30, 220, 0.5, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-106", "Remplacement de serrure multipoints en applique 3 points", "Serrure 3 points avec cylindre, tringles et gâches, réglage sur porte existante.", "U", 455, 10, 90, 260, 1.5, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-107", "Remplacement de serrure multipoints encastrée", "Mécanisme encastré équivalent avec têtière, gâches et cylindre, réglage sur porte existante.", "U", 572, 10, 120, 320, 2, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-108", "Serrure en applique 1 point certifiée A2P", "Serrure de sûreté en applique avec cylindre et gâche, pose sur porte bois.", "U", 221, 10, 60, 110, 1, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-109", "Blindage de porte existante avec serrure 3 points A2P", "Tôle acier côté extérieur, cornières anti-pince, serrure 3 points et paumelles renforcées.", "U", 1365, 10, 300, 750, 5, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-110", "Cornière anti-pince et protège-cylindre", "Cornière acier sur l'ouvrant et rosace de protection du cylindre, fixation traversante.", "U", 136, 10, 45, 60, 0.75, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-111", "Mise en sécurité après effraction", "Fermeture provisoire, condamnation de l'accès ou pose d'un verrou temporaire. Réparation en sus.", "forfait", 234, 10, 120, 60, 2, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-112", "Dépannage de serrure grippée ou de gâche mal réglée", "Déblocage, lubrification, réglage de la gâche et des points de fermeture.", "forfait", 67.5, 10, 45, 5, 0.75, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-113", "Serrure connectée ou électronique sur porte existante", "Serrure motorisée ou à code adaptée au cylindre, paramétrage de l'application.", "U", 416, 10, 60, 260, 1, ["serrurier"]],
    ["ME-SER-114", "Gâche électrique sur porte ou portillon existant", "Encastrement de la gâche, raccordement à la commande existante, essais.", "U", 228, 10, 90, 85, 1.5, ["serrurier", "poseur-portails-clotures", "serrurier-metallier"]],
    ["ME-SER-115", "Ferme-porte hydraulique à bras compas", "Ferme-porte réglable en force et vitesse, pose et réglage sur porte existante.", "U", 169, 10, 55, 75, 1, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-116", "Barre anti-panique 1 point pour porte d'issue de secours", "Barre conforme aux issues de secours, pose et réglage. Local professionnel ou ERP.", "U", 377, 20, 110, 180, 2, ["serrurier", "serrurier-metallier"]],
    ["ME-SER-117", "Remplacement de poignée ou plaque de porte d'entrée", "Ensemble poignée sur plaque adapté à l'entraxe, fixation traversante.", "U", 94, 10, 27.5, 45, 0.5, ["serrurier", "menuisier-pvc-alu", "poseur-fenetres"]],
  ],
  "Métallerie": [
    ["ME-MET-101", "Garde-corps acier barreaudé thermolaqué", "Garde-corps acier galvanisé thermolaqué, fixation en nez de dalle ou sur dalle, conforme hauteur réglementaire.", "ml", 429, 10, 110, 220, 2, ["serrurier-metallier", "ferronnier"]],
    ["ME-MET-102", "Garde-corps aluminium et verre feuilleté", "Poteaux alu et remplissage verre feuilleté 44.2, main courante, fixation sur dalle.", "ml", 637, 10, 110, 380, 2, ["serrurier-metallier"]],
    ["ME-MET-103", "Garde-corps inox à câbles tendus", "Poteaux inox 316, câbles et tendeurs, main courante inox, fixation latérale ou sur dalle.", "ml", 481, 10, 110, 260, 2, ["serrurier-metallier"]],
    ["ME-MET-104", "Main courante murale acier ou inox", "Main courante Ø 42 sur supports muraux, embouts et fixations chimiques.", "ml", 128, 10, 44, 55, 0.8, ["serrurier-metallier", "ferronnier"]],
    ["ME-MET-105", "Barre d'appui de fenêtre en acier thermolaqué", "Barre de protection fixée en tableau, hauteur réglementaire, teinte au choix.", "U", 228, 10, 55, 120, 1, ["serrurier-metallier", "ferronnier"]],
    ["ME-MET-106", "Escalier métallique droit, limon central, marches bois", "Escalier sur mesure jusqu'à 14 marches, marches chêne, garde-corps non compris.", "U", 4784, 10, 880, 2800, 16, ["serrurier-metallier"]],
    ["ME-MET-107", "Escalier hélicoïdal acier Ø 1,60 m", "Escalier colimaçon sur fût central, marches tôle ou bois, garde-corps intégré.", "U", 4121, 10, 770, 2400, 14, ["serrurier-metallier"]],
    ["ME-MET-108", "Grille de défense de fenêtre en acier, 100 × 125", "Barreaudage acier plein scellé ou fixé par chevilles chimiques, thermolaquage au choix.", "U", 429, 10, 110, 220, 2, ["serrurier-metallier", "ferronnier", "serrurier"]],
    ["ME-MET-109", "Marquise d'entrée acier et verre feuilleté 150 × 90", "Structure acier thermolaquée, verre feuilleté, fixation par tirants ou consoles.", "U", 1131, 10, 220, 650, 4, ["serrurier-metallier", "ferronnier", "verandaliste"]],
    ["ME-MET-110", "Claustra ou brise-vue en acier découpé", "Panneaux acier découpés laser ou acier corten, poteaux scellés.", "ml", 419, 10, 82.5, 240, 1.5, ["serrurier-metallier", "ferronnier"]],
    ["ME-MET-111", "Soudure et réparation métallique sur site", "Intervention au poste à souder sur ouvrage existant, jusqu'à 2 h, consommables compris.", "forfait", 182, 10, 110, 30, 2, ["serrurier-metallier", "ferronnier"]],
    ["ME-MET-112", "Remise en peinture d'ouvrage métallique existant", "Brossage, antirouille et deux couches de laque glycéro ou spéciale métal.", "m²", 86, 10, 48, 18, 1, ["serrurier-metallier", "ferronnier"]],
  ],
  "Ferronnerie d'art": [
    ["ME-FER-101", "Garde-corps en fer forgé ornemental", "Barreaudage forgé avec volutes, rosaces ou pointes, fabrication atelier et scellement.", "ml", 832, 10, 360, 280, 6, ["ferronnier"]],
    ["ME-FER-102", "Rampe d'escalier en fer forgé avec main courante", "Rampe forgée sur mesure, main courante acier ou bois, fixation sur limon ou marches.", "ml", 676, 10, 300, 220, 5, ["ferronnier"]],
    ["ME-FER-103", "Balconnet de fenêtre en fer forgé", "Garde-corps de fenêtre décoratif forgé, scellement en tableau, finition peinture.", "U", 624, 10, 300, 180, 5, ["ferronnier"]],
    ["ME-FER-104", "Grille de défense décorative en fer forgé", "Grille forgée à motifs, scellée en tableau, finition antirouille et peinture.", "U", 598, 10, 240, 220, 4, ["ferronnier", "serrurier"]],
    ["ME-FER-105", "Portail battant en fer forgé 2 vantaux 3 m", "Portail forgé sur mesure, gonds à sceller, serrure et finition thermolaquée.", "U", 4940, 10, 1200, 2600, 20, ["ferronnier", "poseur-portails-clotures"]],
    ["ME-FER-106", "Portillon en fer forgé 1 m", "Portillon forgé assorti au portail, gonds, serrure et finition.", "U", 1599, 10, 480, 750, 8, ["ferronnier", "poseur-portails-clotures"]],
    ["ME-FER-107", "Grille de clôture en fer forgé sur muret", "Grille forgée sur muret existant, scellements et finition peinture.", "ml", 468, 10, 180, 180, 3, ["ferronnier", "poseur-portails-clotures"]],
    ["ME-FER-108", "Marquise d'entrée en fer forgé et verre, style ancien", "Structure forgée à consoles décoratives, verre feuilleté, scellement en façade.", "U", 3588, 10, 960, 1800, 16, ["ferronnier"]],
    ["ME-FER-109", "Restauration de ferronnerie ancienne", "Décapage, remplacement des éléments forgés manquants, soudure et finition. Au m² développé.", "m²", 390, 10, 240, 60, 4, ["ferronnier"]],
    ["ME-FER-110", "Élément forgé à l'unité (volute, pointe de lance, rosace)", "Pièce forgée à la main à l'identique ou sur modèle, fournie prête à souder.", "U", 97.5, 10, 60, 15, 1, ["ferronnier"]],
    ["ME-FER-111", "Heure de forge et façonnage en atelier", "Travail de forge, cintrage et ajustage en atelier, matière facturée en sus.", "h", 80.5, 10, 62, 0, 1, ["ferronnier"]],
  ],
});
