import { defineCatalog } from "./define";

export const CATALOG_PIERRE_PATRIMOINE = defineCatalog("pierre-patrimoine", {
  "Études, relevés et installation": [
    ["PP-ETU-101", "Relevé pierre à pierre et calepinage de façade", "Relevé des appareils, repérage des pierres à remplacer et plan coté de calepinage, au m² de parement.", "m²", 22.5, 20, 16.25, 0.5, 0.25, ["tailleur-pierre", "restaurateur-monuments-historiques", "macon-patrimoine"]],
    ["PP-ETU-102", "Étude préalable et diagnostic sanitaire de maçonnerie ancienne", "Visite, cartographie des altérations, hypothèses de causes et préconisations chiffrées. Analyses de laboratoire en sus.", "forfait", 1508, 20, 1120, 40, 16, ["restaurateur-monuments-historiques", "tailleur-pierre", "macon-patrimoine"]],
    ["PP-ETU-103", "Sondages et prélèvements de mortiers et enduits anciens pour analyse", "Fenêtres de sondage, prélèvements, analyse granulométrique et de liant, formulation d'un mortier compatible.", "forfait", 572, 20, 260, 180, 4, ["restaurateur-monuments-historiques", "macon-patrimoine"]],
    ["PP-ETU-104", "Constat d'état photographique avant intervention", "Reportage photo localisé, fiches d'état et repérage des éléments à déposer ou protéger.", "forfait", 266.5, 20, 195, 10, 3, ["restaurateur-monuments-historiques", "tailleur-pierre", "macon-patrimoine", "sculpteur-pierre"]],
    ["PP-ETU-105", "Épure, gabarit et panneaux de taille", "Tracé à l'échelle 1, panneaux et cerces pour une pièce ou une série de pièces identiques.", "U", 273, 10, 195, 15, 3, ["tailleur-pierre", "sculpteur-pierre"]],
    ["PP-ETU-106", "Maquette ou esquisse modelée d'ornement", "Modèle en terre ou plâtre soumis à validation avant taille. Prise de cotes comprise.", "U", 728, 20, 520, 40, 8, ["sculpteur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-ETU-107", "Rapport de fin de travaux et documentation de restauration", "Relevé des interventions, matériaux employés, photos avant/après, remis au maître d'ouvrage.", "forfait", 754, 20, 560, 20, 8, ["restaurateur-monuments-historiques"]],
    ["PP-ETU-108", "Installation de chantier patrimoine et protections", "Balisage, protection des sols, végétaux et éléments sculptés, stockage des pierres, repli et nettoyage.", "forfait", 767, 10, 440, 150, 8, ["macon-patrimoine", "tailleur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-ETU-109", "Échafaudage de façade, montage, location 1 mois et démontage", "Échafaudage de pied avec planchers, garde-corps et filet, au m² de façade. Autorisation de voirie en sus.", "m²", 21, 10, 10, 6, 0.2, ["macon-patrimoine", "tailleur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-ETU-110", "Régie compagnon tailleur de pierre ou maçon du patrimoine", "Heure de travail effectif d'un compagnon pour travaux non prévus au devis. Pierre et fournitures en sus.", "h", 83.5, 10, 62, 0, 1, ["tailleur-pierre", "macon-patrimoine", "restaurateur-monuments-historiques", "sculpteur-pierre", "marbrier"]],
  ],
  "Joints et enduits à la chaux": [
    ["PP-ENC-101", "Dégarnissage manuel des joints sur 3 cm", "Dégarnissage au crochet et à la massette sans épaufrer les arêtes, brossage et dépoussiérage.", "m²", 68, 10, 49.5, 1, 0.9, ["macon-patrimoine", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-ENC-102", "Rejointoiement de moellons à la chaux, joints beurrés brossés", "Humidification, garnissage chaux NHL et sable local, brossage au ressuage. Dégarnissage compté à part.", "m²", 92.5, 10, 60.5, 8, 1.1, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-103", "Rejointoiement de pierre de taille à joints fins", "Garnissage au fer de joints ≤ 8 mm au mortier de chaux teinté, au ml de joint.", "ml", 11, 10, 7.2, 0.5, 0.12, ["tailleur-pierre", "macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-104", "Piquage d'enduit ciment incompatible sur maçonnerie ancienne", "Piquage soigné jusqu'à la pierre, sans altérer les moellons, évacuation comprise.", "m²", 42, 10, 30, 1, 0.6, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-105", "Enduit à la chaux trois couches (gobetis, corps, finition)", "Chaux naturelle et sables locaux, finition talochée ou grattée. Échafaudage compté à part.", "m²", 123, 10, 77, 14, 1.4, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-106", "Enduit à pierre vue à la chaux", "Enduit affleurant les têtes de moellons, finition brossée ou éponge.", "m²", 95, 10, 60.5, 10, 1.1, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-107", "Enduit chaux-chanvre intérieur ép. 5 cm", "Projection ou application manuelle en deux passes sur maçonnerie ancienne, finition talochée. Isolation thermique d'appoint.", "m²", 137, 10, 71.5, 30, 1.3, ["macon-patrimoine"]],
    ["PP-ENC-108", "Badigeon de chaux teinté, deux passes", "Badigeon aux pigments naturels sur enduit ou pierre, application à la brosse.", "m²", 26.5, 10, 16.5, 3, 0.3, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-109", "Patine d'harmonisation sur pierre ou enduit neuf", "Eau forte ou patine à la chaux pour fondre les reprises dans l'existant.", "m²", 32.5, 10, 21, 3, 0.35, ["macon-patrimoine", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-ENC-110", "Encadrement de baie en enduit chaux lissé", "Bandeau de 15 à 20 cm dressé à la règle, finition lissée ou badigeonnée.", "ml", 48.5, 10, 33, 3, 0.6, ["macon-patrimoine"]],
    ["PP-ENC-111", "Rocaillage et calage de maçonnerie de moellons", "Calage des moellons instables par éclats de pierre et mortier de chaux avant rejointoiement.", "m²", 67.5, 10, 44, 6, 0.8, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-ENC-112", "Injection de coulis de chaux dans maçonnerie fissurée ou creuse", "Forages, injecteurs, coulis de chaux hydraulique à basse pression et ragréage des orifices.", "ml", 98.5, 10, 58, 15, 1, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
  ],
  "Restauration de pierre de taille": [
    ["PP-RES-101", "Reprise de pierre en tiroir, bloc ≤ 0,05 m³", "Dépose de la pierre altérée, taille d'une pierre neuve de même nature, pose au mortier de chaux et calage.", "U", 748, 10, 434, 120, 7, ["tailleur-pierre", "restaurateur-monuments-historiques", "macon-patrimoine"]],
    ["PP-RES-102", "Reprise de pierre en tiroir au m³ (pièces moulurées ou grandes)", "Taille en atelier, dépose, pose avec goujons inox si nécessaire et rejointoiement.", "m³", 6786, 10, 3720, 1500, 60, ["tailleur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-RES-103", "Bouchon ou placage de pierre ≤ 4 dm²", "Entaille au droit de la lacune, bouchon taillé de même pierre, collage et ajustage.", "U", 305, 10, 186, 40, 3, ["tailleur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-RES-104", "Ragréage de pierre au mortier de restauration", "Purge, goujonnage si nécessaire, mortier teinté monté en couches et retaillé, au m² de surface ragréée.", "m²", 312, 10, 186, 45, 3, ["tailleur-pierre", "restaurateur-monuments-historiques", "macon-patrimoine", "sculpteur-pierre"]],
    ["PP-RES-105", "Ragréage ponctuel d'éclat ou d'épaufrure ≤ 1 dm²", "Purge, mortier minéral teinté, mise en forme et finition au rifloir.", "U", 59, 10, 37.2, 5, 0.6, ["tailleur-pierre", "restaurateur-monuments-historiques", "macon-patrimoine", "sculpteur-pierre"]],
    ["PP-RES-106", "Consolidation de pierre par imprégnation au silicate d'éthyle", "Application jusqu'à refus sur pierre sèche, protection pendant la polymérisation.", "m²", 60, 10, 24.8, 18, 0.4, ["restaurateur-monuments-historiques", "tailleur-pierre", "sculpteur-pierre"]],
    ["PP-RES-107", "Dessalement de parement par compresses", "Pose de compresses de pulpe de cellulose, retrait après séchage, deux cycles.", "m²", 84, 10, 48, 12, 0.8, ["restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-RES-108", "Nettoyage de façade pierre par micro-gommage", "Projection basse pression d'abrasif fin, protections des menuiseries et récupération des résidus.", "m²", 35.5, 10, 19.25, 6, 0.35, ["tailleur-pierre", "macon-patrimoine", "restaurateur-monuments-historiques", "marbrier"]],
    ["PP-RES-109", "Nettoyage de pierre par nébulisation d'eau", "Brumisation prolongée et brossage doux pour dissoudre les croûtes, gestion des eaux.", "m²", 25, 10, 15, 3, 0.3, ["macon-patrimoine", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-RES-110", "Nettoyage laser d'éléments sculptés", "Ablation laser des encrassements sur ornements fragiles, au temps passé.", "h", 128, 20, 75, 20, 1, ["restaurateur-monuments-historiques", "sculpteur-pierre"]],
    ["PP-RES-111", "Traitement biocide et brossage des mousses et lichens", "Pulvérisation biocide, temps d'action et brossage doux, rinçage.", "m²", 14.5, 10, 7.5, 3, 0.15, ["macon-patrimoine", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-RES-112", "Ravalement par retaille du parement", "Retaille de 1 à 2 cm à la gradine ou à la boucharde, reprise des arêtes.", "m²", 216, 10, 155, 5, 2.5, ["tailleur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-RES-113", "Agrafage ou goujonnage inox de pierre fissurée", "Forages, goujons ou agrafes inox scellés à la résine ou au mortier, ragréage des orifices.", "U", 146, 10, 93, 15, 1.5, ["tailleur-pierre", "restaurateur-monuments-historiques", "sculpteur-pierre", "macon-patrimoine"]],
    ["PP-RES-114", "Remplacement de corniche ou bandeau mouluré en pierre", "Dépose, taille au profil relevé, pose avec goujons et pente d'écoulement.", "ml", 999, 10, 520, 220, 8, ["tailleur-pierre", "restaurateur-monuments-historiques", "sculpteur-pierre"]],
    ["PP-RES-115", "Restauration de remplage ou meneau de baie ancienne", "Dépose des parties instables, taille des éléments neufs, remontage. Vitraux non compris.", "U", 4420, 20, 2800, 600, 40, ["restaurateur-monuments-historiques", "tailleur-pierre"]],
  ],
  "Ouvrages en pierre": [
    ["PP-OUV-101", "Encadrement de baie en pierre massive ≤ 1,20 × 2,15 m", "Jambages, linteau et appui taillés, pose au mortier de chaux avec feuillure. Ouverture du mur comptée à part.", "U", 3302, 10, 1440, 1100, 24, ["tailleur-pierre", "macon-patrimoine"]],
    ["PP-OUV-102", "Linteau en pierre massive ≤ 1,40 m", "Pierre taillée sur cinq faces, pose sur appuis de 20 cm. Étaiement de l'ouverture compris.", "U", 754, 10, 300, 280, 5, ["tailleur-pierre", "macon-patrimoine"]],
    ["PP-OUV-103", "Appui de fenêtre en pierre massive avec rejingot ≤ 1,20 m", "Pente, rejingot et goutte d'eau taillés, pose au mortier. Dépose de l'ancien appui comprise.", "U", 460, 10, 174, 180, 3, ["tailleur-pierre", "macon-patrimoine", "marbrier"]],
    ["PP-OUV-104", "Seuil de porte en pierre massive ≤ 1 m", "Seuil taillé avec feuillure, pose au mortier sur support préparé.", "U", 396.5, 10, 145, 160, 2.5, ["tailleur-pierre", "macon-patrimoine", "marbrier"]],
    ["PP-OUV-105", "Marche d'escalier en pierre massive ≤ 1,20 m", "Marche taillée ou adoucie, nez arrondi, scellement dans les maçonneries.", "U", 525, 10, 174, 230, 3, ["tailleur-pierre", "macon-patrimoine", "marbrier"]],
    ["PP-OUV-106", "Chaînage d'angle en pierre de taille", "Harpes alternées taillées et posées au mortier de chaux, au ml de hauteur.", "ml", 637, 10, 240, 250, 4, ["tailleur-pierre", "macon-patrimoine"]],
    ["PP-OUV-107", "Chaperon ou couvertine de mur en pierre", "Pierre de couronnement à double pente avec larmier, posée au mortier.", "ml", 149.5, 10, 55, 60, 1, ["tailleur-pierre", "macon-patrimoine"]],
    ["PP-OUV-108", "Pilier de portail en pierre de taille h ≤ 2 m", "Assises taillées, chapeau mouluré, gonds scellés. Fondation non comprise.", "U", 1560, 10, 600, 600, 10, ["tailleur-pierre", "macon-patrimoine"]],
    ["PP-OUV-109", "Dallage extérieur en pierre naturelle sur chape", "Dalles calibrées posées au mortier, joints à la chaux ou au mortier. Chape comptée à part.", "m²", 178.5, 10, 62.4, 75, 1.2, ["macon-patrimoine", "tailleur-pierre", "marbrier"]],
    ["PP-OUV-110", "Dépose soignée et repose de dallage ancien", "Dépose numérotée, nettoyage, forme refaite et repose avec complément de dalles de réemploi.", "m²", 182, 10, 110, 25, 2, ["macon-patrimoine", "tailleur-pierre"]],
    ["PP-OUV-111", "Pavage en pavés de grès ou granit sur lit de sable stabilisé", "Pavés neufs ou de réemploi, joints sablés ou à la chaux. Terrassement non compris.", "m²", 169, 10, 70, 60, 1.4, ["macon-patrimoine", "tailleur-pierre"]],
    ["PP-OUV-112", "Mur en pierres sèches h ≤ 1 m", "Fondation, montage à sec avec boutisses et fruit, couronnement, au m² de parement vu.", "m²", 335, 10, 208, 40, 4, ["macon-patrimoine"]],
    ["PP-OUV-113", "Mur en moellons hourdés à la chaux", "Montage double parement avec boutisses, mortier de chaux. Pierre fournie ou de réemploi.", "m²", 261.5, 10, 156, 45, 3, ["macon-patrimoine"]],
    ["PP-OUV-114", "Remontage de mur en pierre effondré avec réemploi", "Dégagement, tri des pierres, remontage à l'identique et rejointoiement.", "m²", 272.5, 10, 182, 20, 3.5, ["macon-patrimoine", "restaurateur-monuments-historiques"]],
    ["PP-OUV-115", "Cheminée en pierre à foyer ouvert, fournie posée", "Jambages, linteau et tablette taillés, contrecœur et âtre. Conduit de fumée non compris.", "forfait", 4758, 10, 1860, 1800, 30, ["tailleur-pierre", "marbrier", "sculpteur-pierre"]],
    ["PP-OUV-116", "Restauration de cheminée ancienne en pierre", "Dépose partielle, ragréages, collages, nettoyage et remontage. Ramonage et tubage exclus.", "forfait", 1334, 10, 868, 120, 14, ["tailleur-pierre", "marbrier", "restaurateur-monuments-historiques", "sculpteur-pierre"]],
  ],
  "Marbrerie de décoration": [
    ["PP-MAR-101", "Relevé et gabarit sur site pour ouvrage de marbrerie", "Prise de cotes ou gabarit, vérification des aplombs et des réservations avant débit.", "forfait", 118, 10, 82.5, 5, 1.5, ["marbrier"]],
    ["PP-MAR-102", "Plan de travail granit ép. 3 cm poli, profondeur 62 cm", "Débit, chants polis, transport et pose sur meubles. Découpes comptées à part.", "ml", 445, 10, 82.5, 260, 1.5, ["marbrier"]],
    ["PP-MAR-103", "Plan de travail quartz reconstitué ép. 2 cm, profondeur 62 cm", "Débit, chants polis, transport et pose collée. Découpes comptées à part.", "ml", 399, 10, 77, 230, 1.4, ["marbrier"]],
    ["PP-MAR-104", "Découpe d'évier sous plan avec chants polis", "Découpe à la commande numérique ou au disque, polissage et collage de l'évier.", "U", 106.5, 10, 66, 10, 1.2, ["marbrier"]],
    ["PP-MAR-105", "Découpe de plaque de cuisson ou d'encastré", "Découpe aux cotes de l'appareil, renforts si nécessaire.", "U", 53, 10, 33, 5, 0.6, ["marbrier"]],
    ["PP-MAR-106", "Crédence en pierre naturelle ép. 2 cm", "Débit, découpes de prises, pose collée et joints silicone.", "m²", 320, 10, 66, 180, 1.2, ["marbrier"]],
    ["PP-MAR-107", "Plan vasque en marbre avec découpe, salle de bains", "Plan ép. 3 cm, dosseret, découpe vasque et percements robinetterie, pose sur consoles ou meuble.", "ml", 471, 10, 82.5, 280, 1.5, ["marbrier"]],
    ["PP-MAR-108", "Vasque taillée dans la masse", "Vasque monobloc en pierre ou marbre, bonde et évacuation. Robinetterie non comprise.", "U", 923, 10, 360, 350, 6, ["marbrier", "tailleur-pierre"]],
    ["PP-MAR-109", "Habillage mural en marbre agrafé ou collé", "Plaques ép. 2 cm, agrafes inox ou colle adaptée, joints fins.", "m²", 289, 10, 82.5, 140, 1.5, ["marbrier"]],
    ["PP-MAR-110", "Habillage de marche et contremarche en marbre", "Marche ép. 3 cm avec nez poli et contremarche ép. 2 cm, collées sur support béton.", "U", 250, 10, 82.5, 110, 1.5, ["marbrier"]],
    ["PP-MAR-111", "Sol en marbre poli posé collé", "Dalles calibrées, pose collée sur chape, joints fins. Chape non comprise.", "m²", 236, 10, 71.5, 110, 1.3, ["marbrier"]],
    ["PP-MAR-112", "Tablette de fenêtre en marbre", "Tablette ép. 2 cm, chants polis, pose collée.", "ml", 121, 10, 33, 60, 0.6, ["marbrier"]],
    ["PP-MAR-113", "Ponçage et cristallisation de sol en marbre", "Ponçage aux grains successifs, rebouchage et cristallisation.", "m²", 30, 10, 17.5, 4, 0.35, ["marbrier", "tailleur-pierre"]],
    ["PP-MAR-114", "Restauration de plateau ou tablette en marbre ancien", "Collage des cassures, rebouchage teinté et repolissage.", "U", 270, 10, 180, 20, 3, ["marbrier", "restaurateur-monuments-historiques"]],
    ["PP-MAR-115", "Traitement oléofuge et hydrofuge anti-taches", "Application d'un imperméabilisant sur pierre ou marbre, deux passes.", "m²", 22.5, 10, 10, 6, 0.2, ["marbrier"]],
  ],
  "Funéraire": [
    ["PP-FUN-101", "Monument funéraire granit, une place, fourni posé", "Monument standard avec tombale, stèle et semelle, transport et pose. Gravure comptée à part.", "U", 4238, 20, 660, 2600, 12, ["marbrier"]],
    ["PP-FUN-102", "Monument funéraire granit, deux places, fourni posé", "Monument double avec tombale, stèle et semelle, transport et pose. Gravure comptée à part.", "U", 5941, 20, 770, 3800, 14, ["marbrier"]],
    ["PP-FUN-103", "Caveau béton deux places", "Terrassement, caveau préfabriqué, mise à niveau et dalle de fermeture.", "U", 2901.5, 20, 832, 1400, 16, ["marbrier"]],
    ["PP-FUN-104", "Ouverture et fermeture de caveau", "Dépose de la tombale, ouverture, refermeture et nettoyage.", "U", 223, 20, 150, 15, 3, ["marbrier"]],
    ["PP-FUN-105", "Gravure de lettre en creux sur granit", "Gravure par lettre, peinture ou ton pierre. Hauteur 3 à 5 cm.", "U", 14, 20, 9, 1, 0.15, ["marbrier", "sculpteur-pierre", "tailleur-pierre"]],
    ["PP-FUN-106", "Gravure de lettre dorée à la feuille", "Gravure en creux et dorure à la feuille d'or, par lettre.", "U", 25, 20, 15, 3, 0.25, ["marbrier", "sculpteur-pierre"]],
    ["PP-FUN-107", "Gravure de motif décoratif ou emblème", "Motif gravé ou sablé d'après modèle fourni ou catalogue.", "U", 182, 20, 120, 10, 2, ["marbrier", "sculpteur-pierre", "tailleur-pierre"]],
    ["PP-FUN-108", "Plaque funéraire gravée fournie posée", "Plaque granit ou marbre jusqu'à 30 lettres, fixation sur monument.", "U", 196, 20, 55, 90, 1, ["marbrier"]],
    ["PP-FUN-109", "Nettoyage et rénovation de monument funéraire", "Nettoyage, démoussage, rejointoiement et ravivage des gravures.", "U", 310.5, 20, 200, 30, 4, ["marbrier", "tailleur-pierre"]],
    ["PP-FUN-110", "Redressement et remise à niveau de monument", "Dépose, reprise de la fondation, repose et calage.", "U", 475, 20, 312, 40, 6, ["marbrier"]],
    ["PP-FUN-111", "Restauration de tombe ancienne en pierre", "Collages, goujonnages, ragréages et nettoyage d'un monument ancien.", "U", 1541.5, 20, 992, 150, 16, ["tailleur-pierre", "restaurateur-monuments-historiques", "sculpteur-pierre", "marbrier"]],
  ],
  "Sculpture et ornement": [
    ["PP-SCU-101", "Sculpture de modillon ou console en pierre", "Taille d'après modèle ou relevé, pierre fournie, pose comprise.", "U", 1741.5, 10, 1170, 120, 18, ["sculpteur-pierre", "tailleur-pierre"]],
    ["PP-SCU-102", "Restitution de chapiteau sculpté", "Taille d'après relevé et maquette validée, pierre de même nature, pose comprise.", "U", 7800, 20, 5600, 400, 80, ["sculpteur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-SCU-103", "Bas-relief armorié ou décoratif", "Sculpture en bas-relief d'après dessin validé, dimensions ≤ 60 × 60 cm.", "U", 3796, 20, 2720, 200, 40, ["sculpteur-pierre"]],
    ["PP-SCU-104", "Moulure taillée en pierre", "Taille au profil d'après gabarit, ajustage et pose.", "ml", 416, 10, 248, 60, 4, ["sculpteur-pierre", "tailleur-pierre"]],
    ["PP-SCU-105", "Fleuron, pinacle ou épi de faîtage en pierre", "Taille d'après relevé ou modèle, goujonnage et pose.", "U", 2912, 20, 2040, 200, 30, ["sculpteur-pierre", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-SCU-106", "Restauration d'ornement par ragréage modelé", "Reconstitution des parties manquantes au mortier minéral modelé et retaillé.", "U", 580.5, 10, 390, 40, 6, ["sculpteur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-SCU-107", "Recollage de fragment sculpté avec goujon", "Nettoyage des cassures, goujon inox ou fibre et collage réversible.", "U", 218.5, 10, 136, 20, 2, ["sculpteur-pierre", "restaurateur-monuments-historiques", "tailleur-pierre"]],
    ["PP-SCU-108", "Moulage silicone d'ornement existant", "Prise d'empreinte en élastomère avec chape, sans altération de l'original.", "U", 910, 20, 520, 180, 8, ["sculpteur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-SCU-109", "Tirage en pierre reconstituée d'après moule", "Coulage, démoulage et patine d'un tirage à partir d'un moule existant.", "U", 324, 10, 180, 60, 3, ["sculpteur-pierre", "restaurateur-monuments-historiques"]],
    ["PP-SCU-110", "Lettre sculptée en relief ou inscription monumentale", "Lettre taillée en relief ou en creux profond, hauteur 8 à 15 cm.", "U", 138.5, 20, 97.5, 5, 1.5, ["sculpteur-pierre", "tailleur-pierre"]],
    ["PP-SCU-111", "Statue en ronde-bosse taille directe h ≤ 1 m", "Création originale d'après esquisse validée, pierre fournie. Socle et pose comptés à part.", "U", 12090, 20, 8400, 900, 120, ["sculpteur-pierre"]],
  ],
});
