import { defineCatalog } from "./define";

export const CATALOG_SECOND_OEUVRE = defineCatalog("second-oeuvre", {
  "Installation et généralités": [
    ["SO-GEN-101", "Frais de déplacement chantier zone ≤ 30 km", "Aller-retour véhicule utilitaire et temps de trajet, par jour d'intervention.", "forfait", 63.5, 10, 33.75, 15, 0.75],
    ["SO-GEN-102", "Protection des sols, menuiseries et mobilier conservés", "Bâches, carton ou film adhésif sur sols, escaliers et meubles, retrait en fin de chantier.", "m²", 7.5, 10, 3.6, 2, 0.08],
    ["SO-GEN-103", "Main d'œuvre en régie, ouvrier qualifié", "Heure de travail effectif pour travaux non prévus au devis. Fournitures facturées en sus.", "h", 61, 10, 45, 0, 1],
    ["SO-GEN-104", "Main d'œuvre en régie, compagnon / chef d'équipe", "Heure de travail d'un compagnon confirmé. Fournitures et location de matériel en sus.", "h", 74, 10, 55, 0, 1],
    ["SO-GEN-105", "Forfait petite intervention (≤ 2 h sur place)", "Déplacement, 2 h de main d'œuvre et petites fournitures courantes. Au-delà, régie horaire.", "forfait", 142, 10, 90, 15, 2],
    ["SO-GEN-106", "Évacuation des déchets de chantier en déchetterie (≤ 1 m³)", "Ensachage, chargement, transport et redevance de dépôt en déchetterie professionnelle.", "forfait", 146, 10, 67.5, 45, 1.5],
    ["SO-GEN-107", "Nettoyage de fin de chantier (pièces traitées)", "Aspiration, dépoussiérage et lavage des sols et vitres des pièces concernées par les travaux.", "m²", 4, 10, 2.4, 0.5, 0.06],
    ["SO-GEN-108", "Location échafaudage roulant intérieur (semaine)", "Tour roulante h ≤ 6 m, livraison, montage et démontage compris.", "forfait", 240.5, 10, 90, 95, 2],
  ],
  "Plâtrerie et plaquisterie": [
    ["SO-PLA-101", "Cloison BA13 hydro sur ossature 72/48, laine 45 mm", "Plaques H1 sur rails et montants, isolant, bandes et joints. Traitement SPEC et faïence non compris.", "m²", 72.5, 10, 33.75, 22, 0.75, ["plaquiste", "platrier-plaquiste", "poseur-isolation"]],
    ["SO-PLA-102", "Cloison distributive 98/48 double peau 2 × BA13, laine 45 mm", "Deux plaques par face, montants 48 entraxe 60, isolant et joints. Affaiblissement ≈ 45 dB.", "m²", 100, 10, 45, 32, 1, ["plaquiste", "platrier-plaquiste", "poseur-isolation"]],
    ["SO-PLA-103", "Cloison acoustique 120 mm sur double ossature, 2 × BA13 phonique", "Ossature désolidarisée, laine 2 × 45 mm, plaques phoniques par face. Joints compris.", "m²", 148.5, 10, 62.4, 52, 1.3, ["plaquiste", "platrier-plaquiste", "poseur-isolation"]],
    ["SO-PLA-104", "Cloison coupe-feu EI 60, 2 × BA13 feu par face", "Plaques type F sur ossature 48, laine minérale et joints. PV d'essai du fabricant à respecter.", "m²", 123, 10, 52.8, 42, 1.1, ["plaquiste", "platrier-plaquiste"]],
    ["SO-PLA-105", "Cloison alvéolaire plâtre 50 mm (carreau de plâtre alvéolé)", "Panneaux à âme alvéolaire collés en pied et en tête, joints. Solution économique sans isolant.", "m²", 47.5, 10, 22.5, 14, 0.5, ["plaquiste", "platrier-plaquiste"]],
    ["SO-PLA-106", "Cloison carreaux de plâtre pleins 7 cm", "Carreaux collés au plâtre-colle, liaisons et finition prête à peindre après ratissage.", "m²", 70, 10, 36, 18, 0.8, ["platrier", "platrier-plaquiste"]],
    ["SO-PLA-107", "Cloison carreaux de plâtre hydrofugés 7 cm (pièce humide)", "Carreaux hydro collés, premier rang sur coupure de capillarité. Prêts à recevoir faïence.", "m²", 81, 10, 38.25, 24, 0.85, ["platrier", "platrier-plaquiste"]],
    ["SO-PLA-108", "Doublage BA13 sur fourrures métalliques, sans isolant", "Fourrures sur appuis ou cornières, plaques vissées et joints. Masque des murs irréguliers.", "m²", 50.5, 10, 27, 12, 0.6, ["platrier", "plaquiste", "platrier-plaquiste"]],
    ["SO-PLA-109", "Plafond BA13 sur fourrures et suspentes", "Ossature F530 entraxe 50, plaques vissées, bandes et joints. Isolant non compris.", "m²", 62, 10, 33.75, 14, 0.75, ["platrier", "plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus"]],
    ["SO-PLA-110", "Plafond BA13 hydro sur ossature (salle de bains, cuisine)", "Ossature suspendue, plaques H1, bandes et joints. Peinture pièce humide non comprise.", "m²", 69, 10, 36, 17, 0.8, ["plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus"]],
    ["SO-PLA-111", "Plafond acoustique BA13 sur suspentes antivibratiles + laine 100", "Suspentes désolidarisées, laine minérale 100 mm et plaque phonique, joints compris.", "m²", 101.5, 10, 48, 30, 1, ["plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus", "poseur-isolation"]],
    ["SO-PLA-112", "Plafond coupe-feu 2 × BA13 feu sur ossature", "Protection de plancher bois ou de local technique, plaques type F et joints.", "m²", 110, 10, 52.8, 32, 1.1, ["plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus"]],
    ["SO-PLA-113", "Habillage de gaine ou coffre BA13 (développé ≤ 60 cm)", "Ossature, plaques, cornières d'angle et joints. Trappe de visite comptée à part.", "ml", 68, 10, 40.5, 12, 0.9, ["plaquiste", "platrier-plaquiste"]],
    ["SO-PLA-114", "Trappe de visite plâtre 40 × 40 cm, fournie posée", "Découpe dans cloison ou plafond, trappe à cadre aluminium et finition des joints.", "U", 85.5, 10, 33.75, 32, 0.75, ["plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus"]],
    ["SO-PLA-115", "Bandes et joints seuls sur plaques posées par autrui", "Bande papier, enduit en deux passes, ponçage et finition Q2 prête à peindre.", "m²", 12.5, 10, 8.1, 1.5, 0.18, ["plaquiste", "platrier-plaquiste"]],
    ["SO-PLA-116", "Ratissage complet enduit sur plaques (finition Q3)", "Enduit de lissage pleine surface sur plaques jointoyées, ponçage. Pour peinture satinée ou rasante.", "m²", 17, 10, 11.25, 1.8, 0.25, ["platrier", "plaquiste", "platrier-plaquiste", "peintre-batiment"]],
    ["SO-PLA-117", "Enduit plâtre projeté monocouche ép. 10 mm sur maçonnerie", "Projection machine, dressage et lissage, baguettes d'angle. Protection des abords comprise.", "m²", 27.5, 10, 16.8, 4.5, 0.35, ["platrier", "platrier-plaquiste", "staffeur-ornemaniste"]],
    ["SO-PLA-118", "Renfort bois ou métallique pour charge lourde dans cloison", "Pose d'un renfort pour meuble suspendu, WC suspendu, TV ou radiateur.", "U", 41, 10, 22.5, 8, 0.5, ["plaquiste", "platrier-plaquiste", "poseur-cuisines"]],
    ["SO-PLA-119", "Réparation trou ou fissure dans cloison plâtre (≤ 0,25 m²)", "Découpe, pièce de plaque ou bande armée, enduit et ponçage. Peinture non comprise.", "U", 83.5, 10, 54, 8, 1.2, ["platrier", "plaquiste", "platrier-plaquiste", "peintre-batiment", "staffeur-ornemaniste"]],
    ["SO-PLA-120", "Dépose de cloison plâtre ou plaques sur ossature", "Démontage soigné, tri des plaques et métaux, mise en sacs. Évacuation comptée à part.", "m²", 13.5, 10, 10.5, 0, 0.25, ["platrier", "plaquiste", "platrier-plaquiste", "poseur-plafonds-suspendus", "poseur-isolation"]],
    ["SO-PLA-121", "Reprise de plafond ancien plâtre sur lattis (≤ 2 m²)", "Purge des parties instables, regarnissage au plâtre sur grillage ou lattis, lissage.", "forfait", 321.5, 10, 208, 30, 4, ["platrier", "platrier-plaquiste", "staffeur-ornemaniste"]],
  ],
  "Plafonds suspendus": [
    ["SO-PLF-101", "Faux plafond dalles acoustiques 600 × 600 gamme supérieure", "Ossature T24 et dalles fibre minérale αw ≥ 0,9 bord feuilluré. Luminaires non compris.", "m²", 60.5, 10, 22.5, 24, 0.45, ["poseur-plafonds-suspendus"]],
    ["SO-PLF-102", "Faux plafond dalles lavables 600 × 600 (cuisine, sanitaires)", "Ossature T24 inox ou laquée, dalles à surface lavable résistant à l'humidité.", "m²", 64.5, 20, 22.5, 27, 0.45, ["poseur-plafonds-suspendus"]],
    ["SO-PLF-103", "Faux plafond dalles métalliques clipsées 600 × 600", "Ossature porteuse et dalles acier laqué perforées ou pleines, démontables.", "m²", 95, 20, 31.2, 42, 0.6, ["poseur-plafonds-suspendus"]],
    ["SO-PLF-104", "Faux plafond bois en lames ou panneaux sur ossature", "Lames bois ou panneaux mélaminés à joints creux sur ossature métal suspendue.", "m²", 123, 10, 46.8, 48, 0.9, ["poseur-plafonds-suspendus", "menuisier-bois", "menuisier-agenceur"]],
    ["SO-PLF-105", "Plafond tendu PVC mat ou satiné, pose sur lisses", "Toile tendue à chaud sur profilés périphériques, découpes pour luminaires comprises.", "m²", 67, 10, 27.5, 22, 0.5, ["poseur-plafonds-suspendus"]],
    ["SO-PLF-106", "Remplacement de dalles abîmées sur ossature existante", "Dépose, fourniture et pose de dalles identiques ou équivalentes, au m² remplacé.", "m²", 27.5, 10, 7.2, 13, 0.15, ["poseur-plafonds-suspendus"]],
    ["SO-PLF-107", "Dépose de faux plafond dalles et ossature", "Démontage, tri des dalles et métaux, mise en sacs. Évacuation comptée à part.", "m²", 8, 10, 6.3, 0, 0.15, ["poseur-plafonds-suspendus", "plaquiste", "platrier-plaquiste"]],
    ["SO-PLF-108", "Joue ou retombée BA13 en rive de faux plafond (h ≤ 50 cm)", "Ossature, plaque, cornière et joints pour raccord de niveaux ou soffite.", "ml", 52.5, 10, 31.5, 9, 0.7, ["poseur-plafonds-suspendus", "plaquiste", "platrier-plaquiste"]],
    ["SO-PLF-109", "Découpe et intégration de luminaire ou bouche dans faux plafond", "Découpe de dalle ou plaque, renfort d'ossature si besoin. Raccordement électrique exclu.", "U", 32.5, 10, 20, 4, 0.4, ["poseur-plafonds-suspendus", "plaquiste", "platrier-plaquiste"]],
    ["SO-PLF-110", "Laine minérale 100 mm posée sur faux plafond (acoustique)", "Rouleaux ou panneaux déroulés sur les dalles pour correction acoustique entre locaux.", "m²", 12.5, 10, 4.5, 5, 0.1, ["poseur-plafonds-suspendus", "poseur-isolation"]],
  ],
  "Isolation": [
    ["SO-ISO-101", "Isolation combles perdus laine minérale soufflée R ≥ 7", "Soufflage ép. ≈ 32 cm, piges de repérage, rehausse de trappe, écarts au feu. Récépissé fourni.", "m²", 18, 5.5, 4, 10, 0.08, ["poseur-isolation"]],
    ["SO-ISO-102", "Isolation combles perdus ouate de cellulose soufflée R ≥ 7", "Soufflage ép. ≈ 30 cm avec tassement pris en compte, piges et protections de conduits.", "m²", 20, 5.5, 4.5, 11, 0.09, ["poseur-isolation"]],
    ["SO-ISO-103", "Isolation combles perdus laine déroulée 2 couches croisées R ≥ 7", "Deux couches de rouleaux (200 + 100 mm) croisées, pare-vapeur si requis.", "m²", 32, 5.5, 9.6, 15, 0.2, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-104", "Isolation rampants laine 2 couches R ≥ 6 + membrane + BA13", "Laine entre et sous chevrons, suspentes, membrane hygro-régulante, ossature et plaque jointoyée.", "m²", 124.5, 5.5, 57.6, 38, 1.2, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-105", "Isolation rampants laine 2 couches R ≥ 6, sans parement", "Pose isolant et membrane d'étanchéité à l'air scotchée. Parement plaque non compris.", "m²", 63, 5.5, 26.4, 22, 0.55, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-106", "Doublage collé PSE graphité + BA13, R ≥ 3,7 (mur extérieur)", "Complexe isolant collé au mortier adhésif, joints et calfeutrement des tableaux.", "m²", 76.5, 5.5, 27, 32, 0.6, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-107", "Doublage sur ossature laine 120 mm R ≥ 3,7 + pare-vapeur + BA13", "Appuis intermédiaires, laine minérale, membrane continue, plaque et joints.", "m²", 95, 5.5, 43.2, 30, 0.9, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-108", "Doublage collé PSE 40 + BA13 (R ≈ 1,3, hors aide)", "Complexe mince pour correction thermique ou mur intérieur. Non éligible au taux réduit.", "m²", 51.5, 10, 24.75, 15, 0.55, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-109", "Isolation plancher bas sous-face PSE ou laine rigide R ≥ 3", "Panneaux fixés par chevilles en sous-face de cave ou vide sanitaire accessible.", "m²", 56, 5.5, 19.2, 24, 0.4, ["poseur-isolation"]],
    ["SO-ISO-110", "Isolation plancher de combles par panneaux sous plancher OSB", "Panneaux rigides entre solives R ≥ 7 et panneaux OSB 18 mm vissés pour rangement.", "m²", 126, 5.5, 45, 52, 0.9, ["poseur-isolation", "menuisier-bois"]],
    ["SO-ISO-111", "Laine minérale 45 mm en cloison (isolation phonique)", "Fourniture et pose entre montants lors de la création de cloison.", "m²", 7, 10, 2.25, 3, 0.05, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-112", "Membrane pare-vapeur hygro-régulante avec adhésifs", "Pose agrafée et scotchée en continuité, raccords aux murs et traversées étanchés.", "m²", 12, 5.5, 5.76, 3.5, 0.12, ["poseur-isolation", "plaquiste", "platrier-plaquiste"]],
    ["SO-ISO-113", "Dépose et évacuation ancien isolant de combles", "Retrait de laine ancienne tassée ou souillée, ensachage et évacuation en centre agréé.", "m²", 13.5, 10, 8.4, 2, 0.2, ["poseur-isolation"]],
    ["SO-ISO-114", "Isolation et rehausse de trappe d'accès aux combles", "Coffrage de rehausse, isolant collé R ≥ 4,5 sur trappe et joint d'étanchéité.", "U", 125, 5.5, 57.6, 35, 1.2, ["poseur-isolation"]],
    ["SO-ISO-115", "Capot de protection de spot encastré ou de conduit", "Écart au feu réglementaire autour des spots et conduits avant soufflage.", "U", 21.5, 10, 6.75, 9, 0.15, ["poseur-isolation"]],
  ],
  "Menuiserie intérieure": [
    ["SO-MEN-101", "Bloc-porte alvéolaire 83 × 204 prépeint, huisserie bois", "Fourniture et pose, calage, fixation, serrure bec de cane et poignée. Peinture non comprise.", "U", 253.5, 10, 100, 95, 2, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-102", "Bloc-porte âme pleine 83 × 204 isophonique, prépeint", "Porte lourde 40 mm à joint périphérique, quincaillerie standard et seuil. Peinture non comprise.", "U", 435.5, 10, 125, 210, 2.5, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-103", "Bloc-porte chêne plaqué ou massif 83 × 204, finition vernie", "Porte finie usine avec huisserie assortie, paumelles et quincaillerie laiton ou inox.", "U", 663, 10, 130, 380, 2.5, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-104", "Bloc-porte coupe-feu EI 30 avec ferme-porte", "Bloc certifié avec plaque et étiquette, ferme-porte et joints intumescents.", "U", 827, 20, 156, 480, 3, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-105", "Porte vitrée intérieure 83 × 204 (verre trempé dépoli)", "Bloc-porte à cadre bois et vitrage sécurit, poignée et serrure. Finition à prévoir.", "U", 578.5, 10, 125, 320, 2.5, ["menuisier-bois", "menuisier-agenceur", "vitrier"]],
    ["SO-MEN-106", "Châssis à galandage pour porte coulissante 83 × 204 + porte", "Caisson métallique intégré à cloison neuve, porte alvéolaire et quincaillerie. Plaques hors lot.", "U", 695.5, 10, 175, 360, 3.5, ["menuisier-bois", "menuisier-agenceur", "plaquiste", "platrier-plaquiste"]],
    ["SO-MEN-107", "Porte coulissante en applique sur rail visible 83 × 204", "Rail acier ou alu, porte prépeinte ou décor, butées et guide au sol.", "U", 442, 10, 100, 240, 2, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-108", "Dépose de porte intérieure et huisserie", "Démontage soigné, rebouchage sommaire des scellements. Évacuation comptée à part.", "U", 44, 10, 33.75, 0, 0.75, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-109", "Ajustage de porte (rabotage, détalonnage, reprise de paumelles)", "Dépose, rabotage ou recoupe pour passage de revêtement de sol, repose et réglage.", "U", 70, 10, 50, 2, 1, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-110", "Remplacement serrure et béquillage de porte intérieure", "Fourniture et pose d'une serrure à larder et d'un ensemble poignées sur rosaces.", "U", 111.5, 10, 37.5, 45, 0.75, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-111", "Façade de placard coulissante 2 vantaux mélaminé (≤ 2 m)", "Portes mélaminées ou miroir sur rails haut et bas, profils acier laqué. Sur mesure.", "U", 708.5, 10, 125, 420, 2.5, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-112", "Façade de placard battante 2 portes avec bâti", "Bâti bois, portes prépeintes 2 × 50 cm, charnières et boutons. Aménagement intérieur exclu.", "U", 533, 10, 150, 260, 3, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-113", "Aménagement intérieur de placard (étagères, penderie, tiroirs)", "Kit mélaminé 18 mm sur mesure, crémaillères et tube de penderie, par ml de placard.", "ml", 253.5, 10, 75, 120, 1.5, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-114", "Plinthes MDF 70 mm à peindre, collées et clouées", "Fourniture et pose avec coupes d'onglet, joints acryliques. Peinture non comprise.", "ml", 14.5, 10, 7.2, 3.5, 0.15, ["menuisier-bois", "menuisier-agenceur", "parqueteur"]],
    ["SO-MEN-115", "Plinthes bois massif chêne ou pin 90 mm vernies", "Plinthe massif finie, coupes et raccords, fixation par clouage ou colle.", "ml", 24.5, 10, 9, 9, 0.18, ["menuisier-bois", "menuisier-agenceur", "parqueteur"]],
    ["SO-MEN-116", "Dépose de plinthes bois ou carrelage", "Dépose soignée, purge des clous et colle, mise en sac.", "ml", 2.5, 10, 2.1, 0, 0.05, ["menuisier-bois", "parqueteur", "carreleur", "solier-moquettiste"]],
    ["SO-MEN-117", "Escalier droit sapin ou hêtre à limons, 13 marches, vernis", "Fabrication, livraison et pose, marches 30 mm, rampe d'un côté. Trémie existante.", "U", 3146, 10, 770, 1650, 14, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-118", "Escalier quart tournant hêtre ou chêne, 14 marches, vernis", "Escalier sur mesure à limons, contremarches, rampe et main courante, pose comprise.", "U", 5200, 10, 1100, 2900, 20, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-119", "Habillage d'escalier béton en chêne (marches et contremarches)", "Marches 26 mm et contremarches 10 mm collées, nez arrondis, par marche.", "U", 252, 10, 99, 95, 1.8, ["menuisier-bois", "menuisier-agenceur", "parqueteur"]],
    ["SO-MEN-120", "Échelle escamotable isolée pour trappe de comble 70 × 120", "Fourniture, élargissement de trémie si besoin, pose et réglage de l'échelle 3 plans.", "U", 559, 10, 150, 280, 3, ["menuisier-bois", "menuisier-agenceur"]],
    ["SO-MEN-121", "Habillage de tableau de fenêtre en MDF ou bois (≤ 1,40 m)", "Joues et tablette en MDF hydro ou bois massif, joints de finition. Peinture non comprise.", "U", 155, 10, 75, 40, 1.5, ["menuisier-bois", "menuisier-agenceur"]],
  ],
  "Agencement sur mesure": [
    ["SO-AGE-101", "Dressing sur mesure mélaminé 18 mm, h ≤ 2,50 m", "Caissons, étagères, penderies et 2 tiroirs par ml, conception et pose. Portes non comprises.", "ml", 780, 10, 220, 380, 4, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-102", "Dressing haut de gamme laqué ou plaqué bois, portes incluses", "Agencement sur mesure, tiroirs à fermeture amortie, portes battantes, éclairage hors lot.", "ml", 1763, 10, 406, 950, 7, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-103", "Bibliothèque sur mesure MDF à peindre, toute hauteur", "Fabrication atelier, montants et étagères 25 mm, pose et calage. Peinture non comprise.", "ml", 845, 10, 330, 320, 6, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-104", "Meuble TV suspendu sur mesure (≤ 2,40 m)", "Caisson laqué ou décor bois, passe-câbles et fixation renforcée au mur.", "U", 1183, 10, 330, 580, 6, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-105", "Aménagement de placard sous escalier sur mesure", "Caissons, tiroirs ou portes découpés au profil de l'escalier, pose comprise.", "forfait", 1963, 10, 660, 850, 12, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-106", "Bureau ou plan suspendu sur mesure avec étagères", "Plateau 40 mm sur tasseaux ou consoles invisibles, 2 étagères murales.", "ml", 487.5, 10, 165, 210, 3, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-107", "Habillage mural tasseaux bois sur panneau acoustique", "Tasseaux chêne ou noyer sur feutre, fixation par vis ou colle. Découpes prises.", "m²", 229, 10, 66, 110, 1.2, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-108", "Claustra bois sur mesure (séparation de pièce)", "Lames verticales bois massif entre lisses haute et basse, finition vernie.", "ml", 536, 10, 192.5, 220, 3.5, ["menuisier-agenceur", "menuisier-bois"]],
    ["SO-AGE-109", "Meuble de salle de bains sur mesure sous vasque", "Caisson hydrofuge, façades laquées, découpe plan pour vasque. Plomberie exclue.", "ml", 1033.5, 10, 275, 520, 5, ["menuisier-agenceur", "menuisier-bois", "poseur-cuisines"]],
    ["SO-AGE-110", "Comptoir ou banque d'accueil sur mesure (local professionnel)", "Fabrication et pose, plateau stratifié, tablette haute et rangements. ERP : accessibilité incluse.", "ml", 1617, 20, 464, 780, 8, ["menuisier-agenceur", "menuisier-bois"]],
  ],
  "Cuisine et salle de bains": [
    ["SO-CUI-101", "Pose de meuble bas de cuisine (montage, mise à niveau)", "Montage du caisson fourni, réglage des pieds, assemblage et réglage des façades.", "U", 69, 10, 50, 3, 1, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-102", "Pose de meuble haut de cuisine sur rail ou fixation directe", "Montage, fixation sur rail ou chevilles adaptées au support, réglage des portes.", "U", 73, 10, 50, 6, 1, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-103", "Pose de colonne four ou réfrigérateur intégrable", "Montage et fixation de colonne, réglage des façades. Raccordements hors lot.", "U", 125, 10, 90, 6, 1.8, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-104", "Plan de travail stratifié 38 mm fourni posé", "Plan postformé, chants, joints d'étanchéité et fixation. Découpes comptées à part.", "ml", 162.5, 10, 50, 75, 1, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-105", "Plan de travail quartz ou céramique 20 mm, fourni posé", "Gabarit sur site, fabrication et pose par le fournisseur, chants polis. Découpes en sus.", "ml", 617.5, 10, 55, 420, 1, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-106", "Plan de travail bois massif 38 mm huilé, fourni posé", "Chêne ou hêtre lamellé, huilage, fixation avec jeu de dilatation.", "ml", 305.5, 10, 75, 160, 1.5, ["poseur-cuisines", "menuisier-agenceur", "menuisier-bois"]],
    ["SO-CUI-107", "Découpe d'évier ou de plaque dans plan stratifié ou bois", "Traçage, découpe à la scie sur gabarit, étanchéité des chants.", "U", 54.5, 10, 37.5, 3, 0.75, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-108", "Crédence stratifié ou compact 10 mm fournie posée", "Panneau collé et jointoyé, découpes de prises comprises.", "ml", 123.5, 10, 40, 55, 0.8, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-109", "Pose de plinthes et fileurs de cuisine", "Ajustage et clipsage des plinthes, fileurs de compensation et joues de finition.", "ml", 23, 10, 15, 2, 0.3, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-110", "Pose d'électroménager encastrable (four, plaque, lave-vaisselle)", "Mise en place et fixation dans le meuble, branchement sur attentes existantes conformes.", "U", 53.5, 20, 37.5, 2, 0.75, ["poseur-cuisines"]],
    ["SO-CUI-111", "Fourniture et pose hotte décorative ou intégrée avec conduit", "Hotte, fixation, gaine Ø 125 vers sortie existante. Percement mur extérieur en sus.", "U", 494, 20, 100, 280, 2, ["poseur-cuisines"]],
    ["SO-CUI-112", "Dépose d'une cuisine existante (≤ 4 ml)", "Démontage meubles, plan et électroménager, condamnation des attentes. Évacuation à part.", "forfait", 247, 10, 180, 10, 4, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-113", "Pose d'îlot central (caissons, plan et joues)", "Assemblage et fixation au sol des caissons, pose du plan et des joues, mise à niveau.", "forfait", 357.5, 10, 250, 25, 5, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-114", "Pose de meuble vasque suspendu avec miroir", "Fixation sur renforts, pose de la vasque et du miroir. Raccordement plomberie exclu.", "U", 140.5, 10, 100, 8, 2, ["poseur-cuisines", "menuisier-agenceur"]],
    ["SO-CUI-115", "Pose de receveur de douche extra-plat sur pieds ou sur chape", "Mise à niveau, réglage de pente, joint silicone. Bonde et raccordement par le plombier.", "U", 188.5, 10, 125, 20, 2.5, ["poseur-cuisines", "carreleur", "carreleur-mosaiste"]],
    ["SO-CUI-116", "Panneaux muraux stratifiés étanches (douche, crédence)", "Panneaux 10 mm collés, profils de jonction et silicone. Alternative sans joint à la faïence.", "m²", 143, 10, 45, 65, 0.9, ["poseur-cuisines", "menuisier-agenceur", "carreleur"]],
  ],
  "Parquets et sols bois": [
    ["SO-PAR-101", "Parquet stratifié AC5 12 mm grand passage, flottant", "Sous-couche acoustique intégrée, coupes et barres de seuil. Plinthes comptées à part.", "m²", 53, 10, 16.8, 24, 0.35, ["parqueteur", "solier-moquettiste"]],
    ["SO-PAR-102", "Parquet contrecollé chêne 14 mm vernis, pose flottante", "Sous-couche, pose clic ou collée en rive, joints de dilatation. Plinthes non comprises.", "m²", 84, 10, 22.5, 42, 0.45, ["parqueteur"]],
    ["SO-PAR-103", "Parquet contrecollé chêne 15 mm, pose collée", "Colle polymère sur support plan, compatible sol chauffant. Ragréage non compris.", "m²", 103.5, 10, 27.5, 52, 0.55, ["parqueteur"]],
    ["SO-PAR-104", "Parquet massif chêne 14 mm, pose collée, brut ou verni", "Lames 70 à 90 mm collées pleine surface, finition usine ou ponçage en sus.", "m²", 125.5, 10, 36.4, 60, 0.7, ["parqueteur"]],
    ["SO-PAR-105", "Parquet massif chêne 21 mm cloué sur lambourdes", "Lambourdes réglées et calées, lames clouées. Ponçage et finition comptés à part.", "m²", 176, 10, 57.2, 78, 1.1, ["parqueteur", "menuisier-bois"]],
    ["SO-PAR-106", "Parquet point de Hongrie ou bâton rompu contrecollé, collé", "Traçage, pose collée en motif, bande de rive. Ragréage et finition non compris.", "m²", 179.5, 10, 66, 72, 1.2, ["parqueteur"]],
    ["SO-PAR-107", "Sol vinyle clipsable LVT 5 mm avec sous-couche", "Lames vinyle rigide pose flottante, résistant à l'eau, découpes et seuils.", "m²", 50, 10, 14.4, 24, 0.3, ["parqueteur", "solier-moquettiste"]],
    ["SO-PAR-108", "Sous-couche acoustique pour parquet flottant", "Fourniture et pose de sous-couche ép. 2 à 3 mm, film pare-vapeur intégré.", "m²", 6.5, 10, 1.44, 3.5, 0.03, ["parqueteur", "solier-moquettiste"]],
    ["SO-PAR-109", "Ponçage et vitrification de parquet ancien (3 couches)", "Trois passages de ponçage, bouche-pores, rebouchage des joints et 3 couches vitrificateur.", "m²", 43.5, 10, 26.4, 6, 0.55, ["parqueteur"]],
    ["SO-PAR-110", "Ponçage et huilage ou cirage de parquet", "Ponçage complet, aspiration et 2 couches d'huile-cire ou d'huile dure.", "m²", 44.5, 10, 26.4, 6.5, 0.55, ["parqueteur"]],
    ["SO-PAR-111", "Égrenage et revitrification sans ponçage complet", "Égrenage à la monobrosse et une couche de vitrificateur sur parquet sain.", "m²", 15.5, 10, 8.64, 3, 0.18, ["parqueteur"]],
    ["SO-PAR-112", "Réparation ponctuelle de parquet (remplacement de lames)", "Dépose des lames abîmées, remplacement par lames d'origine ou similaires, raccord.", "forfait", 256.5, 10, 150, 40, 3, ["parqueteur"]],
    ["SO-PAR-113", "Dépose de parquet ou stratifié existant", "Dépose de lames clouées, collées ou flottantes, grattage des résidus, mise en sacs.", "m²", 11, 10, 8.4, 0, 0.2, ["parqueteur", "solier-moquettiste"]],
    ["SO-PAR-114", "Barre de seuil ou profilé de finition aluminium", "Profilé de transition ou de rive, coupe et fixation.", "U", 35, 10, 12, 14, 0.25, ["parqueteur", "solier-moquettiste", "carreleur"]],
  ],
  "Carrelage et faïence": [
    ["SO-CAR-101", "Carrelage sol grès cérame 30 × 30 ou 45 × 45, pose collée", "Double encollage si besoin, joints ciment. Fourniture carrelage standard ≈ 20 €/m².", "m²", 83.5, 10, 38.4, 26, 0.8, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-102", "Carrelage sol grand format 60 × 120 rectifié, pose collée", "Double encollage, croisillons auto-nivelants, joints fins. Ragréage non compris.", "m²", 134, 10, 55, 48, 1.1, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-103", "Carrelage sol imitation parquet 20 × 120, pose décalée", "Pose collée avec décalage 1/3, joints fins teintés. Plinthes non comprises.", "m²", 118.5, 10, 55, 36, 1.1, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-104", "Carrelage extérieur antidérapant R11 sur chape existante", "Pose collée double encollage, mortier-colle C2S1, joints, pente conservée.", "m²", 114.5, 10, 50, 38, 1, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-105", "Dallage céramique 20 mm sur plots (terrasse sur étanchéité)", "Plots réglables et dalles grès 60 × 60 ép. 20 mm, sans joint collé.", "m²", 119.5, 10, 30, 62, 0.6, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-106", "Faïence murale 30 × 60 ou 30 × 90 rectifiée, pose collée", "Colle C2, joints fins, profilés d'angle. SPEC en zone humide compté à part.", "m²", 106.5, 10, 50, 32, 1, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-107", "Faïence grand format 60 × 120 murale", "Double encollage, cales de nivellement, découpes soignées. Manutention à deux.", "m²", 162, 10, 72.8, 52, 1.4, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-108", "Carrelage mural petit format type métro ou zellige 7,5 × 15", "Pose collée serrée ou joints marqués, découpes nombreuses, joints ciment.", "m²", 166.5, 10, 83.2, 45, 1.6, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-109", "Mosaïque pâte de verre ou grès sur trame, pose murale", "Pose collée colle blanche, joints époxy ou ciment fin, découpes en périphérie.", "m²", 214.5, 10, 110, 55, 2, ["carreleur-mosaiste", "carreleur"]],
    ["SO-CAR-110", "Mosaïque de sol en grès cérame sur trame (douche, bande décor)", "Pose collée sur support plan et SPEC, joints époxy, pente respectée.", "m²", 235.5, 10, 121, 60, 2.2, ["carreleur-mosaiste", "carreleur"]],
    ["SO-CAR-111", "Système d'étanchéité liquide sous carrelage (SPEC) zone douche", "Primaire, deux couches de résine, bandes d'angle et manchettes. Requis sous carrelage douche.", "m²", 44, 10, 20, 14, 0.4, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-112", "Natte de désolidarisation sous carrelage", "Natte collée sur support fissuré, bois ou chauffant, bandes de raccord.", "m²", 37, 10, 12.5, 16, 0.25, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-113", "Ragréage autolissant P3 ép. 3 à 5 mm", "Primaire d'accrochage et ragréage fibré sur support sain. Préparation lourde en sus.", "m²", 21, 10, 7.2, 9, 0.15, ["carreleur", "carreleur-mosaiste", "parqueteur", "solier-moquettiste"]],
    ["SO-CAR-114", "Chape de ravoirage au mortier ép. 4 à 6 cm", "Chape dosée à 350 kg tirée à la règle, finition talochée prête à carreler.", "m²", 36.5, 10, 19.2, 9, 0.4, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-115", "Douche à l'italienne carrelée (≤ 1,2 m², hors plomberie)", "Forme de pente, SPEC, caniveau ou siphon de sol, carrelage antidérapant et joints.", "forfait", 1440.5, 10, 728, 380, 14, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-116", "Tablier de baignoire carrelé avec trappe de visite", "Ossature ou carreaux de plâtre hydro, faïence, trappe magnétique.", "U", 357.5, 10, 200, 75, 4, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-117", "Plinthes carrelage assorties, collées et jointoyées", "Plinthes coupées dans le carrelage ou industrielles, joint silicone haut.", "ml", 19.5, 10, 9.6, 5, 0.2, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-118", "Carrelage de marche d'escalier avec nez de marche", "Marche et contremarche carrelées, profil nez de marche aluminium, par marche.", "U", 143, 10, 75, 35, 1.5, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-119", "Dépose de carrelage sol ou faïence et ragréage du support", "Burinage, piquage de la colle, mise en sacs. Évacuation comptée à part.", "m²", 36.5, 10, 27, 1, 0.6, ["carreleur", "carreleur-mosaiste", "solier-moquettiste"]],
    ["SO-CAR-120", "Remplacement d'un carreau cassé (sol ou mur)", "Dépose du carreau, purge de la colle, pose d'un carreau fourni par le client, joints.", "forfait", 112, 10, 75, 8, 1.5, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-121", "Réfection des joints de carrelage (grattage et rejointoiement)", "Dégarnissage mécanique, nettoyage et rejointoiement ciment ou époxy.", "m²", 44.5, 10, 28.8, 4, 0.6, ["carreleur", "carreleur-mosaiste"]],
    ["SO-CAR-122", "Joints silicone sanitaire (douche, baignoire, évier)", "Dépose de l'ancien joint, nettoyage, fongicide et joint neuf lissé.", "ml", 11, 10, 6.75, 1.5, 0.15, ["carreleur", "carreleur-mosaiste", "poseur-cuisines"]],
    ["SO-CAR-123", "Crédence de cuisine carrelée (≤ 3 m²)", "Pose de faïence ou carreaux décoratifs, découpes de prises et joints.", "forfait", 377, 10, 200, 90, 4, ["carreleur", "carreleur-mosaiste", "poseur-cuisines"]],
  ],
  "Sols souples": [
    ["SO-SOL-101", "Sol PVC en lés U2SP3 acoustique, pose collée", "Colle acrylique, arasement et soudure ou joints à froid. Ragréage non compris.", "m²", 41, 10, 13.5, 18, 0.3, ["solier-moquettiste"]],
    ["SO-SOL-102", "Sol PVC compact U4P3 hétérogène, pose collée soudée à chaud", "Lés pour locaux à fort trafic, soudure à chaud des joints. Ragréage non compris.", "m²", 56, 20, 19.2, 24, 0.4, ["solier-moquettiste"]],
    ["SO-SOL-103", "Lames ou dalles vinyle LVT à coller 2,5 mm", "Pose collée sur ragréage, découpes et finitions, compatible sol chauffant.", "m²", 55.5, 10, 16.8, 26, 0.35, ["solier-moquettiste", "parqueteur"]],
    ["SO-SOL-104", "Linoléum naturel 2,5 mm en lés, pose collée", "Lés soudés à chaud avec cordon, colle spécifique. Ragréage non compris.", "m²", 69.5, 10, 21.6, 32, 0.45, ["solier-moquettiste"]],
    ["SO-SOL-105", "Moquette velours ou bouclée en lés, pose tendue ou collée", "Thibaude ou colle, joints arasés, barres de seuil. Gamme résidentielle.", "m²", 57, 10, 15.75, 28, 0.35, ["solier-moquettiste"]],
    ["SO-SOL-106", "Dalles de moquette 50 × 50 plombantes ou collées (bureaux)", "Pose libre avec poisseux ou collée, découpes en rive.", "m²", 43, 20, 11.25, 22, 0.25, ["solier-moquettiste"]],
    ["SO-SOL-107", "Remontée en plinthe sol souple (gorge et profil)", "Remontée de 10 cm sur profil gorge, soudure et profil de finition.", "ml", 25, 10, 14.4, 4, 0.3, ["solier-moquettiste"]],
    ["SO-SOL-108", "Revêtement de marche d'escalier en sol souple ou moquette", "Pose collée sur marche et contremarche, nez de marche PVC ou alu.", "U", 75.5, 10, 36, 22, 0.75, ["solier-moquettiste"]],
    ["SO-SOL-109", "Dépose de sol souple ou moquette collée, grattage", "Arrachage, grattage des colles et ragréage sommaire, mise en sacs.", "m²", 11.5, 10, 8.4, 0.5, 0.2, ["solier-moquettiste", "parqueteur"]],
    ["SO-SOL-110", "Primaire d'accrochage et préparation du support", "Aspiration, ponçage ou grattage léger et primaire avant ragréage ou collage.", "m²", 5, 10, 2.25, 1.5, 0.05, ["solier-moquettiste", "parqueteur", "carreleur"]],
    ["SO-SOL-111", "Ragréage fibré P4 ép. 5 à 10 mm sur ancien carrelage ou bois", "Primaire spécifique et ragréage fibré pour supports difficiles.", "m²", 32, 10, 9.6, 15, 0.2, ["solier-moquettiste", "parqueteur", "carreleur"]],
    ["SO-SOL-112", "Sol PVC antidérapant douche et vestiaire (R10 / PN 18)", "Lés collés et soudés, remontées et raccord au siphon pour zones humides.", "m²", 75.5, 10, 24, 34, 0.5, ["solier-moquettiste"]],
  ],
  "Peinture et revêtements muraux": [
    ["SO-PEI-101", "Peinture plafond acrylique mate 2 couches", "Impression si besoin et 2 couches mates, protections comprises. Supports sains.", "m²", 15, 10, 9, 2.5, 0.2, ["peintre-batiment"]],
    ["SO-PEI-102", "Peinture murs acrylique satinée 2 couches (lessivable)", "Égrenage, 2 couches satinées pour couloirs, cuisines et chambres d'enfants.", "m²", 17, 10, 9.9, 3, 0.22, ["peintre-batiment"]],
    ["SO-PEI-103", "Peinture spéciale pièce humide 2 couches (fongicide)", "Traitement fongicide si besoin et 2 couches de peinture salle de bains.", "m²", 18, 10, 9.9, 4, 0.22, ["peintre-batiment"]],
    ["SO-PEI-104", "Impression sur plaques de plâtre ou plâtre neuf", "Une couche d'impression garnissante avant finition.", "m²", 6, 10, 3.6, 1, 0.08, ["peintre-batiment"]],
    ["SO-PEI-105", "Lessivage des murs et plafonds", "Lessive alcaline, rinçage à l'éponge, temps de séchage.", "m²", 4.5, 10, 2.94, 0.3, 0.07, ["peintre-batiment"]],
    ["SO-PEI-106", "Rebouchage et ponçage localisés avant peinture", "Grattage, rebouchage des trous et fissures, ponçage, par m² de surface traitée.", "m²", 7, 10, 4.5, 0.5, 0.1, ["peintre-batiment"]],
    ["SO-PEI-107", "Enduit de lissage complet en 2 passes avant peinture", "Enduit pâte ou poudre en deux passes croisées, ponçage soigné. Finition Q3.", "m²", 23, 10, 15.75, 2, 0.35, ["peintre-batiment", "platrier", "platrier-plaquiste"]],
    ["SO-PEI-108", "Traitement de fissure par bande calicot ou toile armée", "Ouverture de la fissure, entoilage et enduit de recouvrement, ponçage.", "ml", 20, 10, 13.5, 1.5, 0.3, ["peintre-batiment"]],
    ["SO-PEI-109", "Toile de verre à peindre posée + 2 couches acryliques", "Encollage, pose à joints vifs, 2 couches de peinture. Murs ou plafonds.", "m²", 27, 10, 15.75, 5, 0.35, ["peintre-batiment"]],
    ["SO-PEI-110", "Papier peint intissé uni ou motif standard, posé", "Encollage du mur, raccords et découpes. Fourniture papier ≈ 25 €/rouleau.", "m²", 25.5, 10, 13.5, 6, 0.3, ["peintre-batiment"]],
    ["SO-PEI-111", "Papier peint panoramique ou haut de gamme, posé", "Pose de lés numérotés avec raccords précis, colle adaptée, découpes soignées.", "m²", 78, 10, 30, 30, 0.6, ["peintre-batiment"]],
    ["SO-PEI-112", "Dépose de papier peint (décolleuse vapeur)", "Décollage, grattage, lessivage des résidus de colle, mise en sacs.", "m²", 10.5, 10, 7.56, 0.3, 0.18, ["peintre-batiment"]],
    ["SO-PEI-113", "Peinture porte intérieure 2 faces + huisserie (glycéro ou acrylique)", "Égrenage, impression si besoin et 2 couches laque satinée, quincaillerie protégée.", "U", 132.5, 10, 90, 12, 2, ["peintre-batiment"]],
    ["SO-PEI-114", "Peinture fenêtre bois 2 faces (≤ 1,5 m²)", "Grattage, ponçage, rebouchage, impression et 2 couches microporeuses.", "U", 159, 10, 112.5, 10, 2.5, ["peintre-batiment"]],
    ["SO-PEI-115", "Peinture de plinthes, chambranles ou moulures", "Égrenage et 2 couches laque, raccords et masquage.", "ml", 7, 10, 4.5, 0.5, 0.1, ["peintre-batiment"]],
    ["SO-PEI-116", "Peinture radiateur acier ou fonte (≤ 1 m²)", "Dégraissage, ponçage, antirouille si besoin et 2 couches peinture radiateur.", "U", 80.5, 10, 54, 8, 1.2, ["peintre-batiment"]],
    ["SO-PEI-117", "Peinture de garde-corps ou grille métallique (antirouille + laque)", "Brossage, antirouille et 2 couches laque glycéro, au ml de garde-corps h ≤ 1 m.", "ml", 40.5, 10, 27, 4, 0.6, ["peintre-batiment"]],
    ["SO-PEI-118", "Lasure ou saturateur sur volets, bardage ou boiseries extérieures", "Nettoyage, ponçage léger et 2 couches de lasure ou saturateur.", "m²", 21.5, 10, 13.5, 3, 0.3, ["peintre-batiment"]],
    ["SO-PEI-119", "Décapage de peinture sur boiseries (chimique ou thermique)", "Décapage, grattage, neutralisation et ponçage avant mise en peinture.", "m²", 81, 10, 54, 6, 1.2, ["peintre-batiment"]],
    ["SO-PEI-120", "Peinture de sol béton (garage, cave) 2 couches", "Dégraissage, primaire et 2 couches peinture sol polyuréthane ou époxy.", "m²", 22.5, 10, 11.25, 6, 0.25, ["peintre-batiment"]],
    ["SO-PEI-121", "Enduit décoratif à la chaux ou béton ciré mural", "Primaire, 2 à 3 passes d'enduit décoratif, finition cire ou vernis de protection.", "m²", 104.5, 10, 62.4, 18, 1.2, ["peintre-batiment"]],
    ["SO-PEI-122", "Masquage et protection avant mise en peinture", "Bâches, adhésifs et films sur sols, menuiseries et équipements, retrait final.", "m²", 3, 10, 1.68, 0.6, 0.04, ["peintre-batiment"]],
  ],
  "Vitrerie et miroiterie": [
    ["SO-VIT-101", "Remplacement de vitre simple 4 mm sur châssis existant (≤ 1 m²)", "Dépose du verre cassé, mastic ou parcloses, verre clair coupé à dimension.", "U", 115, 10, 50, 35, 1, ["vitrier", "miroitier"]],
    ["SO-VIT-102", "Remplacement de vitrage feuilleté de sécurité 44.2", "Verre feuilleté coupé sur mesure, pose sous parcloses ou mastic, au m².", "m²", 178.5, 10, 62.4, 75, 1.2, ["vitrier", "miroitier"]],
    ["SO-VIT-103", "Double vitrage à isolation renforcée Ug ≤ 1,1 en remplacement", "Vitrage 4/16/4 faible émissivité gaz argon, intercalaire warm-edge, sous parcloses.", "m²", 198.5, 10, 67.6, 85, 1.3, ["vitrier", "miroitier"]],
    ["SO-VIT-104", "Vitrage dépoli ou imprimé (salle de bains, porte)", "Verre dépoli acide ou imprimé, coupé à dimension et posé sous parcloses.", "m²", 136.5, 10, 50, 55, 1, ["vitrier", "miroitier"]],
    ["SO-VIT-105", "Mise en sécurité après bris de glace (panneau provisoire)", "Intervention, retrait des débris et panneau bois ou polycarbonate provisoire.", "forfait", 152, 10, 82.5, 30, 1.5, ["vitrier", "miroitier"]],
    ["SO-VIT-106", "Paroi de douche fixe verre trempé 8 mm (≤ 1,20 m)", "Verre sécurit traité anticalcaire, profilé mural et barre de stabilité inox.", "U", 551, 10, 104, 320, 2, ["vitrier", "miroitier", "poseur-cuisines"]],
    ["SO-VIT-107", "Porte de douche pivotante verre trempé 8 mm en niche", "Vitrage sécurit, charnières verre-mur, joints d'étanchéité et poignée.", "U", 793, 10, 130, 480, 2.5, ["vitrier", "miroitier", "poseur-cuisines"]],
    ["SO-VIT-108", "Crédence en verre laqué trempé sur mesure", "Prise de cotes, découpes de prises usinées, pose collée au mastic spécial verre.", "m²", 354, 10, 82.5, 190, 1.5, ["vitrier", "miroitier", "poseur-cuisines"]],
    ["SO-VIT-109", "Verrière d'atelier acier ou alu sur allège ou toute hauteur", "Profilés noirs mats, vitrage feuilleté ou trempé, fixation et calfeutrement.", "m²", 725, 10, 137.5, 420, 2.5, ["vitrier", "miroitier", "menuisier-bois", "menuisier-agenceur"]],
    ["SO-VIT-110", "Cloison vitrée de bureau toute hauteur (local professionnel)", "Profilés alu, vitrage feuilleté 44.2 ou 55.2, porte non comprise.", "m²", 481, 20, 110, 260, 2, ["vitrier", "miroitier"]],
    ["SO-VIT-111", "Garde-corps verre feuilleté sur profil aluminium", "Profil en U fixé en nez de dalle ou au sol, verre 66.2 ou 88.2 trempé feuilleté.", "ml", 760.5, 10, 165, 420, 3, ["vitrier", "miroitier"]],
    ["SO-MIR-101", "Miroir argenté 5 mm collé, bords polis (≤ 2 m²)", "Coupe à dimension, bords polis, collage au mastic miroir sur support plan.", "m²", 196.5, 10, 66, 85, 1.2, ["miroitier", "vitrier"]],
    ["SO-MIR-102", "Miroir biseauté ou à façon sur mesure avec fixations", "Biseau 15 à 25 mm, perçages ou pattes invisibles, protection anti-éclats.", "m²", 276, 10, 82.5, 130, 1.5, ["miroitier", "vitrier"]],
    ["SO-MIR-103", "Miroir rétroéclairé LED de salle de bains (≤ 120 × 80)", "Fourniture et fixation, raccordement sur attente existante conforme.", "U", 445, 10, 82.5, 260, 1.5, ["miroitier", "vitrier", "poseur-cuisines"]],
    ["SO-MIR-104", "Habillage mural en miroir (pan de mur, dressing)", "Plaques miroir sécurisées par film arrière, joints et découpes, pose collée.", "m²", 271.5, 10, 99, 110, 1.8, ["miroitier", "vitrier"]],
    ["SO-MIR-105", "Tablette ou étagère en verre trempé avec supports", "Verre trempé 8 à 10 mm bords polis, supports inox, perçage compris.", "U", 130, 10, 41.25, 55, 0.75, ["miroitier", "vitrier"]],
    ["SO-MIR-106", "Film adhésif occultant ou de sécurité sur vitrage", "Nettoyage et pose de film dépoli, solaire ou anti-effraction.", "m²", 61, 10, 20, 25, 0.4, ["miroitier", "vitrier"]],
    ["SO-MIR-107", "Dépose de miroir collé ou de vitrage", "Décollage au fil, protection anti-éclats et évacuation des verres.", "m²", 41.5, 10, 30, 2, 0.6, ["miroitier", "vitrier"]],
  ],
  "Staff et ornementation": [
    ["SO-STA-101", "Corniche staff lisse ou à gorge (≤ 15 cm), fournie posée", "Profil staff préfabriqué collé et chevillé, coupes d'onglet, raccords enduits.", "ml", 57, 10, 30, 14, 0.5, ["staffeur-ornemaniste"]],
    ["SO-STA-102", "Corniche staff restituée par tirage sur place (profil existant)", "Relevé de profil, gabarit, tirage au plâtre sur place et raccords à l'ancien.", "ml", 191.5, 10, 130, 12, 2, ["staffeur-ornemaniste", "platrier"]],
    ["SO-STA-103", "Réparation de corniche existante (raccord ≤ 1 ml)", "Purge des parties dégradées, reconstitution du profil au plâtre, finition.", "forfait", 385, 10, 260, 25, 4, ["staffeur-ornemaniste", "platrier"]],
    ["SO-STA-104", "Rosace de plafond staff Ø 60 cm, fournie posée", "Rosace préfabriquée collée et chevillée, passage du câble d'éclairage.", "U", 188.5, 10, 60, 85, 1, ["staffeur-ornemaniste"]],
    ["SO-STA-105", "Rosace sur mesure reproduite par moulage (Ø ≤ 80 cm)", "Prise d'empreinte ou modèle, moule silicone, tirage staff et pose.", "U", 864, 10, 520, 120, 8, ["staffeur-ornemaniste"]],
    ["SO-STA-106", "Moulure d'encadrement ou cadre mural staff", "Moulure plate ou décorée collée, coupes d'onglet et raccords.", "ml", 39, 10, 21, 9, 0.35, ["staffeur-ornemaniste", "peintre-batiment"]],
    ["SO-STA-107", "Cache-lumière staff pour éclairage indirect (corniche lumineuse)", "Profil creux pour ruban LED fixé en tête de mur. Éclairage hors lot.", "ml", 75.5, 10, 36, 22, 0.6, ["staffeur-ornemaniste", "plaquiste", "platrier-plaquiste"]],
    ["SO-STA-108", "Plafond staff plan sur ossature (plaques staff armées)", "Plaques staff fixées par polochons filasse, joints et ratissage.", "m²", 156, 10, 90, 30, 1.5, ["staffeur-ornemaniste"]],
    ["SO-STA-109", "Plafond à caissons ou voûte en staff sur mesure", "Fabrication atelier, pose sur ossature, raccords et finition prête à peindre.", "m²", 479.5, 10, 260, 95, 4, ["staffeur-ornemaniste"]],
    ["SO-STA-110", "Pilastre ou demi-colonne staff avec chapiteau", "Fût, base et chapiteau préfabriqués ou moulés, fixation et raccords, h ≤ 2,80 m.", "U", 767, 10, 310, 280, 5, ["staffeur-ornemaniste"]],
    ["SO-STA-111", "Niche décorative en staff", "Niche préfabriquée encastrée dans cloison ou doublage, raccords enduits.", "U", 468, 10, 180, 180, 3, ["staffeur-ornemaniste"]],
    ["SO-STA-112", "Prise d'empreinte et fabrication de moule silicone", "Relevé d'un ornement existant, moule silicone et contre-moule pour reproduction.", "forfait", 715.5, 10, 390, 140, 6, ["staffeur-ornemaniste"]],
  ],
});
