import { defineCatalog } from "./define";

export const CATALOG_TRAVAUX_PUBLICS = defineCatalog("travaux-publics", {
  "Installation de chantier et études": [
    ["TP-INS-101", "Installation et repli de chantier TP", "Base vie, clôture, panneau de chantier, accès et repli avec nettoyage. Signalisation sur voirie en sus.", "forfait", 1105, 20, 400, 450, 8],
    ["TP-INS-102", "Main d'œuvre en régie, ouvrier TP", "Heure de travail effectif pour travaux hors devis. Engins et fournitures facturés en sus.", "h", 61, 20, 45, 0, 1],
    ["TP-INS-103", "Main d'œuvre en régie, chef d'équipe TP", "Heure de chef d'équipe ou compagnon. Engins et fournitures facturés en sus.", "h", 74, 20, 55, 0, 1],
    ["TP-INS-104", "DT-DICT, marquage et piquetage des réseaux existants", "Déclarations, récépissés exploitants et marquage au sol des réseaux avant terrassement.", "forfait", 240.5, 20, 165, 20, 3],
    ["TP-INS-105", "Détection de réseaux enterrés par géoradar", "Détection électromagnétique et radar, marquage et plan de repérage. Classe A non garantie.", "forfait", 455, 20, 260, 90, 4, ["canalisateur", "monteur-reseaux", "poseur-fibre-optique", "conducteur-engins", "assainissement"]],
    ["TP-INS-106", "Signalisation temporaire avec alternat par feux", "Panneaux temporaires, feux tricolores mobiles, pose, surveillance et repli, par jour.", "jour", 208, 20, 75, 85, 1.5, ["signalisation-routiere", "constructeur-routes", "canalisateur", "monteur-reseaux", "poseur-fibre-optique"]],
    ["TP-INS-107", "Plan de signalisation et demande d'arrêté de circulation", "Plan de balisage, dossier de permission de voirie et demande d'arrêté auprès du gestionnaire.", "forfait", 148.5, 20, 110, 0, 2, ["signalisation-routiere", "constructeur-routes", "canalisateur", "monteur-reseaux", "poseur-fibre-optique"]],
  ],
  "Engins avec chauffeur": [
    ["TP-ENG-101", "Amenée et repli d'engin par porte-engin (≤ 30 km)", "Transport aller-retour de pelle ou chargeuse sur porte-engin avec chauffeur.", "forfait", 533, 20, 110, 300, 2, ["conducteur-engins", "canalisateur", "constructeur-routes", "assainissement", "monteur-reseaux", "forage-puits"]],
    ["TP-ENG-102", "Mini-pelle 5 t avec chauffeur", "Journée de 8 h, godets et carburant compris. Transport compté à part.", "jour", 837.5, 20, 440, 230, 8, ["conducteur-engins", "canalisateur", "assainissement", "monteur-reseaux", "poseur-fibre-optique", "forage-puits"]],
    ["TP-ENG-103", "Pelle 8 t avec chauffeur", "Journée de 8 h, godets et carburant compris. Brise-roche en option.", "jour", 962.5, 20, 440, 330, 8, ["conducteur-engins", "canalisateur", "assainissement", "monteur-reseaux"]],
    ["TP-ENG-104", "Pelle 20 t avec chauffeur", "Journée de 8 h sur chenilles, carburant compris. Transport par porte-engin en sus.", "jour", 1392.5, 20, 464, 650, 8, ["conducteur-engins", "canalisateur", "constructeur-routes"]],
    ["TP-ENG-105", "Tractopelle avec chauffeur", "Journée de 8 h, chargement, petites tranchées et remblais. Carburant compris.", "jour", 900, 20, 440, 280, 8, ["conducteur-engins", "canalisateur", "assainissement", "constructeur-routes"]],
    ["TP-ENG-106", "Chargeuse sur pneus avec chauffeur", "Journée de 8 h, chargement et reprise de matériaux, carburant compris.", "jour", 1075, 20, 440, 420, 8, ["conducteur-engins", "constructeur-routes"]],
    ["TP-ENG-107", "Compacteur tandem 3 t avec chauffeur", "Journée de 8 h de compactage d'enrobés ou de graves, carburant compris.", "jour", 807.5, 20, 416, 230, 8, ["conducteur-engins", "constructeur-routes"]],
    ["TP-ENG-108", "Camion 6x4 benne avec chauffeur", "Heure de camion 26 t pour transport de matériaux ou de déblais, hors redevance de décharge.", "h", 136.5, 20, 55, 50, 1, ["conducteur-engins", "constructeur-routes", "canalisateur", "assainissement"]],
  ],
  "Terrassements et tranchées": [
    ["TP-TER-101", "Déblai de plateforme en terrain ordinaire, mise en dépôt", "Terrassement en pleine masse à la pelle 20 t, chargement ou dépôt sur site. Évacuation en sus.", "m³", 10.5, 20, 4.64, 3.5, 0.08, ["conducteur-engins", "constructeur-routes"]],
    ["TP-TER-102", "Réglage et compactage du fond de forme", "Nivellement à ± 3 cm et compactage au rouleau, essais de plaque non compris.", "m²", 3, 20, 1.65, 0.6, 0.03, ["conducteur-engins", "constructeur-routes"]],
    ["TP-TER-103", "Couche de forme en grave 0/31,5 compactée", "Fourniture, mise en œuvre par couches de 30 cm et compactage. Géotextile compté à part.", "m³", 57, 20, 13.75, 30, 0.25, ["constructeur-routes", "conducteur-engins"]],
    ["TP-TER-104", "Tranchée 0,40 × 0,80 m pour réseaux secs", "Ouverture, lit de sable, remblai compacté et grillage avertisseur. Fourreaux comptés à part.", "ml", 31, 20, 18.2, 5.5, 0.35, ["canalisateur", "monteur-reseaux", "poseur-fibre-optique", "conducteur-engins"]],
    ["TP-TER-105", "Tranchée 0,60 × 1,20 m pour réseaux humides", "Ouverture, lit et enrobage sable, remblai compacté et grillage. Canalisation comptée à part.", "ml", 56, 20, 31.2, 12, 0.6, ["canalisateur", "assainissement", "conducteur-engins"]],
    ["TP-TER-106", "Tranchée profonde 1,50 à 2,50 m avec blindage", "Fouille blindée par caissons, enrobage et remblai compacté par couches. Rabattement de nappe exclu.", "ml", 149.5, 20, 77, 38, 1.4, ["canalisateur", "assainissement", "conducteur-engins"]],
    ["TP-TER-107", "Tranchée sous chaussée, découpe et remblai en grave", "Découpe d'enrobé, terrassement, remblai GNT compacté. Réfection de surface comptée à part.", "ml", 108, 20, 55, 28, 1, ["canalisateur", "monteur-reseaux", "poseur-fibre-optique", "constructeur-routes"]],
    ["TP-TER-108", "Micro-tranchée 10 × 30 cm pour fibre optique", "Sciage à la trancheuse, pose du micro-fourreau et rebouchage au mortier ou à la résine.", "ml", 20.5, 20, 6.96, 9, 0.12, ["poseur-fibre-optique"]],
    ["TP-TER-109", "Plus-value pour terrain rocheux en tranchée", "Fragmentation au brise-roche et purge, au m³ en place.", "m³", 165, 20, 87, 40, 1.5, ["canalisateur", "conducteur-engins", "assainissement", "monteur-reseaux"]],
    ["TP-TER-110", "Évacuation des déblais en décharge (≤ 20 km)", "Chargement, transport et redevance de mise en décharge de terres inertes, au m³ en place.", "m³", 43, 20, 11, 22, 0.2, ["conducteur-engins", "canalisateur", "constructeur-routes", "assainissement"]],
    ["TP-TER-111", "Forage dirigé sous voirie ou obstacle", "Forage horizontal guidé avec tirage de fourreau PEHD Ø ≤ 110. Fosses d'entrée et sortie comprises.", "ml", 188, 20, 49.6, 95, 0.8, ["canalisateur", "poseur-fibre-optique", "monteur-reseaux"]],
  ],
  "Canalisations et branchements": [
    ["TP-CAN-101", "Canalisation PEHD Ø 32 eau potable posée en tranchée", "Tube PN16 en couronne, raccords et grillage bleu. Tranchée comptée à part.", "ml", 10.5, 20, 5.2, 2.8, 0.1, ["canalisateur"]],
    ["TP-CAN-102", "Canalisation PEHD Ø 63 eau potable posée en tranchée", "Tube PN16, raccords électrosoudables ou mécaniques. Tranchée comptée à part.", "ml", 18.5, 20, 7.8, 6.5, 0.15, ["canalisateur"]],
    ["TP-CAN-103", "Canalisation PEHD Ø 110 électrosoudée", "Tube PN16, soudures bout à bout ou manchons électrosoudables. Tranchée comptée à part.", "ml", 47, 20, 19.25, 17, 0.35, ["canalisateur"]],
    ["TP-CAN-104", "Canalisation fonte ductile Ø 100 eau potable", "Tuyaux à emboîtement verrouillé, pièces de raccord et butées béton. Tranchée comptée à part.", "ml", 98, 20, 27.5, 48, 0.5, ["canalisateur"]],
    ["TP-CAN-105", "Collecteur PVC CR8 Ø 160 eaux usées", "Tuyaux à joints, pose à la pente sur lit de sable. Tranchée et regards comptés à part.", "ml", 36, 20, 15.6, 12, 0.3, ["canalisateur", "assainissement"]],
    ["TP-CAN-106", "Collecteur PVC CR8 Ø 315 eaux pluviales", "Tuyaux à joints, pose au laser. Tranchée et regards comptés à part.", "ml", 90.5, 20, 27.5, 42, 0.5, ["canalisateur"]],
    ["TP-CAN-107", "Branchement eau potable particulier (≤ 10 ml)", "Prise en charge, robinet de branchement, tube PEHD et regard compteur. Compteur fourni par le distributeur.", "U", 1118, 20, 440, 420, 8, ["canalisateur"]],
    ["TP-CAN-108", "Branchement EU ou EP sur réseau public (≤ 10 ml)", "Piquage sur collecteur, boîte de branchement en limite et canalisation. Réfection de voirie en sus.", "U", 1391, 20, 550, 520, 10, ["canalisateur", "assainissement"]],
    ["TP-CAN-109", "Regard de visite béton Ø 1000, profondeur ≤ 2 m", "Éléments préfabriqués, cunette, échelons et tampon fonte D400. Terrassement compris.", "U", 1534, 20, 330, 850, 6, ["canalisateur", "assainissement"]],
    ["TP-CAN-110", "Boîte de branchement PVC Ø 315 avec tampon", "Boîte à passage direct ou à décantation, rehausse et tampon fonte. Terrassement compris.", "U", 283.5, 20, 78, 140, 1.5, ["canalisateur", "assainissement"]],
    ["TP-CAN-111", "Avaloir ou bouche d'égout avec grille fonte", "Élément béton, grille C250 ou D400 et raccordement au collecteur.", "U", 541, 20, 156, 260, 3, ["canalisateur", "constructeur-routes"]],
    ["TP-CAN-112", "Caniveau à grille fonte classe C250", "Caniveau béton polymère sur béton de calage, grille verrouillée et raccordement d'about.", "ml", 177.5, 20, 41.6, 95, 0.8, ["canalisateur", "constructeur-routes"]],
    ["TP-CAN-113", "Essais de pression et désinfection de conduite AEP", "Mise en pression, chloration, rinçage et prélèvement pour analyse. Analyse laboratoire comprise.", "forfait", 448.5, 20, 165, 180, 3, ["canalisateur"]],
    ["TP-CAN-114", "Inspection caméra et essai d'étanchéité de collecteur", "Passage caméra, rapport vidéo et test à l'air ou à l'eau par tronçon.", "ml", 4, 20, 2.4, 0.6, 0.04, ["canalisateur", "assainissement"]],
    ["TP-CAN-115", "Réparation de fuite sur conduite d'eau enterrée", "Recherche, terrassement ponctuel, collier ou manchon de réparation et remblai. Enrobé en sus.", "forfait", 663, 20, 330, 180, 6, ["canalisateur"]],
    ["TP-CAN-116", "Curage hydrodynamique de réseau", "Heure d'hydrocureuse avec opérateur, débouchage et nettoyage des canalisations.", "h", 195, 20, 55, 95, 1, ["assainissement", "canalisateur"]],
  ],
  "Assainissement non collectif": [
    ["TP-ANC-101", "Étude de sol et de filière ANC avec tests de perméabilité", "Sondages, tests de perméabilité et dimensionnement de la filière pour dossier SPANC.", "forfait", 494, 20, 300, 80, 5, ["assainissement"]],
    ["TP-ANC-102", "Diagnostic d'installation ANC existante avec rapport", "Ouverture des regards, contrôle des ouvrages et de l'écoulement. Avant vente ou contrôle SPANC.", "forfait", 221, 20, 150, 20, 2.5, ["assainissement"]],
    ["TP-ANC-103", "Fosse toutes eaux 4000 L fournie posée", "Fosse PEHD ou béton, fouille, lit de sable, calage et raccordements. Logement ≤ 5 pièces.", "U", 2340, 10, 550, 1250, 10, ["assainissement"]],
    ["TP-ANC-104", "Fosse toutes eaux 5000 L fournie posée", "Fosse, fouille, calage et raccordements. Logement 6 pièces et plus.", "U", 3003, 10, 660, 1650, 12, ["assainissement"]],
    ["TP-ANC-105", "Tranchées d'épandage à faible profondeur", "Tranchée, gravier lavé, tuyaux d'épandage et géotextile, au mètre de tranchée.", "ml", 62.5, 10, 26, 22, 0.5, ["assainissement"]],
    ["TP-ANC-106", "Filtre à sable vertical non drainé", "Fouille, géotextile, sable siliceux, gravier et répartition, au m² de filtre. Regards compris.", "m²", 159, 10, 62.4, 60, 1.2, ["assainissement"]],
    ["TP-ANC-107", "Filtre à sable vertical drainé", "Filtre étanche avec drains de collecte et regard de bouclage, au m² de filtre.", "m²", 196, 10, 72.8, 78, 1.4, ["assainissement"]],
    ["TP-ANC-108", "Micro-station d'épuration agréée 5 EH fournie posée", "Cuve, fouille, calage, raccordements et alimentation électrique en attente. Mise en service incluse.", "U", 7850, 10, 880, 5400, 16, ["assainissement"]],
    ["TP-ANC-109", "Filtre compact agréé 5 EH fourni posé", "Fosse et filtre à média, fouille, calage et raccordements. Sans électricité.", "U", 9087.5, 10, 770, 6500, 14, ["assainissement"]],
    ["TP-ANC-110", "Poste de relevage eaux usées", "Cuve avec pompe, alarme de niveau, refoulement ≤ 15 ml. Alimentation électrique en attente.", "U", 1664, 10, 330, 950, 6, ["assainissement", "canalisateur"]],
    ["TP-ANC-111", "Ventilation de fosse avec extracteur statique", "Ventilation secondaire en PVC Ø 100 jusqu'au faîtage et extracteur. Percement de toiture compris.", "forfait", 478.5, 10, 208, 160, 4, ["assainissement"]],
    ["TP-ANC-112", "Vidange de fosse toutes eaux ≤ 3 m³", "Camion hydrocureur, vidange, nettoyage et bordereau de suivi de traitement des matières.", "forfait", 400.5, 10, 78, 230, 1.5, ["assainissement"]],
    ["TP-ANC-113", "Neutralisation d'une ancienne fosse septique", "Vidange, désinfection, perforation du fond et comblement en sable ou matériaux inertes.", "U", 452.5, 10, 208, 140, 4, ["assainissement"]],
    ["TP-ANC-114", "Raccordement au tout-à-l'égout avec mise hors service de fosse", "Déviation de la sortie maison vers boîte de branchement, neutralisation de la fosse. ≤ 15 ml.", "forfait", 1261, 10, 520, 450, 10, ["assainissement", "canalisateur"]],
  ],
  "Chaussées et revêtements": [
    ["TP-ROU-101", "Rabotage d'enrobé ép. 5 cm", "Fraisage à la raboteuse, chargement et évacuation des fraisats en centre de recyclage.", "m²", 5, 20, 1.16, 2.8, 0.02, ["constructeur-routes", "conducteur-engins"]],
    ["TP-ROU-102", "Découpe d'enrobé ou de béton à la scie", "Sciage franc avant démolition ou tranchée, profondeur ≤ 10 cm.", "ml", 7, 20, 4.16, 1.2, 0.08, ["constructeur-routes", "canalisateur", "monteur-reseaux", "poseur-fibre-optique"]],
    ["TP-ROU-103", "Démolition de chaussée ou trottoir en enrobé", "Démolition à la pelle, chargement et évacuation en centre agréé.", "m²", 15, 20, 5.5, 6, 0.1, ["constructeur-routes", "conducteur-engins"]],
    ["TP-ROU-104", "Couche de fondation GNT 0/31,5 ép. 25 cm", "Fourniture, mise en œuvre au niveleur ou à la pelle et compactage.", "m²", 14.5, 20, 3.3, 8, 0.06, ["constructeur-routes", "conducteur-engins"]],
    ["TP-ROU-105", "Couche d'accrochage à l'émulsion de bitume", "Répandage à la rampe ou à la lance avant enrobé, dosage 300 à 400 g/m².", "m²", 1.5, 20, 0.52, 0.7, 0.01, ["constructeur-routes"]],
    ["TP-ROU-106", "Enrobé BB 0/10 ép. 5 cm mis en œuvre manuellement", "Petites surfaces et accès, réglage au râteau et compactage au rouleau. Couche d'accrochage en sus.", "m²", 25.5, 20, 7.8, 12, 0.15, ["constructeur-routes"]],
    ["TP-ROU-107", "Enrobé BB 0/10 ép. 6 cm au finisseur (≥ 500 m²)", "Mise en œuvre au finisseur et compactage au tandem. Couche d'accrochage en sus.", "m²", 20.5, 20, 1.74, 14, 0.03, ["constructeur-routes", "conducteur-engins"]],
    ["TP-ROU-108", "Enduit superficiel bicouche gravillonné", "Émulsion et deux couches de gravillons, cylindrage et balayage des rejets.", "m²", 7, 20, 1.65, 3.8, 0.03, ["constructeur-routes"]],
    ["TP-ROU-109", "Réfection de tranchée en enrobé", "Découpe des bords, accrochage et enrobé à chaud ép. 6 cm compacté, joint de reprise.", "m²", 41, 20, 15.6, 16, 0.3, ["constructeur-routes", "canalisateur", "monteur-reseaux", "poseur-fibre-optique"]],
    ["TP-ROU-110", "Bouchage de nids-de-poule en enrobé à chaud", "Purge, accrochage, enrobé compacté et joint d'étanchéité.", "m²", 45, 20, 20.8, 14, 0.4, ["constructeur-routes"]],
    ["TP-ROU-111", "Bordure béton T2 posée sur béton", "Bordure de trottoir, fondation et contrebutée béton, joints au mortier.", "ml", 42.5, 20, 20.8, 12, 0.4, ["constructeur-routes"]],
    ["TP-ROU-112", "Caniveau béton préfabriqué CC1", "Éléments posés sur béton de fondation, pente et joints au mortier.", "ml", 44, 20, 20.8, 13, 0.4, ["constructeur-routes", "canalisateur"]],
    ["TP-ROU-113", "Pavés béton autobloquants 6 cm sur lit de sable", "Lit de pose réglé, pavés, sable de jointoiement et compactage. Fondation en sus.", "m²", 67.5, 20, 30, 22, 0.6, ["constructeur-routes"]],
    ["TP-ROU-114", "Béton désactivé ép. 12 cm", "Béton fibré, désactivant de surface, lavage et joints de retrait. Fondation en sus.", "m²", 79.5, 20, 26, 35, 0.5, ["constructeur-routes"]],
    ["TP-ROU-115", "Mise à niveau de tampon ou de bouche à clé", "Découpe, rehausse du cadre, calage au mortier rapide et reprise d'enrobé.", "U", 213, 20, 104, 60, 2, ["constructeur-routes", "canalisateur"]],
  ],
  "Réseaux secs et éclairage public": [
    ["TP-RES-101", "Fourreau TPC Ø 63 posé en tranchée", "Fourreau aiguillé avec raccords, au mètre. Tranchée comptée à part.", "ml", 5.5, 20, 2, 2.4, 0.04, ["monteur-reseaux", "poseur-fibre-optique", "canalisateur"]],
    ["TP-RES-102", "Fourreau TPC Ø 90 à 160 posé en tranchée", "Fourreau aiguillé avec raccords et bouchons d'extrémité. Tranchée comptée à part.", "ml", 9, 20, 2.5, 4.5, 0.05, ["monteur-reseaux", "poseur-fibre-optique"]],
    ["TP-RES-103", "Câble BT souterrain alu 3 × 150 + 70 tiré en fourreau", "Déroulage au treuil ou à la main, repérage et protection des extrémités. Jonctions en sus.", "ml", 32, 20, 6.6, 18, 0.12, ["monteur-reseaux"]],
    ["TP-RES-104", "Câble BT souterrain alu 4 × 35 de branchement", "Câble tiré en fourreau jusqu'au coffret. Raccordements compris.", "ml", 14, 20, 4.4, 6.5, 0.08, ["monteur-reseaux"]],
    ["TP-RES-105", "Jonction ou dérivation BT souterraine", "Boîte de jonction ou de dérivation à résine, préparation et raccordement des conducteurs.", "U", 476, 20, 186, 180, 3, ["monteur-reseaux"]],
    ["TP-RES-106", "Coffret de coupure et protection en limite de propriété", "Coffret en niche ou sur socle, fixation et raccordements. Raccordement réseau par le gestionnaire.", "U", 702, 20, 220, 320, 4, ["monteur-reseaux"]],
    ["TP-RES-107", "Implantation de poteau béton 9 m", "Fouille, poteau, levage par engin et calage béton.", "U", 1014, 20, 220, 560, 4, ["monteur-reseaux", "poseur-fibre-optique"]],
    ["TP-RES-108", "Massif béton pour candélabre", "Fouille, coffrage, tiges d'ancrage et fourreau d'attente.", "U", 291, 20, 104, 120, 2, ["monteur-reseaux"]],
    ["TP-RES-109", "Candélabre d'éclairage public 6 m LED raccordé", "Mât, crosse, luminaire LED et coffret de pied, raccordement au réseau d'éclairage. Massif en sus.", "U", 2249, 20, 330, 1400, 6, ["monteur-reseaux"]],
  ],
  "Fibre optique et télécoms": [
    ["TP-FIB-101", "Chambre de tirage L1T avec tampon", "Chambre préfabriquée, fouille, calage et raccordement des fourreaux.", "U", 437, 20, 156, 180, 3, ["poseur-fibre-optique", "monteur-reseaux"]],
    ["TP-FIB-102", "Chambre de tirage L2T avec tampon", "Chambre préfabriquée, fouille, calage et raccordement des fourreaux.", "U", 686.5, 20, 208, 320, 4, ["poseur-fibre-optique", "monteur-reseaux"]],
    ["TP-FIB-103", "Aiguillage et désobstruction de fourreau existant", "Passage d'aiguille, mandrinage et pose de fil de tirage.", "ml", 3, 20, 2.2, 0.3, 0.04, ["poseur-fibre-optique", "monteur-reseaux"]],
    ["TP-FIB-104", "Tirage de câble fibre en conduite existante", "Tirage manuel ou au treuil avec lubrifiant, lovage en chambre.", "ml", 2.5, 20, 1.1, 0.9, 0.02, ["poseur-fibre-optique"]],
    ["TP-FIB-105", "Pose de câble fibre en aérien sur appuis existants", "Câble autoporté, pinces d'ancrage et de suspension, lovage sur poteau.", "ml", 4, 20, 2.2, 1, 0.04, ["poseur-fibre-optique"]],
    ["TP-FIB-106", "Point de branchement optique posé et raccordé", "Boîtier en chambre, façade ou poteau, préparation du câble et organisation des cassettes.", "U", 357.5, 20, 155, 120, 2.5, ["poseur-fibre-optique"]],
    ["TP-FIB-107", "Soudure de fibre optique par fusion (par fibre)", "Dénudage, clivage, soudure et protection en cassette.", "U", 10.5, 20, 6.2, 1.5, 0.1, ["poseur-fibre-optique"]],
    ["TP-FIB-108", "Mesure réflectométrique avec rapport (par fibre)", "Mesure bidirectionnelle et rapport de recette par fibre.", "U", 13, 20, 9.75, 0, 0.15, ["poseur-fibre-optique"]],
    ["TP-FIB-109", "Adduction télécom souterraine privative (≤ 15 ml)", "Tranchée, fourreau aiguillé jusqu'au logement et regard en limite. Raccordement opérateur exclu.", "forfait", 387.5, 10, 208, 90, 4, ["poseur-fibre-optique", "monteur-reseaux"]],
    ["TP-FIB-110", "Réparation de câble fibre sectionné", "Ouverture, pose d'un manchon de raccordement, soudures et mesures. ≤ 72 fibres.", "forfait", 938.5, 20, 372, 350, 6, ["poseur-fibre-optique"]],
    ["TP-FIB-111", "Dossier de recette et plans de récolement réseau", "Plans, synoptiques, fiches de soudures et mesures au format du maître d'ouvrage.", "forfait", 324, 20, 240, 0, 4, ["poseur-fibre-optique", "monteur-reseaux"]],
  ],
  "Forages et puits": [
    ["TP-FOR-101", "Amenée et repli de foreuse", "Transport de l'atelier de forage, installation et repli. Accès praticable requis.", "forfait", 811, 20, 174, 450, 3, ["forage-puits"]],
    ["TP-FOR-102", "Déclaration de forage domestique et dossier administratif", "Déclaration en mairie et auprès des services de l'État, implantation selon distances réglementaires.", "forfait", 111.5, 20, 82.5, 0, 1.5, ["forage-puits"]],
    ["TP-FOR-103", "Forage d'eau Ø 150-200 mm en terrain meuble", "Forage au rotary, au mètre linéaire, gestion des cuttings sur place.", "ml", 88.5, 20, 30, 38, 0.5, ["forage-puits"]],
    ["TP-FOR-104", "Forage d'eau en terrain rocheux au marteau fond de trou", "Forage en roche dure, au mètre linéaire, compresseur compris.", "ml", 118.5, 20, 36, 55, 0.6, ["forage-puits"]],
    ["TP-FOR-105", "Tubage PVC pression Ø 125 plein ou crépiné", "Fourniture et pose du tubage avec centreurs, au mètre.", "ml", 31, 20, 5.8, 18, 0.1, ["forage-puits"]],
    ["TP-FOR-106", "Massif filtrant et cimentation annulaire de tête", "Gravier calibré en face des crépines et bouchon d'étanchéité au ciment en tête de forage.", "forfait", 590, 20, 174, 280, 3, ["forage-puits"]],
    ["TP-FOR-107", "Développement et essai de pompage", "Nettoyage à l'air, pompage d'essai et rapport de débit et de niveau.", "forfait", 457.5, 20, 232, 120, 4, ["forage-puits"]],
    ["TP-FOR-108", "Tête de forage étanche avec regard", "Capot étanche, regard de protection et dalle béton anti-infiltration.", "U", 377, 20, 110, 180, 2, ["forage-puits"]],
    ["TP-FOR-109", "Pompe immergée 4\" 0,75 kW avec câble ≤ 40 m", "Pompe multicellulaire, câble immergé, corde inox et colonne de refoulement. Coffret compté à part.", "U", 1102.5, 20, 232, 650, 4, ["forage-puits"]],
    ["TP-FOR-110", "Pompe immergée 4\" 1,5 kW avec câble ≤ 60 m", "Pompe multicellulaire grande profondeur, câble, colonne et clapet. Coffret compté à part.", "U", 1639, 20, 261, 1050, 4.5, ["forage-puits"]],
    ["TP-FOR-111", "Coffret de commande de pompe avec sécurité manque d'eau", "Coffret de protection moteur, sonde de niveau et pressostat, raccordement.", "U", 529, 20, 87, 320, 1.5, ["forage-puits"]],
    ["TP-FOR-112", "Réservoir à vessie 100 L avec raccordements", "Réservoir, manomètre, vanne et raccordement en local technique.", "U", 507, 20, 110, 280, 2, ["forage-puits"]],
    ["TP-FOR-113", "Remontée et remplacement de pompe immergée (main d'œuvre)", "Remontée de la colonne, échange de la pompe fournie, redescente et essais.", "forfait", 353.5, 20, 232, 40, 4, ["forage-puits"]],
    ["TP-FOR-114", "Puits busé Ø 1000 creusé à la pelle", "Creusement, buses béton, gravier de fond et rehausse, au mètre de profondeur.", "ml", 377, 20, 110, 180, 2, ["forage-puits", "conducteur-engins"]],
    ["TP-FOR-115", "Curage et nettoyage de puits", "Vidange, enlèvement des dépôts, brossage des parois et désinfection.", "forfait", 483.5, 20, 312, 60, 6, ["forage-puits"]],
    ["TP-FOR-116", "Analyse de potabilité de l'eau (prélèvement compris)", "Prélèvement et analyse en laboratoire agréé, transmission des résultats.", "forfait", 283, 20, 27.5, 190, 0.5, ["forage-puits"]],
  ],
  "Signalisation routière": [
    ["TP-SIG-101", "Marquage de ligne en peinture largeur 12 cm", "Pré-marquage et application à la machine, continue ou discontinue.", "ml", 2, 20, 1.04, 0.35, 0.02, ["signalisation-routiere"]],
    ["TP-SIG-102", "Passage piéton en résine à chaud", "Bandes en résine thermoplastique avec billes de verre, au m² peint.", "m²", 49, 20, 15.6, 22, 0.3, ["signalisation-routiere"]],
    ["TP-SIG-103", "Marquage de place de stationnement (par place)", "Traçage des limites d'une place standard en peinture routière.", "U", 25.5, 20, 15.6, 4, 0.3, ["signalisation-routiere"]],
    ["TP-SIG-104", "Marquage de place PMR avec logo", "Traçage, logo et zone hachurée en peinture ou résine.", "U", 86.5, 20, 41.6, 25, 0.8, ["signalisation-routiere"]],
    ["TP-SIG-105", "Flèche ou pictogramme au sol", "Application au pochoir en peinture routière.", "U", 28, 20, 15.6, 6, 0.3, ["signalisation-routiere"]],
    ["TP-SIG-106", "Effacement de marquage existant", "Effacement par rabotage léger ou grenaillage, nettoyage.", "m²", 29, 20, 16.5, 6, 0.3, ["signalisation-routiere", "constructeur-routes"]],
    ["TP-SIG-107", "Panneau de police Ø 650 sur mât", "Panneau, mât galvanisé, fixations et massif béton.", "U", 309.5, 20, 78, 160, 1.5, ["signalisation-routiere"]],
    ["TP-SIG-108", "Panneau directionnel ≤ 1,5 m² sur deux mâts", "Panneau, mâts, fixations et massifs béton.", "U", 827, 20, 156, 480, 3, ["signalisation-routiere"]],
    ["TP-SIG-109", "Coussin berlinois préfabriqué", "Éléments en caoutchouc fixés par chevilles chimiques, signalisation verticale non comprise.", "U", 1760, 20, 208, 1200, 4, ["signalisation-routiere", "constructeur-routes"]],
    ["TP-SIG-110", "Ralentisseur trapézoïdal en enrobé", "Plateau en enrobé avec rampes, marquage et réglage. Signalisation verticale non comprise.", "U", 2678, 20, 660, 1400, 12, ["signalisation-routiere", "constructeur-routes"]],
    ["TP-SIG-111", "Potelet ou borne anti-stationnement", "Potelet acier ou fonte scellé dans un massif.", "U", 99, 20, 31.2, 45, 0.6, ["signalisation-routiere", "constructeur-routes"]],
    ["TP-SIG-112", "Miroir de circulation Ø 600 sur mât", "Miroir, mât et massif, orientation sur site.", "U", 335.5, 20, 78, 180, 1.5, ["signalisation-routiere"]],
    ["TP-SIG-113", "Glissière de sécurité métallique", "Glissière simple sur supports battus ou fixés, extrémités comptées à part.", "ml", 87, 20, 22, 45, 0.4, ["signalisation-routiere", "constructeur-routes"]],
  ],
});
