/**
 * Catalogue d'ouvrages génériques BTP — prix indicatifs marché France 2025-2026.
 * Descriptifs originaux Soline ; ordres de grandeur courants (pas de reprise de bases éditeurs).
 */
import type { PlatformWorkItem } from "@/lib/work-library/platform-catalog-types";
import { PLATFORM_WORK_CATALOG_EXTRA } from "@/lib/work-library/platform-catalog-data-extra";

function item(
  partial: Omit<PlatformWorkItem, "tradeIds"> & { tradeIds?: string[] },
): PlatformWorkItem {
  return { tradeIds: [], ...partial };
}

export const PLATFORM_WORK_CATALOG: PlatformWorkItem[] = [
  // —— Gros œuvre ——
  item({
    id: "go-mur-parpaing",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["macon", "constructeur-beton-arme"],
    workCategory: "Maçonnerie",
    reference: "GO-MAC-001",
    title: "Mur en parpaings creux 20×20×50",
    description: "Montage mur parpaing + joints + chaînages, hors fondations",
    unit: "m²",
    unitPriceHt: 78,
    defaultVatRate: 10,
    laborCost: 48,
    materialCost: 22,
    estimatedHours: 1.1,
  }),
  item({
    id: "go-dalle-beton",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["macon", "coffreur-bancheur"],
    workCategory: "Maçonnerie",
    reference: "GO-MAC-002",
    title: "Dalle béton armé 15 cm",
    description: "Coffrage, ferraillage standard, coulage et cure",
    unit: "m²",
    unitPriceHt: 95,
    defaultVatRate: 10,
    laborCost: 55,
    materialCost: 32,
    estimatedHours: 1.4,
  }),
  item({
    id: "go-seuil-fondations",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["macon", "terrassier"],
    workCategory: "Fondations",
    reference: "GO-FON-001",
    title: "Semelle filante béton",
    description: "Tranchée, ferraillage, coulage semelle 50×30 cm environ",
    unit: "ml",
    unitPriceHt: 120,
    defaultVatRate: 10,
    laborCost: 65,
    materialCost: 45,
    estimatedHours: 1.6,
  }),
  item({
    id: "go-demol-cloison",
    tradeCategoryId: "gros-oeuvre",
    workCategory: "Démolition",
    reference: "GO-DEM-001",
    title: "Démolition cloison briques",
    description: "Dépose, évacuation gravats, hors traitement plomb/amiante",
    unit: "m²",
    unitPriceHt: 32,
    defaultVatRate: 10,
    laborCost: 26,
    materialCost: 4,
    estimatedHours: 0.7,
  }),
  item({
    id: "go-terrassement",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["terrassier", "demolisseur"],
    workCategory: "Terrassement",
    reference: "GO-TER-001",
    title: "Terrassement en rigole / fouille",
    description: "Décaissement mécanique, évacuation terres, profondeur ≤ 1,2 m",
    unit: "m³",
    unitPriceHt: 38,
    defaultVatRate: 20,
    laborCost: 28,
    materialCost: 6,
    estimatedHours: 0.5,
  }),
  item({
    id: "go-enduit-facade",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["facadier-ravaleur", "macon"],
    workCategory: "Façade",
    reference: "GO-FAC-001",
    title: "Enduit monocouche sur parpaing",
    description: "Préparation support + projection/enduit monocouche",
    unit: "m²",
    unitPriceHt: 42,
    defaultVatRate: 10,
    laborCost: 26,
    materialCost: 12,
    estimatedHours: 0.65,
  }),

  // —— Couverture ——
  item({
    id: "cov-tuile-mecanique",
    tradeCategoryId: "couverture",
    tradeIds: ["couvreur", "couvreur-zingueur"],
    workCategory: "Couverture",
    reference: "COV-001",
    title: "Pose tuiles mécaniques",
    description: "Tuiles + liteaux, hors échafaudage complexe",
    unit: "m²",
    unitPriceHt: 85,
    defaultVatRate: 10,
    laborCost: 48,
    materialCost: 28,
    estimatedHours: 1.2,
  }),
  item({
    id: "cov-zinc-gouttiere",
    tradeCategoryId: "couverture",
    tradeIds: ["zingueur", "poseur-gouttieres"],
    workCategory: "Zinguerie",
    reference: "COV-002",
    title: "Gouttière zinc demi-ronde",
    description: "Fourniture + pose gouttière zinc avec crochets",
    unit: "ml",
    unitPriceHt: 95,
    defaultVatRate: 10,
    laborCost: 45,
    materialCost: 38,
    estimatedHours: 0.9,
  }),
  item({
    id: "cov-etancheite-toit",
    tradeCategoryId: "couverture",
    tradeIds: ["couvreur", "etancheur"],
    workCategory: "Étanchéité",
    reference: "COV-003",
    title: "Réfection étanchéité toiture terrasse",
    description: "Dépose ancienne étanchéité + membrane bitume ou EPDM",
    unit: "m²",
    unitPriceHt: 110,
    defaultVatRate: 10,
    laborCost: 55,
    materialCost: 42,
    estimatedHours: 1.3,
  }),
  item({
    id: "cov-demoussage",
    tradeCategoryId: "couverture",
    tradeIds: ["nettoyage-toiture", "couvreur"],
    workCategory: "Entretien",
    reference: "COV-004",
    title: "Démoussage toiture",
    description: "Nettoyage HP + traitement anti-mousse",
    unit: "m²",
    unitPriceHt: 18,
    defaultVatRate: 20,
    laborCost: 12,
    materialCost: 3,
    estimatedHours: 0.25,
  }),

  // —— Second œuvre ——
  item({
    id: "so-cloison-ba13",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["plaquiste", "platrier-plaquiste", "poseur-isolation"],
    workCategory: "Plâtrerie",
    reference: "SO-PLA-001",
    title: "Cloison placo BA13 sur ossature 72/48",
    description: "Montage ossature + 1 BA13 + laine 45 mm",
    unit: "m²",
    unitPriceHt: 68,
    defaultVatRate: 10,
    laborCost: 42,
    materialCost: 18,
    estimatedHours: 1.2,
  }),
  item({
    id: "so-doublage",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["plaquiste", "poseur-isolation"],
    workCategory: "Plâtrerie",
    reference: "SO-PLA-002",
    title: "Doublage collé BA13 + isolant",
    description: "Collage rails + polystyrène 40 mm + BA13",
    unit: "m²",
    unitPriceHt: 52,
    defaultVatRate: 10,
    laborCost: 32,
    materialCost: 16,
    estimatedHours: 0.9,
  }),
  item({
    id: "so-peinture-murs",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["peintre-batiment"],
    workCategory: "Peinture",
    reference: "SO-PEI-001",
    title: "Peinture murs acrylique 2 couches",
    description: "Préparation légère + 2 couches acrylique mat",
    unit: "m²",
    unitPriceHt: 24,
    defaultVatRate: 10,
    laborCost: 15,
    materialCost: 5,
    estimatedHours: 0.45,
  }),
  item({
    id: "so-carrelage-sol",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["carreleur", "carreleur-mosaiste"],
    workCategory: "Carrelage",
    reference: "SO-CAR-001",
    title: "Carrelage sol grès cérame 60×60",
    description: "Pose collée + joints, support préparé",
    unit: "m²",
    unitPriceHt: 75,
    defaultVatRate: 10,
    laborCost: 42,
    materialCost: 28,
    estimatedHours: 1.1,
  }),
  item({
    id: "so-parquet-flottant",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["parqueteur", "solier-moquettiste"],
    workCategory: "Sols",
    reference: "SO-SOL-001",
    title: "Parquet stratifié flottant",
    description: "Sous-couche + pose flottante + plinthes",
    unit: "m²",
    unitPriceHt: 45,
    defaultVatRate: 10,
    laborCost: 22,
    materialCost: 18,
    estimatedHours: 0.6,
  }),
  item({
    id: "so-menuiserie-interieure",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["menuisier-bois", "menuisier-agenceur"],
    workCategory: "Menuiserie",
    reference: "SO-MEN-001",
    title: "Pose porte intérieure postformée",
    description: "Fourniture porte standard + pose + quincaillerie",
    unit: "U",
    unitPriceHt: 280,
    defaultVatRate: 10,
    laborCost: 95,
    materialCost: 145,
    estimatedHours: 2,
  }),

  // —— Plomberie & chauffage ——
  item({
    id: "pc-wc-suspendu",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["plombier", "installateur-sanitaire", "plombier-chauffagiste"],
    workCategory: "Sanitaire",
    reference: "PC-SAN-001",
    title: "Remplacement WC suspendu",
    description: "Dépose, bâti-support, WC, robinet, raccordements",
    unit: "U",
    unitPriceHt: 480,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 220,
    estimatedHours: 3.5,
  }),
  item({
    id: "pc-lavabo",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["plombier", "installateur-sanitaire"],
    workCategory: "Sanitaire",
    reference: "PC-SAN-002",
    title: "Pose lavabo avec robinetterie",
    description: "Lavabo céramique + robinet + siphon + raccords",
    unit: "U",
    unitPriceHt: 320,
    defaultVatRate: 10,
    laborCost: 120,
    materialCost: 140,
    estimatedHours: 2,
  }),
  item({
    id: "pc-chauffe-eau",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["plombier-chauffagiste", "chauffagiste", "plombier"],
    workCategory: "Chauffage",
    reference: "PC-CHA-001",
    title: "Remplacement chauffe-eau électrique 200 L",
    description: "Dépose ancien, pose vertical, raccordements",
    unit: "U",
    unitPriceHt: 890,
    defaultVatRate: 10,
    laborCost: 220,
    materialCost: 520,
    estimatedHours: 4,
  }),
  item({
    id: "pc-radiateur",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["chauffagiste", "plombier-chauffagiste"],
    workCategory: "Chauffage",
    reference: "PC-CHA-002",
    title: "Pose radiateur eau chaude",
    description: "Radiateur panneau + robinetterie + raccordement circuit",
    unit: "U",
    unitPriceHt: 420,
    defaultVatRate: 10,
    laborCost: 150,
    materialCost: 210,
    estimatedHours: 2.5,
  }),
  item({
    id: "pc-pac-air-eau",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["chauffagiste", "climaticien", "installateur-pompe-a-chaleur"],
    workCategory: "Chauffage",
    reference: "PC-PAC-001",
    title: "Installation PAC air/eau (mono-split)",
    description: "Unité extérieure + module intérieur, liaisons, mise en service",
    unit: "forfait",
    unitPriceHt: 8500,
    defaultVatRate: 5.5,
    laborCost: 2200,
    materialCost: 5200,
    estimatedHours: 24,
  }),
  item({
    id: "pc-debouchage",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["plombier"],
    workCategory: "Dépannage",
    reference: "PC-DEP-001",
    title: "Débouchage canalisation",
    description: "Intervention manuelle ou furet, canalisation accessible",
    unit: "forfait",
    unitPriceHt: 130,
    defaultVatRate: 20,
    laborCost: 95,
    materialCost: 8,
    estimatedHours: 1,
  }),

  // —— Électricité ——
  item({
    id: "el-point-lumiere",
    tradeCategoryId: "electricite",
    tradeIds: ["electricien"],
    workCategory: "Électricité",
    reference: "EL-001",
    title: "Point lumineux DCL",
    description: "Boîte DCL + câblage + connexion",
    unit: "U",
    unitPriceHt: 98,
    defaultVatRate: 10,
    laborCost: 58,
    materialCost: 22,
    estimatedHours: 1,
  }),
  item({
    id: "el-prise-16a",
    tradeCategoryId: "electricite",
    tradeIds: ["electricien"],
    workCategory: "Électricité",
    reference: "EL-002",
    title: "Prise de courant 16 A encastrée",
    description: "Création prise 2P+T avec saignée ou gaine ICTA",
    unit: "U",
    unitPriceHt: 78,
    defaultVatRate: 10,
    laborCost: 48,
    materialCost: 15,
    estimatedHours: 0.75,
  }),
  item({
    id: "el-tableau",
    tradeCategoryId: "electricite",
    tradeIds: ["electricien", "electricien-industriel"],
    workCategory: "Électricité",
    reference: "EL-003",
    title: "Tableau électrique 2 rangées",
    description: "Tableau pré-équipé + disjoncteurs + mise aux normes",
    unit: "U",
    unitPriceHt: 650,
    defaultVatRate: 10,
    laborCost: 220,
    materialCost: 320,
    estimatedHours: 5,
  }),
  item({
    id: "el-borne-irve",
    tradeCategoryId: "electricite",
    tradeIds: ["installateur-irve", "electricien"],
    workCategory: "IRVE",
    reference: "EL-IRVE-001",
    title: "Borne de recharge véhicule 7,4 kW",
    description: "Borne wallbox + protection dédiée + câblage",
    unit: "U",
    unitPriceHt: 1200,
    defaultVatRate: 20,
    laborCost: 350,
    materialCost: 680,
    estimatedHours: 6,
  }),

  // —— Énergies renouvelables ——
  item({
    id: "enr-pv-3kw",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["installateur-photovoltaique"],
    workCategory: "Photovoltaïque",
    reference: "ENR-PV-001",
    title: "Installation photovoltaïque 3 kWc",
    description: "8 panneaux + onduleur + pose sur toiture tuile",
    unit: "forfait",
    unitPriceHt: 7200,
    defaultVatRate: 20,
    laborCost: 1800,
    materialCost: 4500,
    estimatedHours: 20,
  }),
  item({
    id: "enr-ite",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["specialiste-ite"],
    workCategory: "Isolation",
    reference: "ENR-ITE-001",
    title: "Isolation thermique extérieure polystyrène 140 mm",
    description: "PSE + enduit, hors échafaudage lourd",
    unit: "m²",
    unitPriceHt: 145,
    defaultVatRate: 5.5,
    laborCost: 55,
    materialCost: 72,
    estimatedHours: 1.2,
  }),

  // —— Menuiseries extérieures ——
  item({
    id: "mex-fenetre-pvc",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["menuisier-pvc-alu", "poseur-fenetres"],
    workCategory: "Menuiseries",
    reference: "MEX-FEN-001",
    title: "Fenêtre PVC double vitrage 120×120",
    description: "Dépose ancienne fenêtre + pose + étanchéité",
    unit: "U",
    unitPriceHt: 580,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 320,
    estimatedHours: 3,
  }),
  item({
    id: "mex-porte-garage",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["poseur-porte-garage", "serrurier-metallier"],
    workCategory: "Menuiseries",
    reference: "MEX-PG-001",
    title: "Porte de garage sectionnelle",
    description: "Porte 2,4×2 m + rails + motorisation standard",
    unit: "U",
    unitPriceHt: 2200,
    defaultVatRate: 10,
    laborCost: 450,
    materialCost: 1450,
    estimatedHours: 8,
  }),

  // —— Aménagement extérieur ——
  item({
    id: "ext-terrasse-bois",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["poseur-terrasse", "paysagiste"],
    workCategory: "Terrasse",
    reference: "EXT-TER-001",
    title: "Terrasse bois composite",
    description: "Lambourdes + lames composite sur plots réglables",
    unit: "m²",
    unitPriceHt: 125,
    defaultVatRate: 20,
    laborCost: 48,
    materialCost: 62,
    estimatedHours: 1.2,
  }),
  item({
    id: "ext-cloture",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["cloturiste", "poseur-portails-clotures"],
    workCategory: "Clôture",
    reference: "EXT-CLO-001",
    title: "Clôture panneaux rigides",
    description: "Panneaux 1,53 m + poteaux béton + portillon",
    unit: "ml",
    unitPriceHt: 95,
    defaultVatRate: 20,
    laborCost: 38,
    materialCost: 48,
    estimatedHours: 0.9,
  }),

  // —— Rénovation ——
  item({
    id: "ren-humidite",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["traitement-humidite"],
    workCategory: "Traitement",
    reference: "REN-HUM-001",
    title: "Injection résine contre remontées capillaires",
    description: "Forage + injection barrière horizontale",
    unit: "ml",
    unitPriceHt: 85,
    defaultVatRate: 10,
    laborCost: 45,
    materialCost: 28,
    estimatedHours: 1,
  }),
  item({
    id: "ren-renovation-globale",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["renovation-tous-corps-etat"],
    workCategory: "Rénovation",
    reference: "REN-001",
    title: "Forfait rénovation pièce humide complète",
    description: "Dépose, placo, carrelage, plomberie, électricité — ordre de grandeur",
    unit: "forfait",
    unitPriceHt: 8500,
    defaultVatRate: 10,
    laborCost: 4200,
    materialCost: 3200,
    estimatedHours: 60,
  }),

  // —— Autre / transversal (catégorie autre uniquement) ——
  item({
    id: "aut-depannage",
    tradeCategoryId: "autre",
    tradeIds: ["autre"],
    workCategory: "Dépannage",
    reference: "AUT-001",
    title: "Intervention dépannage forfait 1 h",
    description: "Déplacement + 1 h main-d'œuvre, hors fournitures",
    unit: "forfait",
    unitPriceHt: 95,
    defaultVatRate: 20,
    laborCost: 75,
    materialCost: 5,
    estimatedHours: 1,
  }),
  item({
    id: "aut-devis-hors-catalogue",
    tradeCategoryId: "autre",
    tradeIds: ["autre"],
    workCategory: "Prestation",
    reference: "AUT-002",
    title: "Prestation sur mesure (base horaire)",
    description: "Main-d'œuvre qualifiée, fournitures en sus",
    unit: "h",
    unitPriceHt: 55,
    defaultVatRate: 20,
    laborCost: 55,
    materialCost: 0,
    estimatedHours: 1,
  }),

  ...PLATFORM_WORK_CATALOG_EXTRA,
];
