/**
 * Extension du catalogue Soline — corps d'état complémentaires et métiers non couverts.
 * Prix indicatifs marché France 2025-2026, descriptifs originaux.
 */
import type { PlatformWorkItem } from "@/lib/work-library/platform-catalog-types";

function item(
  partial: Omit<PlatformWorkItem, "tradeIds"> & { tradeIds?: string[] },
): PlatformWorkItem {
  return { tradeIds: [], ...partial };
}

export const PLATFORM_WORK_CATALOG_EXTRA: PlatformWorkItem[] = [
  // —— Gros œuvre (compléments) ——
  item({
    id: "go-ferraillage-dalle",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["ferrailleur", "constructeur-beton-arme"],
    workCategory: "Ferraillage",
    reference: "GO-FER-001",
    title: "Ferraillage dalle béton armé",
    description: "Pose treillis soudé + liens + cales, hors coulage béton",
    unit: "m²",
    unitPriceHt: 28,
    defaultVatRate: 10,
    laborCost: 22,
    materialCost: 4,
    estimatedHours: 0.5,
  }),
  item({
    id: "go-charpente-bois",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["charpentier-bois"],
    workCategory: "Charpente",
    reference: "GO-CHA-001",
    title: "Charpente traditionnelle fermettes",
    description: "Fermes + pannes + liteaux, toiture simple",
    unit: "m²",
    unitPriceHt: 72,
    defaultVatRate: 10,
    laborCost: 48,
    materialCost: 18,
    estimatedHours: 1.1,
  }),
  item({
    id: "go-charpente-metallique",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["charpentier-metallique"],
    workCategory: "Charpente",
    reference: "GO-CHA-002",
    title: "Ossature métallique légère",
    description: "Poutres IPN + pannes + assemblages boulonnés",
    unit: "m²",
    unitPriceHt: 95,
    defaultVatRate: 10,
    laborCost: 55,
    materialCost: 32,
    estimatedHours: 1.3,
  }),
  item({
    id: "go-etancheite-sous-sol",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["etancheur"],
    workCategory: "Étanchéité",
    reference: "GO-ETA-001",
    title: "Étanchéité murs enterrés bitume",
    description: "Préparation + membrane bitumineuse + protection",
    unit: "m²",
    unitPriceHt: 58,
    defaultVatRate: 10,
    laborCost: 32,
    materialCost: 22,
    estimatedHours: 0.8,
  }),
  item({
    id: "go-demolition-lourde",
    tradeCategoryId: "gros-oeuvre",
    tradeIds: ["demolisseur"],
    workCategory: "Démolition",
    reference: "GO-DEM-002",
    title: "Démolition structure béton",
    description: "Démolition mécanique + tri + évacuation benne",
    unit: "m³",
    unitPriceHt: 85,
    defaultVatRate: 20,
    laborCost: 55,
    materialCost: 22,
    estimatedHours: 1.2,
  }),

  // —— Couverture (compléments) ——
  item({
    id: "cov-velux",
    tradeCategoryId: "couverture",
    tradeIds: ["poseur-fenetres-toit", "couvreur"],
    workCategory: "Couverture",
    reference: "COV-005",
    title: "Pose fenêtre de toit type Velux 78×118",
    description: "Découpe charpente + pose + raccord étanchéité tuiles",
    unit: "U",
    unitPriceHt: 680,
    defaultVatRate: 10,
    laborCost: 280,
    materialCost: 320,
    estimatedHours: 4,
  }),
  item({
    id: "cov-bac-acier",
    tradeCategoryId: "couverture",
    tradeIds: ["couvreur", "couvreur-zingueur"],
    workCategory: "Couverture",
    reference: "COV-006",
    title: "Couverture bac acier double peau",
    description: "Bac acier + isolant + fixations, pente ≥ 5 %",
    unit: "m²",
    unitPriceHt: 98,
    defaultVatRate: 10,
    laborCost: 42,
    materialCost: 48,
    estimatedHours: 1,
  }),

  // —— Second œuvre (compléments) ——
  item({
    id: "so-enduit-platre",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["platrier", "platrier-plaquiste"],
    workCategory: "Plâtrerie",
    reference: "SO-PLA-003",
    title: "Enduit plâtre traditionnel 2 passes",
    description: "Gobetis + corps d'enduit sur maçonnerie",
    unit: "m²",
    unitPriceHt: 38,
    defaultVatRate: 10,
    laborCost: 28,
    materialCost: 6,
    estimatedHours: 0.75,
  }),
  item({
    id: "so-plafond-dalles",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["poseur-plafonds-suspendus"],
    workCategory: "Plafonds",
    reference: "SO-PLF-001",
    title: "Plafond dalles minérales sur ossature",
    description: "Ossature T24 + dalles 60×60 + suspentes",
    unit: "m²",
    unitPriceHt: 55,
    defaultVatRate: 10,
    laborCost: 32,
    materialCost: 18,
    estimatedHours: 0.85,
  }),
  item({
    id: "so-cuisine-equipee",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["poseur-cuisines", "menuisier-agenceur"],
    workCategory: "Agencement",
    reference: "SO-CUI-001",
    title: "Pose cuisine équipée linéaire 3 m",
    description: "Montage meubles + plan de travail + raccordements électro",
    unit: "forfait",
    unitPriceHt: 1200,
    defaultVatRate: 10,
    laborCost: 480,
    materialCost: 0,
    estimatedHours: 12,
  }),
  item({
    id: "so-vitrage-double",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["vitrier"],
    workCategory: "Vitrerie",
    reference: "SO-VIT-001",
    title: "Remplacement vitrage double 4/16/4",
    description: "Dépose ancien vitrage + pose neuf + mastic",
    unit: "m²",
    unitPriceHt: 95,
    defaultVatRate: 10,
    laborCost: 45,
    materialCost: 42,
    estimatedHours: 1,
  }),
  item({
    id: "so-miroir-sur-mesure",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["miroitier", "vitrier"],
    workCategory: "Vitrerie",
    reference: "SO-MIR-001",
    title: "Pose miroir sur mesure",
    description: "Découpe + fixations + scellement ou colles",
    unit: "m²",
    unitPriceHt: 120,
    defaultVatRate: 10,
    laborCost: 55,
    materialCost: 52,
    estimatedHours: 1.2,
  }),
  item({
    id: "so-staff-decoratif",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["staffeur-ornemaniste"],
    workCategory: "Staff",
    reference: "SO-STA-001",
    title: "Corniche staff moulurée",
    description: "Fabrication + pose corniche staff, profil standard",
    unit: "ml",
    unitPriceHt: 65,
    defaultVatRate: 10,
    laborCost: 42,
    materialCost: 15,
    estimatedHours: 1,
  }),
  item({
    id: "so-moquette",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["solier-moquettiste"],
    workCategory: "Sols",
    reference: "SO-SOL-002",
    title: "Pose moquette aiguilletée",
    description: "Préparation support + ragréage + collage moquette",
    unit: "m²",
    unitPriceHt: 32,
    defaultVatRate: 10,
    laborCost: 18,
    materialCost: 10,
    estimatedHours: 0.5,
  }),
  item({
    id: "so-carrelage-mural",
    tradeCategoryId: "second-oeuvre",
    tradeIds: ["carreleur", "carreleur-mosaiste"],
    workCategory: "Carrelage",
    reference: "SO-CAR-002",
    title: "Carrelage mural faïence salle de bain",
    description: "Pose collée + joints, préparation support",
    unit: "m²",
    unitPriceHt: 68,
    defaultVatRate: 10,
    laborCost: 38,
    materialCost: 22,
    estimatedHours: 1,
  }),

  // —— Plomberie & chauffage (compléments) ——
  item({
    id: "pc-clim-split",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["climaticien", "frigoriste"],
    workCategory: "Climatisation",
    reference: "PC-CLI-001",
    title: "Climatisation split mono-split 3,5 kW",
    description: "Unité intérieure + extérieure + liaisons frigorifiques",
    unit: "U",
    unitPriceHt: 1450,
    defaultVatRate: 10,
    laborCost: 420,
    materialCost: 850,
    estimatedHours: 6,
  }),
  item({
    id: "pc-vmc-simple-flux",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["installateur-vmc"],
    workCategory: "Ventilation",
    reference: "PC-VMC-001",
    title: "VMC simple flux hygroréglable",
    description: "Caisson + gaines + bouches + mise en service",
    unit: "forfait",
    unitPriceHt: 980,
    defaultVatRate: 10,
    laborCost: 380,
    materialCost: 480,
    estimatedHours: 8,
  }),
  item({
    id: "pc-poele-bois",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["poseur-poeles-cheminees"],
    workCategory: "Chauffage",
    reference: "PC-POE-001",
    title: "Pose poêle à bois avec tubage",
    description: "Poêle + tubage inox + sortie toiture + mise en service",
    unit: "U",
    unitPriceHt: 2200,
    defaultVatRate: 5.5,
    laborCost: 650,
    materialCost: 1200,
    estimatedHours: 10,
  }),
  item({
    id: "pc-ramonage",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["ramoneur"],
    workCategory: "Entretien",
    reference: "PC-RAM-001",
    title: "Ramonage conduit fumée",
    description: "Ramonage mécanique + certificat conforme",
    unit: "forfait",
    unitPriceHt: 95,
    defaultVatRate: 20,
    laborCost: 75,
    materialCost: 5,
    estimatedHours: 1,
  }),
  item({
    id: "pc-adoucisseur",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["traitement-eau", "plombier"],
    workCategory: "Traitement eau",
    reference: "PC-EAU-001",
    title: "Installation adoucisseur d'eau",
    description: "Adoucisseur + bypass + raccordements + mise en service",
    unit: "U",
    unitPriceHt: 780,
    defaultVatRate: 10,
    laborCost: 220,
    materialCost: 420,
    estimatedHours: 3.5,
  }),
  item({
    id: "pc-douche-italienne",
    tradeCategoryId: "plomberie-chauffage",
    tradeIds: ["installateur-sanitaire", "plombier"],
    workCategory: "Sanitaire",
    reference: "PC-SAN-003",
    title: "Création douche à l'italienne",
    description: "Receveur + bonde + paroi + raccordements, hors carrelage",
    unit: "forfait",
    unitPriceHt: 1650,
    defaultVatRate: 10,
    laborCost: 680,
    materialCost: 720,
    estimatedHours: 12,
  }),

  // —— Électricité (compléments) ——
  item({
    id: "el-interphone",
    tradeCategoryId: "electricite",
    tradeIds: ["electricien-courants-faibles"],
    workCategory: "Courants faibles",
    reference: "EL-CF-001",
    title: "Interphone vidéo 2 fils",
    description: "Platine rue + moniteur + câblage + programmation",
    unit: "U",
    unitPriceHt: 520,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 280,
    estimatedHours: 3,
  }),
  item({
    id: "el-domotique-base",
    tradeCategoryId: "electricite",
    tradeIds: ["domoticien", "electricien-courants-faibles"],
    workCategory: "Domotique",
    reference: "EL-DOM-001",
    title: "Pack domotique éclairage 4 circuits",
    description: "Module + interrupteurs connectés + paramétrage",
    unit: "forfait",
    unitPriceHt: 890,
    defaultVatRate: 10,
    laborCost: 320,
    materialCost: 480,
    estimatedHours: 5,
  }),
  item({
    id: "el-alarme",
    tradeCategoryId: "electricite",
    tradeIds: ["installateur-alarme-videosurveillance"],
    workCategory: "Sécurité",
    reference: "EL-SEC-001",
    title: "Alarme intrusion 4 détecteurs",
    description: "Centrale + détecteurs + sirène + télécommande",
    unit: "forfait",
    unitPriceHt: 780,
    defaultVatRate: 20,
    laborCost: 280,
    materialCost: 420,
    estimatedHours: 5,
  }),
  item({
    id: "el-antenne-tnt",
    tradeCategoryId: "electricite",
    tradeIds: ["antenniste"],
    workCategory: "Antenniste",
    reference: "EL-ANT-001",
    title: "Antenne TNT + parabole collective",
    description: "Antenne extérieure + câblage + réglage réception",
    unit: "U",
    unitPriceHt: 380,
    defaultVatRate: 20,
    laborCost: 150,
    materialCost: 180,
    estimatedHours: 2.5,
  }),
  item({
    id: "el-mise-aux-normes",
    tradeCategoryId: "electricite",
    tradeIds: ["electricien", "electricien-industriel"],
    workCategory: "Électricité",
    reference: "EL-004",
    title: "Mise aux normes NF C 15-100 (T2)",
    description: "Diagnostic + remplacement tableau + circuits prioritaires",
    unit: "forfait",
    unitPriceHt: 1800,
    defaultVatRate: 10,
    laborCost: 850,
    materialCost: 650,
    estimatedHours: 12,
  }),

  // —— Énergies renouvelables (compléments) ——
  item({
    id: "enr-solaire-thermique",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["installateur-solaire-thermique"],
    workCategory: "Solaire thermique",
    reference: "ENR-ST-001",
    title: "Chauffe-eau solaire 300 L",
    description: "Capteurs toiture + ballon + régulation + raccordements",
    unit: "forfait",
    unitPriceHt: 5800,
    defaultVatRate: 5.5,
    laborCost: 1400,
    materialCost: 3800,
    estimatedHours: 16,
  }),
  item({
    id: "enr-chaudiere-pellets",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["installateur-chaudiere-biomasse", "installateur-pompe-a-chaleur"],
    workCategory: "Chauffage",
    reference: "ENR-BIO-001",
    title: "Chaudière granulés 15 kW",
    description: "Chaudière + silo + fumisterie + mise en service",
    unit: "forfait",
    unitPriceHt: 12500,
    defaultVatRate: 5.5,
    laborCost: 2800,
    materialCost: 8200,
    estimatedHours: 28,
  }),
  item({
    id: "enr-audit-energetique",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["auditeur-energetique"],
    workCategory: "Audit",
    reference: "ENR-AUD-001",
    title: "Audit énergétique maison individuelle",
    description: "Visite + thermographie + rapport + préconisations",
    unit: "forfait",
    unitPriceHt: 650,
    defaultVatRate: 20,
    laborCost: 520,
    materialCost: 45,
    estimatedHours: 6,
  }),
  item({
    id: "enr-recuperation-eau",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["installateur-recuperation-eau"],
    workCategory: "Eau pluviale",
    reference: "ENR-EAU-001",
    title: "Récupérateur eau de pluie 5000 L enterré",
    description: "Cuve + pompe + filtres + raccord gouttières",
    unit: "forfait",
    unitPriceHt: 4200,
    defaultVatRate: 10,
    laborCost: 1200,
    materialCost: 2500,
    estimatedHours: 14,
  }),
  item({
    id: "enr-pv-6kw",
    tradeCategoryId: "energies-renouvelables",
    tradeIds: ["installateur-photovoltaique"],
    workCategory: "Photovoltaïque",
    reference: "ENR-PV-002",
    title: "Installation photovoltaïque 6 kWc",
    description: "16 panneaux + onduleur + monitoring + raccordement",
    unit: "forfait",
    unitPriceHt: 11800,
    defaultVatRate: 20,
    laborCost: 2800,
    materialCost: 7500,
    estimatedHours: 28,
  }),

  // —— Menuiseries extérieures (compléments) ——
  item({
    id: "mex-volet-roulant",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["poseur-volets-stores"],
    workCategory: "Fermetures",
    reference: "MEX-VO-001",
    title: "Volet roulant électrique aluminium",
    description: "Tablier + coffre + motorisation + commande",
    unit: "U",
    unitPriceHt: 720,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 480,
    estimatedHours: 3,
  }),
  item({
    id: "mex-store-banne",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["poseur-store-banne"],
    workCategory: "Stores",
    reference: "MEX-ST-001",
    title: "Store banne 4×3 m motorisé",
    description: "Store + coffre + capteur vent + motorisation",
    unit: "U",
    unitPriceHt: 1850,
    defaultVatRate: 10,
    laborCost: 350,
    materialCost: 1300,
    estimatedHours: 4,
  }),
  item({
    id: "mex-veranda",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["verandaliste"],
    workCategory: "Véranda",
    reference: "MEX-VER-001",
    title: "Véranda aluminium 12 m²",
    description: "Structure alu + vitrage + fondations légères",
    unit: "forfait",
    unitPriceHt: 14500,
    defaultVatRate: 10,
    laborCost: 4200,
    materialCost: 8800,
    estimatedHours: 40,
  }),
  item({
    id: "mex-pergola",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["poseur-pergolas"],
    workCategory: "Pergola",
    reference: "MEX-PER-001",
    title: "Pergola bioclimatique aluminium",
    description: "Structure + lames orientables + motorisation",
    unit: "forfait",
    unitPriceHt: 9800,
    defaultVatRate: 20,
    laborCost: 2200,
    materialCost: 6500,
    estimatedHours: 18,
  }),
  item({
    id: "mex-serrurerie-porte",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["serrurier", "serrurier-metallier"],
    workCategory: "Serrurerie",
    reference: "MEX-SER-001",
    title: "Porte blindée bloc-porte",
    description: "Bloc-porte certifié + pose + réglages",
    unit: "U",
    unitPriceHt: 1650,
    defaultVatRate: 10,
    laborCost: 380,
    materialCost: 1050,
    estimatedHours: 5,
  }),
  item({
    id: "mex-portail-coulissant",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["poseur-portails-clotures", "serrurier-metallier"],
    workCategory: "Portail",
    reference: "MEX-POR-001",
    title: "Portail coulissant aluminium 4 m",
    description: "Portail + rail + motorisation + interphone",
    unit: "U",
    unitPriceHt: 4200,
    defaultVatRate: 20,
    laborCost: 850,
    materialCost: 2800,
    estimatedHours: 10,
  }),
  item({
    id: "mex-ferronnerie-garde-corps",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["ferronnier"],
    workCategory: "Ferronnerie",
    reference: "MEX-FER-001",
    title: "Garde-corps fer forgé",
    description: "Fabrication + pose garde-corps sur mesure",
    unit: "ml",
    unitPriceHt: 420,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 200,
    estimatedHours: 4,
  }),
  item({
    id: "mex-porte-entree-alu",
    tradeCategoryId: "menuiseries-exterieures",
    tradeIds: ["menuisier-pvc-alu", "poseur-fenetres"],
    workCategory: "Menuiseries",
    reference: "MEX-PE-001",
    title: "Porte d'entrée aluminium isolante",
    description: "Porte + serrure 3 points + pose + étanchéité",
    unit: "U",
    unitPriceHt: 2200,
    defaultVatRate: 10,
    laborCost: 420,
    materialCost: 1550,
    estimatedHours: 6,
  }),

  // —— Piscine & spa ——
  item({
    id: "pis-piscine-beton",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["pisciniste", "constructeur-piscine-beton"],
    workCategory: "Construction",
    reference: "PIS-001",
    title: "Piscine béton 8×4 m liner",
    description: "Terrassement + gros œuvre + liner + filtration",
    unit: "forfait",
    unitPriceHt: 38000,
    defaultVatRate: 20,
    laborCost: 12000,
    materialCost: 22000,
    estimatedHours: 120,
  }),
  item({
    id: "pis-coque-polyester",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["installateur-piscine-coque", "pisciniste"],
    workCategory: "Construction",
    reference: "PIS-002",
    title: "Piscine coque polyester 7×3,5 m",
    description: "Fouille + pose coque + remblai + filtration",
    unit: "forfait",
    unitPriceHt: 22000,
    defaultVatRate: 20,
    laborCost: 6500,
    materialCost: 13500,
    estimatedHours: 60,
  }),
  item({
    id: "pis-hors-sol",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["piscine-hors-sol"],
    workCategory: "Construction",
    reference: "PIS-003",
    title: "Piscine hors-sol tubulaire 5,5×3,6 m",
    description: "Montage structure + liner + pompe + échelle",
    unit: "forfait",
    unitPriceHt: 2800,
    defaultVatRate: 20,
    laborCost: 450,
    materialCost: 2100,
    estimatedHours: 8,
  }),
  item({
    id: "pis-renovation-etancheite",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["renovation-piscine", "poseur-liner"],
    workCategory: "Rénovation",
    reference: "PIS-004",
    title: "Rénovation étanchéité piscine béton",
    description: "Préparation + enduit étanch + liner neuf",
    unit: "forfait",
    unitPriceHt: 8500,
    defaultVatRate: 20,
    laborCost: 3200,
    materialCost: 4200,
    estimatedHours: 35,
  }),
  item({
    id: "pis-liner",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["poseur-liner"],
    workCategory: "Étanchéité",
    reference: "PIS-005",
    title: "Remplacement liner piscine",
    description: "Dépose ancien + pose liner 75/100 + finitions",
    unit: "forfait",
    unitPriceHt: 4200,
    defaultVatRate: 20,
    laborCost: 1800,
    materialCost: 2000,
    estimatedHours: 20,
  }),
  item({
    id: "pis-entretien-saison",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["entretien-piscine", "pisciniste"],
    workCategory: "Entretien",
    reference: "PIS-006",
    title: "Contrat entretien piscine saison",
    description: "Ouverture + traitement + nettoyage hebdo (6 mois)",
    unit: "forfait",
    unitPriceHt: 680,
    defaultVatRate: 20,
    laborCost: 520,
    materialCost: 95,
    estimatedHours: 12,
  }),
  item({
    id: "pis-traitement-eau",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["traitement-eau-piscine"],
    workCategory: "Traitement",
    reference: "PIS-007",
    title: "Installation électrolyseur sel",
    description: "Cellule + régulation + raccordements filtration",
    unit: "U",
    unitPriceHt: 980,
    defaultVatRate: 20,
    laborCost: 280,
    materialCost: 620,
    estimatedHours: 3.5,
  }),
  item({
    id: "pis-abri-telescopique",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["installateur-abri-piscine"],
    workCategory: "Abri",
    reference: "PIS-008",
    title: "Abri piscine télescopique bas",
    description: "Abri alu + rails + motorisation option",
    unit: "forfait",
    unitPriceHt: 12500,
    defaultVatRate: 20,
    laborCost: 2800,
    materialCost: 8500,
    estimatedHours: 24,
  }),
  item({
    id: "pis-plage-margelles",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["poseur-plages-margelles", "macon-paysagiste"],
    workCategory: "Aménagement",
    reference: "PIS-009",
    title: "Plage piscine dalles pierre reconstituée",
    description: "Préparation + pose dalles + joints + margelles",
    unit: "m²",
    unitPriceHt: 145,
    defaultVatRate: 20,
    laborCost: 55,
    materialCost: 72,
    estimatedHours: 1.2,
  }),
  item({
    id: "pis-spa-exterieur",
    tradeCategoryId: "piscine-spa",
    tradeIds: ["installateur-spa-sauna"],
    workCategory: "Spa",
    reference: "PIS-010",
    title: "Spa extérieur 5 places",
    description: "Spa + raccordements électrique + remplissage + mise en service",
    unit: "U",
    unitPriceHt: 6800,
    defaultVatRate: 20,
    laborCost: 650,
    materialCost: 5500,
    estimatedHours: 6,
  }),

  // —— Aménagement extérieur (compléments) ——
  item({
    id: "ext-entretien-jardin",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["jardinier-espaces-verts", "paysagiste"],
    workCategory: "Entretien",
    reference: "EXT-JAR-001",
    title: "Entretien jardin forfait mensuel",
    description: "Tonte + taille haies + débroussaillage léger",
    unit: "forfait",
    unitPriceHt: 180,
    defaultVatRate: 20,
    laborCost: 145,
    materialCost: 12,
    estimatedHours: 3,
  }),
  item({
    id: "ext-elagage",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["elagueur"],
    workCategory: "Arboriculture",
    reference: "EXT-ELA-001",
    title: "Élagage arbre hauteur ≤ 8 m",
    description: "Taille + évacuation branches, accès nacelle si besoin",
    unit: "U",
    unitPriceHt: 380,
    defaultVatRate: 20,
    laborCost: 280,
    materialCost: 45,
    estimatedHours: 4,
  }),
  item({
    id: "ext-dallage-pierre",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["macon-paysagiste", "paysagiste"],
    workCategory: "Maçonnerie paysagère",
    reference: "EXT-MAC-001",
    title: "Allée dalles béton 40×40",
    description: "Décaissement + lit de sable + pose dalles + joints",
    unit: "m²",
    unitPriceHt: 68,
    defaultVatRate: 20,
    laborCost: 38,
    materialCost: 24,
    estimatedHours: 0.9,
  }),
  item({
    id: "ext-arrosage-auto",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["installateur-arrosage"],
    workCategory: "Arrosage",
    reference: "EXT-ARR-001",
    title: "Arrosage automatique 6 zones",
    description: "Programmateur + électrovanne + arrosage enterré",
    unit: "forfait",
    unitPriceHt: 2200,
    defaultVatRate: 20,
    laborCost: 850,
    materialCost: 1100,
    estimatedHours: 12,
  }),
  item({
    id: "ext-gazon-synthetique",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["poseur-gazon-synthetique"],
    workCategory: "Gazon",
    reference: "EXT-GAZ-001",
    title: "Pose gazon synthétique 40 mm",
    description: "Préparation sol + géotextile + pose + sable de dressage",
    unit: "m²",
    unitPriceHt: 55,
    defaultVatRate: 20,
    laborCost: 22,
    materialCost: 28,
    estimatedHours: 0.5,
  }),
  item({
    id: "ext-creation-massif",
    tradeCategoryId: "amenagement-exterieur",
    tradeIds: ["paysagiste"],
    workCategory: "Plantation",
    reference: "EXT-PAY-001",
    title: "Création massif arbustes et vivaces",
    description: "Préparation sol + plantation + paillage, hors végétaux",
    unit: "m²",
    unitPriceHt: 85,
    defaultVatRate: 20,
    laborCost: 45,
    materialCost: 32,
    estimatedHours: 1,
  }),

  // —— Travaux publics & réseaux ——
  item({
    id: "tp-tranchee-reseau",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["canalisateur", "monteur-reseaux", "assainissement"],
    workCategory: "Réseaux",
    reference: "TP-001",
    title: "Tranchée réseau EU/EP 60 cm",
    description: "Tranchée mécanique + pose tube PVC + remblai",
    unit: "ml",
    unitPriceHt: 95,
    defaultVatRate: 20,
    laborCost: 55,
    materialCost: 32,
    estimatedHours: 1.2,
  }),
  item({
    id: "tp-assainissement-fosse",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["assainissement"],
    workCategory: "Assainissement",
    reference: "TP-002",
    title: "Fosse toutes eaux 3000 L + épandage",
    description: "Fouille + pose fosse + tranchée + remblai",
    unit: "forfait",
    unitPriceHt: 6500,
    defaultVatRate: 20,
    laborCost: 2200,
    materialCost: 3500,
    estimatedHours: 24,
  }),
  item({
    id: "tp-enrobe-voirie",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["constructeur-routes", "conducteur-engins"],
    workCategory: "Voirie",
    reference: "TP-003",
    title: "Enrobé à froid réparation voirie",
    description: "Découpe + préparation + enrobé + compactage",
    unit: "m²",
    unitPriceHt: 45,
    defaultVatRate: 20,
    laborCost: 22,
    materialCost: 18,
    estimatedHours: 0.5,
  }),
  item({
    id: "tp-fibre-optique",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["poseur-fibre-optique"],
    workCategory: "Télécoms",
    reference: "TP-004",
    title: "Raccordement fibre optique domicile",
    description: "Tranchée ou fourreau + tirage fibre + boîtier PTO",
    unit: "forfait",
    unitPriceHt: 580,
    defaultVatRate: 20,
    laborCost: 280,
    materialCost: 220,
    estimatedHours: 4,
  }),
  item({
    id: "tp-reseau-electrique-aerien",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["monteur-reseaux"],
    workCategory: "Réseaux",
    reference: "TP-005",
    title: "Pose câble BT aérien",
    description: "Poteau + câble + accessoires + raccordement",
    unit: "ml",
    unitPriceHt: 38,
    defaultVatRate: 20,
    laborCost: 22,
    materialCost: 12,
    estimatedHours: 0.4,
  }),
  item({
    id: "tp-forage-puits",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["forage-puits"],
    workCategory: "Forage",
    reference: "TP-006",
    title: "Forage puits d'eau 40 m",
    description: "Forage + tubage + pompe immergée + essai",
    unit: "forfait",
    unitPriceHt: 8500,
    defaultVatRate: 20,
    laborCost: 2800,
    materialCost: 4800,
    estimatedHours: 24,
  }),
  item({
    id: "tp-signalisation",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["signalisation-routiere"],
    workCategory: "Signalisation",
    reference: "TP-007",
    title: "Marquage au sol parking",
    description: "Peinture thermoplastique + signalisation horizontale",
    unit: "m²",
    unitPriceHt: 18,
    defaultVatRate: 20,
    laborCost: 8,
    materialCost: 8,
    estimatedHours: 0.2,
  }),
  item({
    id: "tp-terrassement-mecanique",
    tradeCategoryId: "travaux-publics",
    tradeIds: ["conducteur-engins", "canalisateur"],
    workCategory: "Terrassement",
    reference: "TP-008",
    title: "Terrassement mécanique grande masse",
    description: "Décaissement engin + évacuation terres, accès chantier",
    unit: "m³",
    unitPriceHt: 28,
    defaultVatRate: 20,
    laborCost: 18,
    materialCost: 6,
    estimatedHours: 0.3,
  }),

  // —— Rénovation spécialisée (compléments) ——
  item({
    id: "ren-traitement-charpente",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["traitement-charpente"],
    workCategory: "Traitement",
    reference: "REN-CHA-001",
    title: "Traitement curatif charpente xylophages",
    description: "Injection + pulvérisation produit certifié",
    unit: "m³",
    unitPriceHt: 120,
    defaultVatRate: 10,
    laborCost: 65,
    materialCost: 42,
    estimatedHours: 1.5,
  }),
  item({
    id: "ren-desamiantage",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["desamiantage"],
    workCategory: "Désamiantage",
    reference: "REN-DES-001",
    title: "Retrait flocage amiante (SS3)",
    description: "Confinement + retrait + évacuation filière amiante",
    unit: "m²",
    unitPriceHt: 45,
    defaultVatRate: 20,
    laborCost: 28,
    materialCost: 12,
    estimatedHours: 0.6,
  }),
  item({
    id: "ren-deplombage",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["deplombage"],
    workCategory: "Déplombage",
    reference: "REN-DEP-001",
    title: "Déplombage peintures anciennes",
    description: "Protection + décapage + évacuation déchets plomb",
    unit: "m²",
    unitPriceHt: 38,
    defaultVatRate: 20,
    laborCost: 24,
    materialCost: 8,
    estimatedHours: 0.5,
  }),
  item({
    id: "ren-desinsectisation",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["traitement-nuisibles"],
    workCategory: "Nuisibles",
    reference: "REN-NUIS-001",
    title: "Traitement termites localisé",
    description: "Diagnostic + injection produit + suivi",
    unit: "forfait",
    unitPriceHt: 850,
    defaultVatRate: 20,
    laborCost: 420,
    materialCost: 280,
    estimatedHours: 5,
  }),
  item({
    id: "ren-nettoyage-fin-chantier",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["nettoyage-remise-en-etat"],
    workCategory: "Nettoyage",
    reference: "REN-NET-001",
    title: "Nettoyage fin de chantier logement",
    description: "Poussières + vitres + sols + sanitaires",
    unit: "forfait",
    unitPriceHt: 420,
    defaultVatRate: 20,
    laborCost: 320,
    materialCost: 35,
    estimatedHours: 6,
  }),
  item({
    id: "ren-diagnostic-dpe",
    tradeCategoryId: "renovation-specialisee",
    tradeIds: ["diagnostiqueur-immobilier"],
    workCategory: "Diagnostic",
    reference: "REN-DIA-001",
    title: "Diagnostic DPE + amiante + plomb",
    description: "Visite + prélèvements + rapports réglementaires",
    unit: "forfait",
    unitPriceHt: 380,
    defaultVatRate: 20,
    laborCost: 280,
    materialCost: 55,
    estimatedHours: 4,
  }),

  // —— Pierre & patrimoine ——
  item({
    id: "pat-taillee-pierre",
    tradeCategoryId: "pierre-patrimoine",
    tradeIds: ["tailleur-pierre", "sculpteur-pierre"],
    workCategory: "Taille de pierre",
    reference: "PAT-001",
    title: "Restitution pierre de taille",
    description: "Taille + pose pierre calcaire, profil simple",
    unit: "m²",
    unitPriceHt: 280,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 75,
    estimatedHours: 4,
  }),
  item({
    id: "pat-macon-patrimoine",
    tradeCategoryId: "pierre-patrimoine",
    tradeIds: ["macon-patrimoine", "restaurateur-monuments-historiques"],
    workCategory: "Restauration",
    reference: "PAT-002",
    title: "Rejointoiement pierre à la chaux",
    description: "Déjointoiement + mortier chaux NHL + finitions",
    unit: "m²",
    unitPriceHt: 95,
    defaultVatRate: 10,
    laborCost: 65,
    materialCost: 22,
    estimatedHours: 1.5,
  }),
  item({
    id: "pat-marbre",
    tradeCategoryId: "pierre-patrimoine",
    tradeIds: ["marbrier"],
    workCategory: "Marbrerie",
    reference: "PAT-003",
    title: "Plan de travail marbre sur mesure",
    description: "Découpe + polissage + pose + joints",
    unit: "m²",
    unitPriceHt: 420,
    defaultVatRate: 10,
    laborCost: 120,
    materialCost: 260,
    estimatedHours: 3,
  }),
  item({
    id: "pat-sculpture-pierre",
    tradeCategoryId: "pierre-patrimoine",
    tradeIds: ["sculpteur-pierre"],
    workCategory: "Sculpture",
    reference: "PAT-004",
    title: "Sculpture ornement pierre",
    description: "Motif décoratif sur mesure, pierre calcaire",
    unit: "U",
    unitPriceHt: 1800,
    defaultVatRate: 10,
    laborCost: 1200,
    materialCost: 350,
    estimatedHours: 20,
  }),
  item({
    id: "pat-restoration-facade",
    tradeCategoryId: "pierre-patrimoine",
    tradeIds: ["restaurateur-monuments-historiques", "macon-patrimoine"],
    workCategory: "Restauration",
    reference: "PAT-005",
    title: "Restauration façade pierre (ABF)",
    description: "Diagnostic + reprise pierres + enduits chaux",
    unit: "m²",
    unitPriceHt: 320,
    defaultVatRate: 10,
    laborCost: 180,
    materialCost: 95,
    estimatedHours: 5,
  }),

  // —— Conception, étude & encadrement ——
  item({
    id: "con-mission-architecte",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["architecte"],
    workCategory: "Architecture",
    reference: "CON-001",
    title: "Mission architecte esquisse + APS",
    description: "Esquisse + avant-projet sommaire, honoraires forfaitaires",
    unit: "forfait",
    unitPriceHt: 4500,
    defaultVatRate: 20,
    laborCost: 4200,
    materialCost: 80,
    estimatedHours: 40,
  }),
  item({
    id: "con-architecte-interieur",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["architecte-interieur", "decorateur-interieur"],
    workCategory: "Architecture intérieure",
    reference: "CON-002",
    title: "Conception aménagement intérieur",
    description: "Plans 2D/3D + planche matériaux + shopping list",
    unit: "forfait",
    unitPriceHt: 2800,
    defaultVatRate: 20,
    laborCost: 2500,
    materialCost: 120,
    estimatedHours: 24,
  }),
  item({
    id: "con-maitre-oeuvre",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["maitre-oeuvre"],
    workCategory: "Maîtrise d'œuvre",
    reference: "CON-003",
    title: "Maîtrise d'œuvre rénovation lourde",
    description: "Consultation entreprises + suivi chantier + réception",
    unit: "forfait",
    unitPriceHt: 8500,
    defaultVatRate: 20,
    laborCost: 7800,
    materialCost: 200,
    estimatedHours: 80,
  }),
  item({
    id: "con-economiste",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["economiste-construction"],
    workCategory: "Économie",
    reference: "CON-004",
    title: "Estimation quantitatif estimatif (DQE)",
    description: "Métrés + chiffrage détaillé poste par poste",
    unit: "forfait",
    unitPriceHt: 1200,
    defaultVatRate: 20,
    laborCost: 1050,
    materialCost: 50,
    estimatedHours: 12,
  }),
  item({
    id: "con-topographie",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["geometre-topographe"],
    workCategory: "Topographie",
    reference: "CON-005",
    title: "Levé topographique terrain",
    description: "Relevé + plan coté + bornage provisoire",
    unit: "forfait",
    unitPriceHt: 980,
    defaultVatRate: 20,
    laborCost: 750,
    materialCost: 120,
    estimatedHours: 8,
  }),
  item({
    id: "con-etudes-structure",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["bureau-etudes"],
    workCategory: "Bureau d'études",
    reference: "CON-006",
    title: "Étude structure béton armé",
    description: "Calcul notes + plans d'exécution fondations/dalle",
    unit: "forfait",
    unitPriceHt: 2200,
    defaultVatRate: 20,
    laborCost: 2000,
    materialCost: 80,
    estimatedHours: 20,
  }),
  item({
    id: "con-conducteur-travaux",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["conducteur-travaux"],
    workCategory: "Encadrement",
    reference: "CON-007",
    title: "Conduite de travaux (forfait mensuel)",
    description: "Pilotage planning + coordination corps d'état",
    unit: "forfait",
    unitPriceHt: 3200,
    defaultVatRate: 20,
    laborCost: 3000,
    materialCost: 50,
    estimatedHours: 30,
  }),
  item({
    id: "con-sps",
    tradeCategoryId: "conception-encadrement",
    tradeIds: ["coordinateur-sps"],
    workCategory: "SPS",
    reference: "CON-008",
    title: "Coordination SPS niveau 2",
    description: "PGC + inspections + registre sécurité",
    unit: "forfait",
    unitPriceHt: 1800,
    defaultVatRate: 20,
    laborCost: 1650,
    materialCost: 60,
    estimatedHours: 16,
  }),
];
